/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/renderer/astryx-theme/makaTheme.ts
 * Command: astryx theme build src/renderer/astryx-theme/makaTheme.ts --out src/renderer/astryx-theme/maka.css
 * Generated: 2026-07-30T16:28:12.131Z
 */

/// <reference path="./maka.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const neutralIconRegistry: IconRegistry;
export declare const makaTheme: DefinedTheme;
