/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/renderer/astryx-theme/makaTheme.ts
 * Command: astryx theme build src/renderer/astryx-theme/makaTheme.ts --out src/renderer/astryx-theme/maka.css
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
