/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

import type { UiCatalog, UiLocale } from '@maka/core/ui-locale';

type WidenCopy<T> = T extends string
  ? string
  : T extends (...args: infer Args) => string
    ? (...args: Args) => string
    : { [K in keyof T]: WidenCopy<T[K]> };

// Capability-section strings for the connection detail page — the add-provider
// form deliberately carries no declaration controls (capabilities are edited
// after the connection exists).
const zhCapabilitiesCopy = {
  capabilities: '能力',
  thinkingEffort: '思考档位（reasoning_effort）',
  thinkingEffortHelp: '勾选需要的思考强度档位，不勾选即为不声明。',
  thinkingUndeclared: '未声明',
  thinkingSelectedCount: (count: number) => `已选择 ${count} 个`,
  thinkingBulk: '批量设置思考档位',
  thinkingBulkCoverage: (declared: number, total: number) =>
    declared === 0 ? '全部未声明' : `${declared}/${total} 个模型`,
  visionInput: '视觉输入（vision）',
  visionInputHelp: '「自动」跟随内置元数据；「启用/禁用」是显式声明，覆盖自动判断。',
  visionAuto: '自动',
  visionEnabledOption: '启用',
  visionDisabledOption: '禁用',
  contextWindow: '上下文窗口（tokens）',
  contextWindowHelp: '设置后作为 Maka 压缩的触发阈值。留空则不主动压缩，由供应商决定何时超限。',
  contextWindowHint: (tokens: number) => `该模型声明的窗口为 ${tokens} tokens`,
  contextWindowApplyHint: '填入',
  fastMode: 'Fast 模式',
  fastModeHelp: '使用 OpenAI 的 fast service tier；留空跟随服务商默认值。',
  fastAuto: '自动',
  fastEnabled: 'Fast',
};
const zhTwCapabilitiesCopy = {
  capabilities: '能力',
  thinkingEffort: '思考檔位（reasoning_effort）',
  thinkingEffortHelp: '勾選需要的思考強度檔位，不勾選即為不宣告。',
  thinkingUndeclared: '未宣告',
  thinkingSelectedCount: (count: number) => `已選擇 ${count} 個`,
  thinkingBulk: '批次設定思考檔位',
  thinkingBulkCoverage: (declared: number, total: number) =>
    declared === 0 ? '全部未宣告' : `${declared}/${total} 個模型`,
  visionInput: '視覺輸入（vision）',
  visionInputHelp: '「自動」跟隨內建後設資料；「啟用/停用」是顯式宣告，覆蓋自動判斷。',
  visionAuto: '自動',
  visionEnabledOption: '啟用',
  visionDisabledOption: '停用',
  contextWindow: '上下文視窗（tokens）',
  contextWindowHelp: '聲明後壓縮與預算按此值計算；留空跟隨內建後設資料。',
  contextWindowHint: (tokens: number) => `該模型宣告的視窗為 ${tokens} tokens`,
  contextWindowApplyHint: '填入',
  fastMode: 'Fast 模式',
  fastModeHelp: '使用 OpenAI 的 fast service tier；留空跟隨服務商預設值。',
  fastAuto: '自動',
  fastEnabled: 'Fast',
};
const enCapabilitiesCopy = {
  capabilities: 'Capabilities',
  thinkingEffort: 'Thinking levels (reasoning_effort)',
  thinkingEffortHelp: 'Tick the thinking levels this model supports; none ticked means undeclared.',
  thinkingUndeclared: 'Undeclared',
  thinkingSelectedCount: (count: number) => `${count} selected`,
  thinkingBulk: 'Set thinking levels for all models',
  thinkingBulkCoverage: (declared: number, total: number) =>
    declared === 0 ? 'On no model' : `On ${declared} of ${total} models`,
  visionInput: 'Vision input',
  visionInputHelp: 'Auto follows built-in metadata; Enabled/Disabled overrides it explicitly.',
  visionAuto: 'Auto',
  visionEnabledOption: 'Enabled',
  visionDisabledOption: 'Disabled',
  contextWindow: 'Context window (tokens)',
  contextWindowHelp: 'When set, Maka compacts once the previous request\'s real usage exceeds it. Leave empty to never compact proactively; the provider decides.',
  contextWindowHint: (tokens: number) => `This model declares a ${tokens}-token window`,
  contextWindowApplyHint: 'Use it',
  fastMode: 'Fast mode',
  fastModeHelp: "Use OpenAI's fast service tier; empty follows the provider default.",
  fastAuto: 'Auto',
  fastEnabled: 'Fast',
};

const zhCopy = {
  detail: {
    delete: '删除', cancel: '取消', deleteUnused: '不再需要，删除连接',
    deleteFailed: '删除模型连接失败', credentialReadFailed: '读取模型凭据状态失败', refreshFailed: '刷新模型连接失败',
    saveFailed: '保存模型连接失败', saveModelsFailed: '保存启用模型失败',
    modelKey: '模型密钥', pasteModelKey: '粘贴模型密钥', getModelKey: '获取模型密钥', saving: '保存中…',
    advancedRequest: '高级请求设置', advancedRequestHelp: '为这个连接的 HTTP 请求添加请求头和额外 JSON 请求体。请求头值作为凭据保存在本机。',
    requestHeaders: '自定义请求头', headerName: '请求头名称', headerValue: '请求头值', retainedHeaderValue: '保留已保存的值', addHeader: '添加请求头', removeHeader: '移除', noRequestHeaders: '未设置自定义请求头。',
    extraRequestBody: '额外请求体（JSON）', extraRequestBodyHelp: '仅添加顶层字段；若与 Maka 生成的字段重名，请求会明确失败。', requestCustomizationInvalid: '请求设置无效', requestHeadersInvalidDetail: '请检查请求头名称和值。', requestBodyInvalidDetail: '请输入符合要求的 JSON 对象。', saveAdvancedRequest: '保存高级请求设置', configuredHeaders: (count: number) => `${count} 个请求头`, noAdvancedRequest: '未设置',
    oauthLoggedIn: 'OAuth 已登录', oauthLoading: 'OAuth 状态读取中', oauthUnknown: 'OAuth 状态未知', oauthWaiting: '等待 OAuth 登录',
    oauthLoggedInDetail: '该模型连接使用主进程保存的 OAuth access token；若请求提示需要重新登录，请到账号连接重新授权。',
    oauthLoadingDetail: '正在读取本机 OAuth 登录状态，读取完成前不会把未知状态显示成未登录。',
    oauthUnknownDetail: '暂时无法读取本机 OAuth 登录状态；请刷新页面或重新打开设置。',
    oauthWaitingDetail: '请到账号连接完成登录；登录成功后会自动出现在模型连接里。',
    oauthRetired: '此登录方式已停用',
    oauthRetiredDetail:
      '这条连接使用的登录方式已从 Maka 移除，无法再登录，也无法用于对话。改用 Anthropic API Key 连接即可继续使用 Claude 模型；删除这条连接会一并清除本机保存的登录凭据。',
    credentialLoadingDetail: '正在读取模型凭据状态，读取完成前暂不测试连接或刷新模型。',
    credentialUnknownDetail: '模型凭据状态暂时没刷新成功，已避免把未知状态显示成未登录或未配置。',
    testConnection: '测试连接',
    updateModels: '更新模型目录', endpoint: '服务地址',
    connectionName: '名称',
    connectionNamePlaceholder: '给这个连接起个名字',
    addModel: '添加模型',
    addModelConfirm: '添加',
    addModelIdField: '模型 ID',
    addModelIdFieldHelp: '需与服务商完全一致，区分大小写。',
    addModelIdPlaceholder: 'deepseek-v4-pro-beta',
    addModelIdRequired: '请填写模型 ID。',
    addModelIdDuplicate: '该模型已在列表中。',
    addModelContextWindow: '上下文窗口',
    addModelContextWindowHelp: '服务商模型页给出的最大 token 数。缺少它 Maka 只能按 32k 处理，长对话会被提前截断。',
    addModelContextWindowRequired: '请填写上下文窗口。',
    credentials: '连接', dangerZone: '删除连接', deleteRowHelp: '此操作不可撤销。',
    credentialsHelp: '密钥只保存在本机。',
    credentialsHelpAccount: '登录令牌只保存在本机。',
    modelManagementHelp: '这些模型会出现在任务的模型选择器里。',
    ...zhCapabilitiesCopy,
    capabilitiesHelp: '配置这个模型的上下文长度、视觉支持与思考档位，保存后生效。',
    // Row affordances (settings-sidebar 的 InfoRow / ExpandableRow 语言)：一行
    // 只报状态，改的时候才展开成输入框。
    change: '更换', set: '设置', edit: '编辑', save: '保存',
    endpointManaged: '由账号登录或服务商管理',
    endpointMissing: '尚未配置服务地址',
    endpointModelOverridesNote: '部分模型会通过其他服务端点发送请求',
    endpointCredentialsMasked: '已保存的地址内嵌凭据,编辑时默认隐藏',
    modelManagement: '模型',
    disconnectAndDelete: '退出账号并删除',
    login: '登录', loggingIn: '登录中…', relogin: '重新登录',
    oauthReloginDetail: '若请求提示需要重新登录，点这里重新走一遍授权。', deviceCode: '登录码：',
    oauthStartDetail: '点下方按钮打开浏览器完成登录，授权成功后会自动刷新这里的状态。',
    status: '连接状态', statusHealthy: '正常', statusUntested: '未测试',
    modelsSummary: (enabled: number, total: number) => `已启用 ${enabled} / ${total}`,
    filterModels: '搜索模型', noModelsMatch: '未找到匹配的模型',
    enableModelAria: (name: string) => `启用模型 ${name}`,
    declareCapabilities: '配置参数', declareCapabilitiesAria: (name: string) => `配置模型参数：${name}`,
    modelUndescribed: '缺少该模型的参数信息，请手动配置。',
    visionToken: '视觉', thinkingToken: '思考', contextToken: (value: string) => `${value} 上下文`,
    noModels: '暂无可选模型，请先更新模型目录。',
    keySet: '已设置', statusLoading: '正在读取状态', credentialUnknown: '凭据状态未知', keyMissing: '尚未设置密钥',
    keyTroubleshooting: '模型密钥 / 服务地址 / 代理设置', endpointTroubleshooting: '本地服务 / 服务地址 / 代理设置', oauthTroubleshooting: 'OAuth 登录 / 代理设置',
    unknownDescription: (provider: string) => `该连接使用的 provider「${provider}」在当前版本未注册。配置和凭据会保留，切回支持它的版本即可继续使用。`,
    deleteProviderTitle: (name: string) => `删除供应商 ${name}？`,
    deleteConnectionTitle: (name: string) => `删除模型连接 ${name}？`,
    deleteUnknownDescription: '删除后，支持该 provider 的其他版本也无法恢复这条连接及其凭据。',
    deleteDescription: (isDefault: boolean, disconnectsAccount: boolean) => [
      disconnectsAccount
        ? '这会退出本机账号、删除 OAuth 凭据和模型连接；刷新后不会自动重新创建。'
        : '这会删除模型连接及其本机凭据；如需再次使用，需要重新添加。',
      isDefault
        ? '它当前是默认连接；删除后默认模型会变成未设置，已有任务可能需要重新选择模型。'
        : '',
    ].filter(Boolean).join(' '),
    connectionSuccess: (name: string) => `连接成功 · ${name}`, connectionFailed: (name: string) => `连接失败 · ${name}`,
    connectionFallbackTitle: (name: string) => `连接可用 · ${name}`,
    connectionFallbackDetail: (selected: readonly string[], tested: string) =>
      `你选择的 ${selected.join('、')} 当前未响应，已改用 ${tested} 验证连接可用；任务中继续使用你选择的模型可能会失败。`,
    connectionTestError: (name: string) => `连接测试出错 · ${name}`, modelsFetched: (count: number, name: string) => `已拉取 ${count} 个模型 · ${name}`,
    modelsFetchFailed: (name: string) => `拉取模型失败 · ${name}`,
    modelsFetchFailedDetail: (message: string, troubleshooting: string) => `${message} · 当前继续显示静态列表，请确认 ${troubleshooting} 后重试。`,
    authTroubleshooting: (value: string) => `鉴权失败，请确认 ${value} 后重试。`, recheckTroubleshooting: (value: string) => `检查 ${value} 后重试。`,
    modelKeyAria: (name: string) => `${name} 模型密钥`,
  },
  shared: {
    actionFallback: '模型连接服务暂时不可用，请稍后重试。', rateLimit: '当前账号或模型服务触发速率限制，请稍后重试。',
    timeout: '请求超时，请检查网络或代理后重试。', unavailable: '模型服务暂时不可用，请稍后重试。',
    network: '网络错误，请检查服务地址或代理设置后重试。', statusUnavailable: '连接测试状态暂时无法显示，请重新测试。',
    // Every list that a search box narrows says how many rows are left, so the
    // change is spoken rather than only shown.
    filterMatches: (count: number) => (count === 0 ? '没有匹配的结果' : `${count} 个匹配结果`),
    connectionStatuses: { retired: '已停用 · 请删除', reauth: '需要重新登录', disabledFailed: '暂不可用 · 上次连接失败', disabled: '暂不可用', failed: '上次连接失败' },
    lastTest: {
      '连接已验证': '连接已验证', '鉴权失败': '鉴权失败', '请求超时': '请求超时', '网络错误': '网络错误', '模型服务返回错误': '模型服务返回错误', '连接测试失败': '连接测试失败',
      'connection verified': '连接已验证', 'authentication failed': '鉴权失败', 'request timed out': '请求超时', 'network error': '网络错误', 'provider returned an error': '模型服务返回错误', 'connection test failed': '连接测试失败',
      'claude oauth 未登录。': 'Claude OAuth 未登录。', 'claude oauth 本地凭据读取失败。': 'Claude OAuth 本地凭据读取失败。', 'claude oauth 需要重新登录。': 'Claude OAuth 需要重新登录。', 'claude oauth 已登录。': 'Claude OAuth 已登录。', 'claude oauth 已退出登录。': 'Claude OAuth 已退出登录。',
      'codex oauth 未登录。': 'Codex OAuth 未登录。', 'codex oauth 本地凭据读取失败。': 'Codex OAuth 本地凭据读取失败。', 'codex oauth 需要重新登录。': 'Codex OAuth 需要重新登录。', 'codex oauth 已登录。': 'Codex OAuth 已登录。', 'codex oauth 已退出登录。': 'Codex OAuth 已退出登录。',
      '当前账号无可用 codex 模型。': '当前账号无可用 Codex 模型。', 'codex 模型列表获取失败。': 'Codex 模型列表获取失败。',
      'github copilot 需要重新导入 github cli 登录。': 'GitHub Copilot 需要重新导入 GitHub CLI 登录。', 'github copilot 无法读取当前账号可用模型，请重新验证登录。': 'GitHub Copilot 无法读取当前账号可用模型，请重新验证登录。', 'github copilot 登录已导入。': 'GitHub Copilot 登录已导入。', 'github copilot 连接未能保存，请重新导入登录。': 'GitHub Copilot 连接未能保存，请重新导入登录。', 'github copilot 已移除本地登录。': 'GitHub Copilot 已移除本地登录。',
    },
  },
  panel: {
    groups: { recommended: '推荐', plans: '订阅计划', api: 'API', aggregators: '聚合服务', local: '本地' },
    loadFailed: '载入模型连接失败', loadingAria: '正在加载模型供应商', connections: '模型连接',
    connectionsHelp: '已启用的模型会显示在任务的模型选择器中。',
    retry: '点击重试。', empty: '还没有模型连接', connectionRemoved: '原连接已被删除或移除，已返回模型连接列表。',
    connectedLoading: '连接已添加，正在载入详情…', connectedLoadFailed: '连接已添加，但暂时无法刷新连接列表。',
    connectionIdentityChanged: '新连接的身份与登录结果不一致，请返回连接列表后重试。',
    emptyHelp: '从下方的常用服务商开始，或浏览全部服务商。', recommended: '推荐服务商', browseAll: '查看全部服务商',
    default: '默认', setDefault: '设为默认', setDefaultTitle: '让新任务默认使用这个连接', setDefaultPending: '设置中…', setDefaultFailed: '设为默认失败', addHelp: '选择账号登录、模型计划、API、聚合服务或本地运行时。',
    searchPlaceholder: '搜索服务商', searchAria: '搜索模型服务商', noMatch: '未找到匹配的服务商', clearSearch: '清除搜索',
    createSubtitle: '完成必要配置后，连接会出现在模型页上方。', connection: '模型连接',
    count: (value: number) => `· ${value}`, modelCount: (value: number) => `${value} 个模型`, connectTitle: (name: string) => `连接 ${name}`,
    chipAria: (name: string, provider: string, isDefault: boolean, status?: string) => `模型连接：${name}，供应商：${provider}${isDefault ? '，默认连接' : ''}${status ? `，${status}` : ''}`,
    addConnection: '添加连接', backToList: '返回模型连接', backToCatalog: '返回服务商列表',
  },
  catalog: {
    unavailable: '未开放',
    cardAria: (name: string, description: string) => `添加模型供应商：${name}，${description}`,
  },
  add: {
    invalidSlug: '连接标识格式不正确', duplicateSlug: '连接标识已存在', cloudflareAccount: '请填写 Cloudflare Account ID', endpointRequired: '这个供应商需要填写服务地址',
    accountLogin: '请到账号连接完成登录；登录成功后会自动创建模型连接。',
    apiKeyPlaceholder: '输入或粘贴 API Key', cancel: '取消', accountTitle: '使用账号连接登录',
    advancedRequest: '高级请求设置', expandAdvancedRequest: '展开高级请求设置', collapseAdvancedRequest: '收起高级请求设置',
    requestHeaders: '自定义请求头', headerName: '请求头名称', headerValue: '请求头值', retainedHeaderValue: '保留已保存的值', addHeader: '添加请求头', removeHeader: '移除', noRequestHeaders: '未设置自定义请求头。',
    extraRequestBody: '额外请求体（JSON）', extraRequestBodyHelp: '仅添加顶层字段；与 Maka 生成字段重名时会明确失败。请求头值将作为凭据保存在本机。', requestCustomizationInvalid: '请检查高级请求设置。',
    accountDetail: '不要在这里手动添加；请回到模型连接页的账号连接完成登录，Maka 会自动创建并刷新模型连接。',
    slug: '连接标识', name: '显示名称',
    accountIdPlaceholder: '填写账户 ID',
    saving: '保存中…', save: '保存供应商', keyRequired: (name: string) => `请填写 ${name} API Key`,
    apiKeyLabel: 'API Key', accountIdLabel: 'Cloudflare Account ID', endpointLabel: '服务地址',
    defaultModel: '默认模型', defaultModelPlaceholder: '留空即可，保存后自动拉取', defaultModelHelp: '保存后 Maka 会向该端点拉取模型目录。只有当端点不提供目录时，才需要在这里手填一个模型 ID。',
    stepsAria: '添加连接步骤', stepCredentials: '密钥', stepModels: '选择模型',
    onboardingVerifyAndChoose: '验证并选择模型', onboardingVerifying: '正在验证密钥并获取模型…',
    onboardingChooseModels: '选择此连接使用的模型', onboardingChooseModelsHelp: '添加后仍可在连接详情中启用其他模型。', onboardingEnabledModels: '启用的模型', onboardingSearchModels: '搜索模型', onboardingAddConnection: '添加连接', onboardingBack: '返回修改',
    onboardingSelectedCount: (selected: number, total: number) => `已选 ${selected} / ${total}`, onboardingSelectAll: '全选', onboardingClearAll: '取消全选', onboardingNoModelsMatch: '未找到匹配的模型',
    onboardingDefaultModel: '默认模型', onboardingDefaultModelHelp: '新任务将默认使用此模型，仅可在已勾选的模型中选择。',
    onboardingAuthFailed: '密钥验证失败，请检查后重试。', onboardingTimeout: '验证超时，请检查网络或代理后重试。', onboardingNetwork: '无法连接模型服务，请检查网络、代理或服务地址。', onboardingUnavailable: '模型连接服务暂时不可用，请稍后重试。', onboardingInvalidResponse: '模型服务返回了无法识别的结果，请稍后重试。', onboardingCatalogFull: '连接数量已达上限，请先删除不再使用的连接。', onboardingModelsChanged: '可用模型已发生变化，请重新验证后选择。', onboardingNoModels: '没有发现可用模型，当前未创建连接。', onboardingSelectModel: '请至少启用一个模型。',
    onboardingOutcomeUnknown: '保存结果暂时无法确认', onboardingOutcomeUnknownDetail: '请勿再次添加，以免创建重复连接。重新加载连接列表并检查该连接是否已经出现；仍不确定时请先重连 Runtime Host。', onboardingReloadConnections: '重新加载连接列表', onboardingRestart: '仍要添加另一个连接',
    ...zhCapabilitiesCopy,
  },
  oauthFlow: {
    refreshFailed: '刷新登录状态失败', accountActionFailed: (name: string) => `${name} 账号操作失败`, loginFailedRetry: '登录失败，请稍后重试。',
    retry: '请稍后再试。', startFailed: '无法开始登录', startFailedRetry: '无法开始登录，请稍后再试。', openFailed: '无法打开浏览器',
    openFailedRetry: '无法打开浏览器，请稍后重试。', loginSuccess: '登录成功', bound: (name: string) => `${name} 已绑定本机。`,
    incomplete: '登录未完成', incompleteRetry: '登录未完成，请重新打开浏览器授权。', loginFailed: '登录失败',
    logoutDescription: '将删除本机保存的订阅凭据，之后需要重新登录才能继续使用这些 OAuth 模型。', logout: '退出登录', cancel: '取消',
    loggedOut: '已退出登录', credentialsCleared: '本地凭据已清除。', logoutFailed: '退出失败', logoutFailedRetry: '退出登录失败，请稍后重试。',
    serviceUnavailable: '登录服务暂时不可用，请检查网络后重试。',
    logoutTitle: (name: string) => `退出 ${name} 登录？`,
  },
  oauthSection: {
    signedIn: '已登录', codexDescription: '使用 ChatGPT Plus / Pro 账号添加连接。', xaiDescription: '使用 SuperGrok / X Premium 账号添加连接。',
    configuredConnections: (count: number) => `已有 ${count} 个连接 · 添加另一个账号`,
    copilotDescription: '使用 GitHub 登录连接 Copilot 订阅，或导入兼容凭据。', serviceUnavailable: '登录服务暂时不可用，请检查网络后重试。',
    aria: 'OAuth 登录',
    staleState: 'OAuth 登录状态暂时没刷新成功，已保留上一次状态。',
    codexDetail: '点击下方按钮打开设备授权页，并在页面中输入这里显示的登录码。', xaiDetail: '点击下方按钮打开浏览器登录，授权完成后会自动回写。', deviceCode: '登录码：',
    openingBrowser: '打开浏览器…', waitingAuthorization: '等待浏览器授权…', logout: '退出登录', loggingOut: '退出中…',
    copilotSubtitle: '使用 GitHub 登录，或导入兼容凭据；token 不会暴露给渲染进程。', copilotImported: '已导入 GitHub Copilot 订阅账号。',
    copilotSetup: '使用 GitHub 登录以连接 Copilot，或导入已有的 gh 凭据。', importing: '导入中…',
    copilotSignIn: '使用 GitHub 登录', copilotActionFailed: 'GitHub Copilot 账号操作失败',
    copilotSignInDisabledHint: '本机未启用 GitHub 登录；请改用导入兼容凭据，或由管理员启用后重试。',
    importCredential: '导入兼容凭据',
    loadingAccount: '正在加载账号状态…', authorizing: '请在弹出的浏览器窗口完成登录。', refreshing: '正在刷新访问令牌…', refreshTokenFailed: '令牌刷新失败，请重新登录。',
    cardAria: (intent: 'add' | 'import' | 'manage', name: string, status: string | undefined, description: string) => `${intent === 'add' ? '添加' : intent === 'import' ? '导入' : '管理'}账号连接：${name}${status ? `，状态：${status}` : ''}，${description.replace(/[。.!！？?]+$/u, '')}`,
    connectTitle: (name: string) => `连接 ${name}`, addAccountTitle: (name: string) => `添加 ${name} 账号`, login: (name: string) => `登录 ${name}`, loginAndAdd: '登录并添加', signedOut: (name: string) => `${name} 尚未登录。`,
    storageFailed: (name: string) => `${name} 本地凭据读取失败，请重新登录。`, providerUnavailable: (name: string) => `${name} 已登录，但当前 provider 状态不可用。`,
  },
} as const;

export type ProviderSettingsCopy = WidenCopy<typeof zhCopy>;

const zhTwCopy = {
  detail: {
    deviceCode: '登入碼：',
    delete: '刪除', cancel: '取消', deleteUnused: '不再需要，刪除連線',
    deleteFailed: '刪除模型連線失敗', credentialReadFailed: '讀取模型憑據狀態失敗', refreshFailed: '重新整理模型連線失敗',
    saveFailed: '儲存模型連線失敗', saveModelsFailed: '儲存啟用模型失敗',
    modelKey: '模型金鑰', pasteModelKey: '貼上模型金鑰', getModelKey: '取得模型金鑰', saving: '儲存中…',
    advancedRequest: '高階請求設定', advancedRequestHelp: '為這個連線的 HTTP 請求新增請求頭和額外 JSON 請求體。請求頭值作為憑據儲存在本機。',
    requestHeaders: '自訂請求頭', headerName: '請求頭名稱', headerValue: '請求頭值', retainedHeaderValue: '保留已儲存的值', addHeader: '新增請求頭', removeHeader: '移除', noRequestHeaders: '未設定自訂請求頭。',
    extraRequestBody: '額外請求體（JSON）', extraRequestBodyHelp: '僅新增頂層欄位；若與 Maka 生成的欄位重名，請求會明確失敗。', requestCustomizationInvalid: '請求設定無效', requestHeadersInvalidDetail: '請檢查請求頭名稱和值。', requestBodyInvalidDetail: '請輸入符合要求的 JSON 物件。', saveAdvancedRequest: '儲存高階請求設定', configuredHeaders: (count: number) => `${count} 個請求頭`, noAdvancedRequest: '未設定',
    oauthLoggedIn: 'OAuth 已登入', oauthLoading: 'OAuth 狀態讀取中', oauthUnknown: 'OAuth 狀態未知', oauthWaiting: '等待 OAuth 登入',
    oauthLoggedInDetail: '該模型連線使用主程序儲存的 OAuth access token；若請求提示需要重新登入，請到帳號連線重新授權。',
    oauthLoadingDetail: '正在讀取本機 OAuth 登入狀態，讀取完成前不會把未知狀態顯示成未登入。',
    oauthUnknownDetail: '暫時無法讀取本機 OAuth 登入狀態；請重新整理頁面或重新開啟設定。',
    oauthWaitingDetail: '請到帳號連線完成登入；登入成功後會自動出現在模型連線裡。',
    oauthRetired: '此登入方式已停用',
    oauthRetiredDetail:
      '這條連線使用的登入方式已從 Maka 移除，無法再登入，也無法用於對話。改用 Anthropic API Key 連線即可繼續使用 Claude 模型；刪除這條連線會一併清除本機儲存的登入憑據。',
    credentialLoadingDetail: '正在讀取模型憑據狀態，讀取完成前暫不測試連線或重新整理模型。',
    credentialUnknownDetail: '模型憑據狀態暫時沒重新整理成功，已避免把未知狀態顯示成未登入或未設定。',
    testConnection: '測試連線',
    updateModels: '更新模型目錄', endpoint: '服務地址',
    connectionName: '名稱',
    connectionNamePlaceholder: '給這個連線起個名字',
    addModel: '新增模型',
    addModelConfirm: '新增',
    addModelIdField: '模型 ID',
    addModelIdFieldHelp: '需與服務商完全一致，區分大小寫。',
    addModelIdPlaceholder: 'deepseek-v4-pro-beta',
    addModelIdRequired: '請填寫模型 ID。',
    addModelIdDuplicate: '該模型已在列表中。',
    addModelContextWindow: '上下文視窗',
    addModelContextWindowHelp: '服務商模型頁給出的最大 token 數。缺少它 Maka 只能按 32k 處理，長對話會被提前截斷。',
    addModelContextWindowRequired: '請填寫上下文視窗。',
    credentials: '連線', dangerZone: '刪除連線', deleteRowHelp: '此操作不可撤銷。',
    credentialsHelp: '金鑰只儲存在本機。',
    credentialsHelpAccount: '登入權杖只儲存在本機。',
    modelManagementHelp: '這些模型會出現在任務的模型選擇器裡。',
    ...zhTwCapabilitiesCopy,
    capabilitiesHelp: '宣告每個已啟用模型的思考檔位、視覺與上下文視窗；儲存後生效。',
    // Row affordances (settings-sidebar 的 InfoRow / ExpandableRow 語言)：一行
    // 只報狀態，改的時候才展開成輸入框。
    change: '更換', set: '設定', edit: '編輯', save: '儲存',
    endpointManaged: '由帳號登入或服務商管理',
    endpointMissing: '尚未設定服務地址',
    endpointModelOverridesNote: '部分模型會透過其他服務端點發送請求',
    endpointCredentialsMasked: '已儲存的地址內嵌憑據,編輯時預設隱藏',
    modelManagement: '模型',
    disconnectAndDelete: '退出帳號並刪除',
    login: '登入', loggingIn: '登入中…', relogin: '重新登入',
    oauthReloginDetail: '若請求提示需要重新登入，點這裡重新走一遍授權。',
    oauthStartDetail: '點下方按鈕開啟瀏覽器完成登入，授權成功後會自動重新整理這裡的狀態。',
    status: '連線狀態', statusHealthy: '正常', statusUntested: '未測試',
    modelsSummary: (enabled: number, total: number) => `已啟用 ${enabled} / ${total}`,
    filterModels: '搜尋模型', noModelsMatch: '找不到符合的模型',
    enableModelAria: (name: string) => `啟用模型 ${name}`,
    declareCapabilities: '設定參數', declareCapabilitiesAria: (name: string) => `設定模型參數：${name}`,
    modelUndescribed: '缺少該模型的參數資訊，請手動設定。',
    visionToken: '视觉', thinkingToken: '思考', contextToken: (value: string) => `${value} 上下文`,
    noModels: '暫無可選模型，請先更新模型目錄。',
    keySet: '已設定', statusLoading: '正在讀取狀態', credentialUnknown: '憑據狀態未知', keyMissing: '尚未設定金鑰',
    keyTroubleshooting: '模型金鑰 / 服務地址 / 代理設定', endpointTroubleshooting: '本地服務 / 服務地址 / 代理設定', oauthTroubleshooting: 'OAuth 登入 / 代理設定',
    unknownDescription: (provider: string) => `該連線使用的 provider「${provider}」在目前版本未註冊。設定和憑據會保留，切回支援它的版本即可繼續使用。`,
    deleteProviderTitle: (name: string) => `刪除供應商 ${name}？`,
    deleteConnectionTitle: (name: string) => `刪除模型連線 ${name}？`,
    deleteUnknownDescription: '刪除後，支援該 provider 的其他版本也無法恢復這條連線及其憑據。',
    deleteDescription: (isDefault: boolean, disconnectsAccount: boolean) => [
      disconnectsAccount
        ? '這會退出本機帳號、刪除 OAuth 憑據和模型連線；重新整理後不會自動重建立立。'
        : '這會刪除模型連線及其本機憑據；如需再次使用，需要重新新增。',
      isDefault
        ? '它目前是預設連線；刪除後預設模型會變成未設定，已有任務可能需要重新選擇模型。'
        : '',
    ].filter(Boolean).join(' '),
    connectionSuccess: (name: string) => `連線成功 · ${name}`, connectionFailed: (name: string) => `連線失敗 · ${name}`,
    connectionFallbackTitle: (name: string) => `連線可用 · ${name}`,
    connectionFallbackDetail: (selected: readonly string[], tested: string) =>
      `你選擇的 ${selected.join('、')} 目前沒有回應，已改用 ${tested} 驗證連線可用；任務中繼續使用你選擇的模型可能會失敗。`,
    connectionTestError: (name: string) => `連線測試出錯 · ${name}`, modelsFetched: (count: number, name: string) => `已拉取 ${count} 個模型 · ${name}`,
    modelsFetchFailed: (name: string) => `拉取模型失敗 · ${name}`,
    modelsFetchFailedDetail: (message: string, troubleshooting: string) => `${message} · 目前繼續顯示靜態列表，請確認 ${troubleshooting} 後重試。`,
    authTroubleshooting: (value: string) => `鑑權失敗，請確認 ${value} 後重試。`, recheckTroubleshooting: (value: string) => `檢查 ${value} 後重試。`,
    modelKeyAria: (name: string) => `${name} 模型金鑰`,
  },
  shared: {
    actionFallback: '模型連線服務暫時不可用，請稍後重試。', rateLimit: '目前帳號或模型服務觸發速率限制，請稍後重試。',
    timeout: '請求超時，請檢查網路或代理後重試。', unavailable: '模型服務暫時不可用，請稍後重試。',
    network: '網路錯誤，請檢查服務地址或代理設定後重試。', statusUnavailable: '連線測試狀態暫時無法顯示，請重新測試。',
    filterMatches: (count: number) => (count === 0 ? '沒有符合的結果' : `${count} 個符合結果`),
    connectionStatuses: { retired: '已停用 · 請刪除', reauth: '需要重新登入', disabledFailed: '暫不可用 · 上次連線失敗', disabled: '暫不可用', failed: '上次連線失敗' },
    lastTest: {
      '连接已验证': '連線已驗證', '鉴权失败': '鑑權失敗', '请求超时': '請求超時', '网络错误': '網路錯誤', '模型服务返回错误': '模型服務回傳錯誤', '连接测试失败': '連線測試失敗',
      'connection verified': '連線已驗證', 'authentication failed': '鑑權失敗', 'request timed out': '請求超時', 'network error': '網路錯誤', 'provider returned an error': '模型服務回傳錯誤', 'connection test failed': '連線測試失敗',
      'claude oauth 未登录。': 'Claude OAuth 未登入。', 'claude oauth 本地凭据读取失败。': 'Claude OAuth 本地憑據讀取失敗。', 'claude oauth 需要重新登录。': 'Claude OAuth 需要重新登入。', 'claude oauth 已登录。': 'Claude OAuth 已登入。', 'claude oauth 已退出登录。': 'Claude OAuth 已退出登入。',
      'codex oauth 未登录。': 'Codex OAuth 未登入。', 'codex oauth 本地凭据读取失败。': 'Codex OAuth 本地憑據讀取失敗。', 'codex oauth 需要重新登录。': 'Codex OAuth 需要重新登入。', 'codex oauth 已登录。': 'Codex OAuth 已登入。', 'codex oauth 已退出登录。': 'Codex OAuth 已退出登入。',
      '当前账号无可用 codex 模型。': '目前帳號無可用 Codex 模型。', 'codex 模型列表获取失败。': 'Codex 模型列表取得失敗。',
      'github copilot 需要重新导入 github cli 登录。': 'GitHub Copilot 需要重新匯入 GitHub CLI 登入。', 'github copilot 无法读取当前账号可用模型，请重新验证登录。': 'GitHub Copilot 無法讀取目前帳號可用模型，請重新驗證登入。', 'github copilot 登录已导入。': 'GitHub Copilot 登入已匯入。', 'github copilot 连接未能保存，请重新导入登录。': 'GitHub Copilot 連線未能儲存，請重新匯入登入。', 'github copilot 已移除本地登录。': 'GitHub Copilot 已移除本地登入。',
    },
  },
  panel: {
    groups: { recommended: '推薦', plans: '訂閱計劃', api: 'API', aggregators: '聚合服務', local: '本地' },
    loadFailed: '載入模型連線失敗', loadingAria: '正在載入模型供應商', connections: '模型連線',
    connectionsHelp: '已啟用的模型會顯示在任務的模型選擇器中。',
    retry: '點選重試。', empty: '還沒有模型連線', connectionRemoved: '原連線已刪除或移除，已返回模型連線列表。',
    connectedLoading: '帳號已連線，正在載入新的模型連線…', connectedLoadFailed: '帳號已連線，但暫時無法載入新的模型連線。',
    connectionIdentityChanged: '新連線的身分與登入結果不一致，請返回連線列表後重試。',
    emptyHelp: '從下方的常用服務商開始，或瀏覽全部服務商。', recommended: '推薦服務商', browseAll: '查看全部服務商',
    default: '預設', setDefault: '設為預設', setDefaultTitle: '讓新任務預設使用這個連線', setDefaultPending: '設定中…', setDefaultFailed: '設為預設失敗', addHelp: '選擇帳號登入、模型計劃、API、聚合服務或本地執行時。',
    searchPlaceholder: '搜尋服務商', searchAria: '搜尋模型服務商', noMatch: '沒有符合的服務商', clearSearch: '清除搜尋',
    createSubtitle: '完成必要設定後，連線會出現在模型頁上方。', connection: '模型連線',
    count: (value: number) => `· ${value}`, modelCount: (value: number) => `${value} 個模型`, connectTitle: (name: string) => `連線 ${name}`,
    chipAria: (name: string, provider: string, isDefault: boolean, status?: string) => `模型連線：${name}，供應商：${provider}${isDefault ? '，預設連線' : ''}${status ? `，${status}` : ''}`,
    addConnection: '新增連線', backToList: '返回模型連線', backToCatalog: '返回服務商列表',
  },
  catalog: {
    unavailable: '未開放',
    cardAria: (name: string, description: string) => `新增模型供應商：${name}，${description}`,
  },
  add: {
    invalidSlug: '連線標識格式不正確', duplicateSlug: '連線標識已存在', cloudflareAccount: '請填寫 Cloudflare Account ID', endpointRequired: '這個供應商需要填寫服務地址',
    accountLogin: '請到帳號連線完成登入；登入成功後會自動建立模型連線。',
    apiKeyPlaceholder: '輸入或貼上 API Key', cancel: '取消', accountTitle: '使用帳號連線登入',
    advancedRequest: '高階請求設定', expandAdvancedRequest: '展開高階請求設定', collapseAdvancedRequest: '收起高階請求設定',
    requestHeaders: '自訂請求頭', headerName: '請求頭名稱', headerValue: '請求頭值', retainedHeaderValue: '保留已儲存的值', addHeader: '新增請求頭', removeHeader: '移除', noRequestHeaders: '未設定自訂請求頭。',
    extraRequestBody: '額外請求體（JSON）', extraRequestBodyHelp: '僅新增頂層欄位；與 Maka 生成欄位重名時會明確失敗。請求頭值將作為憑據儲存在本機。', requestCustomizationInvalid: '請檢查高階請求設定。',
    accountDetail: '不要在這裡手動新增；請回到模型連線頁的帳號連線完成登入，Maka 會自動建立並重新整理模型連線。',
    slug: '連線標識', name: '顯示名稱',
    accountIdPlaceholder: '填寫帳號 ID',
    saving: '儲存中…', save: '儲存供應商', keyRequired: (name: string) => `請填寫 ${name} API Key`,
    apiKeyLabel: 'API Key', accountIdLabel: 'Cloudflare Account ID', endpointLabel: '服務地址',
    defaultModel: '預設模型', defaultModelPlaceholder: '留空即可，儲存後自動拉取', defaultModelHelp: '儲存後 Maka 會向該端點拉取模型目錄。只有當端點不提供目錄時，才需要在這裡手填一個模型 ID。',
    stepsAria: '新增連線步驟', stepCredentials: '金鑰', stepModels: '選擇模型',
    onboardingVerifyAndChoose: '驗證並選擇模型', onboardingVerifying: '正在驗證金鑰並取得模型…',
    onboardingChooseModels: '選擇此連線使用的模型', onboardingChooseModelsHelp: '新增後仍可在連線詳細資料中啟用其他模型。', onboardingEnabledModels: '啟用的模型', onboardingSearchModels: '搜尋模型', onboardingAddConnection: '新增連線', onboardingBack: '返回修改',
    onboardingSelectedCount: (selected: number, total: number) => `已選 ${selected} / ${total}`, onboardingSelectAll: '全選', onboardingClearAll: '取消全選', onboardingNoModelsMatch: '找不到符合的模型',
    onboardingDefaultModel: '預設模型', onboardingDefaultModelHelp: '新任務將預設使用此模型，僅可在已勾選的模型中選擇。',
    onboardingAuthFailed: '金鑰驗證失敗，請檢查後重試。', onboardingTimeout: '驗證逾時，請檢查網路或 Proxy 後重試。', onboardingNetwork: '無法連線至模型服務，請檢查網路、Proxy 或服務位址。', onboardingUnavailable: '模型連線服務暫時無法使用，請稍後重試。', onboardingInvalidResponse: '模型服務回傳無法辨識的結果，請稍後重試。', onboardingCatalogFull: '連線數量已達上限，請先刪除不再使用的連線。', onboardingModelsChanged: '可用模型已變更，請重新驗證後選擇。', onboardingNoModels: '未發現可用模型，目前未建立連線。', onboardingSelectModel: '請至少啟用一個模型。',
    onboardingOutcomeUnknown: '暫時無法確認儲存結果', onboardingOutcomeUnknownDetail: '請勿再次新增，以免建立重複連線。重新載入連線列表並檢查該連線是否已出現；仍不確定時請先重新連線 Runtime Host。', onboardingReloadConnections: '重新載入連線列表', onboardingRestart: '仍要新增另一個連線',
    ...zhTwCapabilitiesCopy,
  },
  oauthFlow: {
    refreshFailed: '重新整理登入狀態失敗', accountActionFailed: (name: string) => `${name} 帳號操作失敗`, loginFailedRetry: '登入失敗，請稍後重試。',
    retry: '請稍後再試。', startFailed: '無法開始登入', startFailedRetry: '無法開始登入，請稍後再試。', openFailed: '無法開啟瀏覽器',
    openFailedRetry: '無法開啟瀏覽器，請稍後重試。', loginSuccess: '登入成功', bound: (name: string) => `${name} 已繫結本機。`,
    incomplete: '登入未完成', incompleteRetry: '登入未完成，請重新開啟瀏覽器授權。', loginFailed: '登入失敗',
    logoutDescription: '將刪除本機儲存的訂閱憑據，之後需要重新登入才能繼續使用這些 OAuth 模型。', logout: '退出登入', cancel: '取消',
    loggedOut: '已退出登入', credentialsCleared: '本地憑據已清除。', logoutFailed: '退出失敗', logoutFailedRetry: '退出登入失敗，請稍後重試。',
    serviceUnavailable: '登入服務暫時不可用，請檢查網路後重試。',
    logoutTitle: (name: string) => `退出 ${name} 登入？`,
  },
  oauthSection: {
    signedIn: '已登入', codexDescription: 'ChatGPT Plus / Pro 訂閱帳號登入。', xaiDescription: 'SuperGrok / X Premium 帳號登入。',
    configuredConnections: (count: number) => `已有 ${count} 個連線 · 新增另一個帳號`,
    copilotDescription: '匯入相容 GitHub 憑據連線 Copilot 訂閱。', serviceUnavailable: '登入服務暫時不可用，請檢查網路後重試。',
    aria: 'OAuth 登入',
    staleState: 'OAuth 登入狀態暫時沒重新整理成功，已保留上一次狀態。',
    codexDetail: '點選下方按鈕開啟裝置授權頁，並在頁面中輸入這裡顯示的登入碼。', xaiDetail: '點選下方按鈕開啟瀏覽器登入，授權完成後會自動回寫。', deviceCode: '登入碼：',
    openingBrowser: '開啟瀏覽器…', waitingAuthorization: '等待瀏覽器授權…', logout: '退出登入', loggingOut: '退出中…',
    copilotSubtitle: '匯入相容的 GitHub 登入；token 不會暴露給渲染程序。', copilotImported: '已匯入 GitHub Copilot 訂閱帳號。',
    copilotSetup: '請設定具有 Copilot Requests 權限的 fine-grained PAT；普通 gh auth login 可能不包含該權限。', importing: '匯入中…',
    copilotSignIn: '使用 GitHub 登入', copilotActionFailed: 'GitHub Copilot 帳號操作失敗',
    copilotSignInDisabledHint: '本機未啟用 GitHub 登入；請改用匯入相容憑據，或由管理員啟用後重試。',
    importCredential: '匯入相容憑據',
    loadingAccount: '正在載入帳號狀態…', authorizing: '請在彈出的瀏覽器視窗完成登入。', refreshing: '正在重新整理存取權杖…', refreshTokenFailed: '權杖重新整理失敗，請重新登入。',
    cardAria: (intent: 'add' | 'import' | 'manage', name: string, status: string | undefined, description: string) => `${intent === 'add' ? '新增' : intent === 'import' ? '匯入' : '管理'}帳號連線：${name}${status ? `，狀態：${status}` : ''}，${description.replace(/[。.!！？?]+$/u, '')}`,
    connectTitle: (name: string) => `連線 ${name}`, addAccountTitle: (name: string) => `新增 ${name} 帳號`, login: (name: string) => `登入 ${name}`, loginAndAdd: '登入並新增', signedOut: (name: string) => `${name} 尚未登入。`,
    storageFailed: (name: string) => `${name} 本地憑據讀取失敗，請重新登入。`, providerUnavailable: (name: string) => `${name} 已登入，但目前 provider 狀態不可用。`,
  },
} as const;
const enCopy: ProviderSettingsCopy = {
  detail: {
    delete: 'Delete', cancel: 'Cancel', deleteUnused: 'Delete unused connection',
    deleteFailed: 'Failed to delete model connection', credentialReadFailed: 'Failed to read model credential status', refreshFailed: 'Failed to refresh model connection',
    saveFailed: 'Failed to save model connection', saveModelsFailed: 'Failed to save enabled models',
    modelKey: 'Model key', pasteModelKey: 'Paste model key', getModelKey: 'Get model key', saving: 'Saving…',
    advancedRequest: 'Advanced request settings', advancedRequestHelp: 'Add HTTP headers and extra JSON request-body fields for this connection. Header values stay in the local credential vault.',
    requestHeaders: 'Custom request headers', headerName: 'Header name', headerValue: 'Header value', retainedHeaderValue: 'Keep saved value', addHeader: 'Add header', removeHeader: 'Remove', noRequestHeaders: 'No custom request headers.',
    extraRequestBody: 'Extra request body (JSON)', extraRequestBodyHelp: 'Adds top-level fields only. A collision with a Maka-generated field fails explicitly.', requestCustomizationInvalid: 'Invalid request settings', requestHeadersInvalidDetail: 'Check the request header names and values.', requestBodyInvalidDetail: 'Enter a valid JSON object that meets the requirements.', saveAdvancedRequest: 'Save advanced request settings', configuredHeaders: (count: number) => `${count} ${count === 1 ? 'header' : 'headers'}`, noAdvancedRequest: 'Not configured',
    oauthLoggedIn: 'OAuth signed in', oauthLoading: 'Reading OAuth status', oauthUnknown: 'OAuth status unavailable', oauthWaiting: 'Waiting for OAuth sign-in',
    oauthLoggedInDetail: 'This model connection uses an OAuth access token stored by the main process. If a request asks you to sign in again, reauthorize it under account connections.',
    oauthLoadingDetail: 'Reading the local OAuth status. An unknown state will not be shown as signed out.',
    oauthUnknownDetail: 'The local OAuth status is temporarily unavailable. Refresh the page or reopen Settings.',
    oauthWaitingDetail: 'Complete sign-in under account connections. The model connection appears automatically afterward.',
    oauthRetired: 'This sign-in path is retired',
    oauthRetiredDetail:
      'The sign-in this connection uses was removed from Maka. It can no longer be signed into or used in a conversation. Add an Anthropic API key connection to keep using Claude models; deleting this connection also clears the sign-in credential stored on this machine.',
    credentialLoadingDetail: 'Reading model credential status. Connection tests and model refresh are paused until it finishes.',
    credentialUnknownDetail: 'Model credential status could not be refreshed, so the connection is not being mislabeled as signed out or unconfigured.',
    testConnection: 'Test connection',
    updateModels: 'Update model catalog', endpoint: 'Service URL',
    connectionName: 'Name',
    connectionNamePlaceholder: 'Name this connection',
    addModel: 'Add model',
    addModelConfirm: 'Add',
    addModelIdField: 'Model ID',
    addModelIdFieldHelp: 'Must match the provider exactly, including case.',
    addModelIdPlaceholder: 'deepseek-v4-pro-beta',
    addModelIdRequired: 'Enter a model ID.',
    addModelIdDuplicate: 'This model is already in the list.',
    addModelContextWindow: 'Context window',
    addModelContextWindowHelp:
      "The maximum token count from the provider's model page. Without it Maka can only assume 32k, and long conversations get truncated early.",
    addModelContextWindowRequired: 'Enter a context window.',
    credentials: 'Connection', dangerZone: 'Delete connection', deleteRowHelp: 'This cannot be undone.',
    credentialsHelp: 'The key stays on this machine.',
    credentialsHelpAccount: 'The sign-in token stays on this machine.',
    modelManagementHelp: 'These models appear in the chat model picker.',
    ...enCapabilitiesCopy,
    capabilitiesHelp: "Set this model's context length, vision support, and thinking levels; applies on save.",
    change: 'Change', set: 'Set', edit: 'Edit', save: 'Save',
    endpointManaged: 'Managed by account sign-in or the provider',
    endpointMissing: 'No service URL configured',
    endpointModelOverridesNote: 'Some models send requests through a different endpoint',
    endpointCredentialsMasked: 'The saved URL embeds credentials and stays masked while editing',
    modelManagement: 'Models',
    disconnectAndDelete: 'Sign out and delete',
    login: 'Sign in', loggingIn: 'Signing in…', relogin: 'Sign in again',
    oauthReloginDetail: 'If a request asks you to sign in again, restart authorization here.', deviceCode: 'Sign-in code:',
    oauthStartDetail: 'Open the browser below to sign in. This status refreshes automatically after authorization.',
    status: 'Connection status', statusHealthy: 'Healthy', statusUntested: 'Not tested',
    modelsSummary: (enabled: number, total: number) => `${enabled} of ${total} enabled`,
    filterModels: 'Search models', noModelsMatch: 'No matching models',
    enableModelAria: (name: string) => `Enable model ${name}`,
    declareCapabilities: 'Set parameters', declareCapabilitiesAria: (name: string) => `Set model parameters: ${name}`,
    modelUndescribed: 'No parameters known for this model. Set them by hand.',
    visionToken: 'Vision', thinkingToken: 'Thinking', contextToken: (value: string) => `${value} context`,
    noModels: 'No models are available. Update the model catalog first.',
    keySet: 'Set', statusLoading: 'Reading status', credentialUnknown: 'Credential status unavailable', keyMissing: 'No key set',
    keyTroubleshooting: 'model key, service URL, and proxy settings', endpointTroubleshooting: 'local service, service URL, and proxy settings', oauthTroubleshooting: 'OAuth sign-in and proxy settings',
    unknownDescription: (provider: string) => `The provider “${provider}” used by this connection is not registered in the current version. Its configuration and credentials are preserved for a supported version.`,
    deleteProviderTitle: (name: string) => `Delete provider ${name}?`,
    deleteConnectionTitle: (name: string) => `Delete model connection ${name}?`,
    deleteUnknownDescription: 'After deletion, another version that supports this provider cannot restore the connection or its credentials.',
    deleteDescription: (isDefault: boolean, disconnectsAccount: boolean) => [
      disconnectsAccount
        ? 'This signs out the local account and deletes its OAuth credential and model connection. It will not be recreated on refresh.'
        : 'This deletes the model connection and its local credential. Add it again to use it later.',
      isDefault
        ? 'It is currently the default connection; the default model becomes unset and existing chats may need another model selected.'
        : '',
    ].filter(Boolean).join(' '),
    connectionSuccess: (name: string) => `Connected · ${name}`, connectionFailed: (name: string) => `Connection failed · ${name}`,
    connectionFallbackTitle: (name: string) => `Connection works · ${name}`,
    connectionFallbackDetail: (selected: readonly string[], tested: string) =>
      `Your selected ${selected.join(', ')} didn't respond; verified the connection with ${tested} instead. Tasks using your selected model may fail.`,
    connectionTestError: (name: string) => `Connection test error · ${name}`, modelsFetched: (count: number, name: string) => `Fetched ${count} ${count === 1 ? 'model' : 'models'} · ${name}`,
    modelsFetchFailed: (name: string) => `Failed to fetch models · ${name}`,
    modelsFetchFailedDetail: (message: string, troubleshooting: string) => `${message} · The static list remains visible. Check ${troubleshooting} and try again.`,
    authTroubleshooting: (value: string) => `Authentication failed. Check ${value} and try again.`, recheckTroubleshooting: (value: string) => `Check ${value} and try again.`,
    modelKeyAria: (name: string) => `${name} model key`,
  },
  shared: {
    actionFallback: 'The model connection service is temporarily unavailable. Try again later.', rateLimit: 'This account or model service is rate-limited. Try again later.',
    timeout: 'The request timed out. Check the network or proxy and try again.', unavailable: 'The model service is temporarily unavailable. Try again later.',
    network: 'Network error. Check the service URL or proxy settings and try again.', statusUnavailable: 'The connection test status is temporarily unavailable. Test again.',
    filterMatches: (count: number) => (count === 0 ? 'No matches' : count === 1 ? '1 match' : `${count} matches`),
    connectionStatuses: { retired: 'Retired · delete it', reauth: 'Sign-in required', disabledFailed: 'Unavailable · last connection failed', disabled: 'Unavailable', failed: 'Last connection failed' },
    lastTest: {
      '连接已验证': 'Connection verified', '鉴权失败': 'Authentication failed', '请求超时': 'Request timed out', '网络错误': 'Network error', '模型服务返回错误': 'Model service returned an error', '连接测试失败': 'Connection test failed',
      'connection verified': 'Connection verified', 'authentication failed': 'Authentication failed', 'request timed out': 'Request timed out', 'network error': 'Network error', 'provider returned an error': 'Model service returned an error', 'connection test failed': 'Connection test failed',
      'claude oauth 未登录。': 'Claude OAuth is signed out.', 'claude oauth 本地凭据读取失败。': 'Could not read local Claude OAuth credentials.', 'claude oauth 需要重新登录。': 'Claude OAuth requires sign-in.', 'claude oauth 已登录。': 'Claude OAuth is signed in.', 'claude oauth 已退出登录。': 'Claude OAuth signed out.',
      'codex oauth 未登录。': 'Codex OAuth is signed out.', 'codex oauth 本地凭据读取失败。': 'Could not read local Codex OAuth credentials.', 'codex oauth 需要重新登录。': 'Codex OAuth requires sign-in.', 'codex oauth 已登录。': 'Codex OAuth is signed in.', 'codex oauth 已退出登录。': 'Codex OAuth signed out.',
      '当前账号无可用 codex 模型。': 'No Codex models are available for this account.', 'codex 模型列表获取失败。': 'Failed to fetch the Codex model list.',
      'github copilot 需要重新导入 github cli 登录。': 'GitHub Copilot requires the GitHub CLI sign-in to be imported again.', 'github copilot 无法读取当前账号可用模型，请重新验证登录。': 'GitHub Copilot could not read models available to this account. Verify sign-in again.', 'github copilot 登录已导入。': 'GitHub Copilot sign-in imported.', 'github copilot 连接未能保存，请重新导入登录。': 'The GitHub Copilot connection could not be saved. Import sign-in again.', 'github copilot 已移除本地登录。': 'Local GitHub Copilot sign-in removed.',
    },
  },
  panel: {
    groups: { recommended: 'Recommended', plans: 'Subscription plans', api: 'API', aggregators: 'Aggregators', local: 'Local' },
    loadFailed: 'Failed to load model connections', loadingAria: 'Loading model providers', connections: 'Connections',
    connectionsHelp: 'These connections and their enabled models appear in the chat model picker.',
    retry: 'Select to retry.', empty: 'No model connections yet', connectionRemoved: 'The original connection was deleted or removed. Returned to the connection list.',
    connectedLoading: 'Connection added. Loading its details…', connectedLoadFailed: 'Connection added, but the connection list could not be refreshed yet.',
    connectionIdentityChanged: 'The new connection identity did not match the sign-in result. Return to the connection list and try again.',
    emptyHelp: 'Start with a common provider below, or browse them all.', recommended: 'Recommended providers', browseAll: 'Browse all providers',
    default: 'Default', setDefault: 'Set as default', setDefaultTitle: 'New chats will use this connection', setDefaultPending: 'Setting…', setDefaultFailed: 'Could not set as default', addHelp: 'Choose account sign-in, a model plan, API, aggregator, or local runtime.',
    searchPlaceholder: 'Search providers', searchAria: 'Search model providers', noMatch: 'No matching providers', clearSearch: 'Clear search',
    createSubtitle: 'After required setup, the connection appears above on the Models page.', connection: 'Model connection',
    count: (value: number) => `· ${value}`, modelCount: (value: number) => `${value} ${value === 1 ? 'model' : 'models'}`, connectTitle: (name: string) => `Connect ${name}`,
    chipAria: (name: string, provider: string, isDefault: boolean, status?: string) => `Model connection: ${name}; provider: ${provider}${isDefault ? '; default connection' : ''}${status ? `; ${status}` : ''}`,
    addConnection: 'Add connection', backToList: 'Back to model connections', backToCatalog: 'Back to the provider list',
  },
  catalog: {
    unavailable: 'Unavailable',
    cardAria: (name: string, description: string) => `Add model provider: ${name}; ${description}`,
  },
  add: {
    invalidSlug: 'The connection identifier format is invalid', duplicateSlug: 'Connection identifier already exists', cloudflareAccount: 'Enter the Cloudflare Account ID', endpointRequired: 'This provider requires a service URL',
    accountLogin: 'Complete sign-in under account connections. A model connection is created automatically afterward.',
    apiKeyPlaceholder: 'Enter or paste API key', cancel: 'Cancel', accountTitle: 'Sign in with an account connection',
    advancedRequest: 'Advanced request settings', expandAdvancedRequest: 'Show advanced request settings', collapseAdvancedRequest: 'Hide advanced request settings',
    requestHeaders: 'Custom request headers', headerName: 'Header name', headerValue: 'Header value', retainedHeaderValue: 'Keep saved value', addHeader: 'Add header', removeHeader: 'Remove', noRequestHeaders: 'No custom request headers.',
    extraRequestBody: 'Extra request body (JSON)', extraRequestBodyHelp: 'Adds top-level fields only. A collision with a Maka-generated field fails explicitly. Header values stay in the local credential vault.', requestCustomizationInvalid: 'Check the advanced request settings.',
    accountDetail: 'Do not add this provider manually here. Return to account connections and sign in; Maka creates and refreshes the model connection automatically.',
    slug: 'Connection identifier', name: 'Display name',
    accountIdPlaceholder: 'Enter account ID',
    saving: 'Saving…', save: 'Save provider', keyRequired: (name: string) => `Enter the ${name} API key`,
    apiKeyLabel: 'API key', accountIdLabel: 'Cloudflare Account ID', endpointLabel: 'Service URL',
    defaultModel: 'Default model', defaultModelPlaceholder: 'Leave empty — fetched after saving', defaultModelHelp: 'Maka fetches the model catalog from this endpoint after saving. Type a model id here only if the endpoint serves no catalog.',
    stepsAria: 'Steps to add the connection', stepCredentials: 'Key', stepModels: 'Choose models',
    onboardingVerifyAndChoose: 'Verify and choose models', onboardingVerifying: 'Verifying the key and loading models…',
    onboardingChooseModels: 'Choose models for this connection', onboardingChooseModelsHelp: 'You can enable more models from the connection details later.', onboardingEnabledModels: 'Enabled models', onboardingSearchModels: 'Search models', onboardingAddConnection: 'Add connection', onboardingBack: 'Back to edit',
    onboardingSelectedCount: (selected: number, total: number) => `${selected} of ${total} selected`, onboardingSelectAll: 'Select all', onboardingClearAll: 'Deselect all', onboardingNoModelsMatch: 'No matching models',
    onboardingDefaultModel: 'Default model', onboardingDefaultModelHelp: 'New chats start on this model. Only selected models can be chosen.',
    onboardingAuthFailed: 'The key could not be verified. Check it and try again.', onboardingTimeout: 'Verification timed out. Check the network or proxy and try again.', onboardingNetwork: 'Could not reach the model provider. Check the network, proxy, or service URL.', onboardingUnavailable: 'The model connection service is unavailable. Try again later.', onboardingInvalidResponse: 'The model provider returned an unrecognized response. Try again later.', onboardingCatalogFull: 'The connection limit has been reached. Remove an unused connection first.', onboardingModelsChanged: 'The available models changed. Verify again and make a new selection.', onboardingNoModels: 'No usable models were found. No connection was created.', onboardingSelectModel: 'Enable at least one model.',
    onboardingOutcomeUnknown: 'The save result cannot be confirmed', onboardingOutcomeUnknownDetail: 'Do not add it again yet, because that could create a duplicate connection. Reload the connection list and check whether this connection appeared; reconnect the Runtime Host if the result is still unclear.', onboardingReloadConnections: 'Reload connection list', onboardingRestart: 'Add another connection anyway',
    ...enCapabilitiesCopy,
  },
  oauthFlow: {
    refreshFailed: 'Failed to refresh sign-in status', accountActionFailed: (name: string) => `${name} account action failed`, loginFailedRetry: 'Sign-in failed. Try again later.',
    retry: 'Try again later.', startFailed: 'Could not start sign-in', startFailedRetry: 'Could not start sign-in. Try again later.', openFailed: 'Could not open browser',
    openFailedRetry: 'Could not open the browser. Try again.', loginSuccess: 'Signed in', bound: (name: string) => `${name} is connected to this device.`,
    incomplete: 'Sign-in incomplete', incompleteRetry: 'Sign-in did not finish. Reopen the browser authorization and try again.', loginFailed: 'Sign-in failed',
    logoutDescription: 'This removes the locally stored subscription credentials. You must sign in again to use these OAuth models.', logout: 'Sign out', cancel: 'Cancel',
    loggedOut: 'Signed out', credentialsCleared: 'Local credentials cleared.', logoutFailed: 'Sign-out failed', logoutFailedRetry: 'Sign-out failed. Try again later.',
    serviceUnavailable: 'The sign-in service is temporarily unavailable. Check the network and try again.',
    logoutTitle: (name: string) => `Sign out of ${name}?`,
  },
  oauthSection: {
    signedIn: 'Signed in', codexDescription: 'Use a ChatGPT Plus / Pro account to add a connection.', xaiDescription: 'Use a SuperGrok or X Premium account to add a connection.',
    configuredConnections: (count: number) => `${count} ${count === 1 ? 'connection' : 'connections'} configured · Add another account`,
    copilotDescription: 'Sign in with GitHub to connect a Copilot subscription, or import compatible credentials.', serviceUnavailable: 'The sign-in service is temporarily unavailable. Check the network and try again.',
    aria: 'OAuth sign-in',
    staleState: 'OAuth sign-in status could not be refreshed. The last known state is preserved. ',
    codexDetail: 'Open the device page below and enter the sign-in code shown here.', xaiDetail: 'Open the browser below to sign in. Authorization is written back automatically.', deviceCode: 'Sign-in code:',
    openingBrowser: 'Opening browser…', waitingAuthorization: 'Waiting for browser authorization…', logout: 'Sign out', loggingOut: 'Signing out…',
    copilotSubtitle: 'Sign in with GitHub, or import compatible credentials. The token is never exposed to the renderer.', copilotImported: 'GitHub Copilot subscription account imported.',
    copilotSetup: 'Sign in with GitHub to connect Copilot, or import an existing gh credential.', importing: 'Importing…',
    copilotSignIn: 'Sign in with GitHub', copilotActionFailed: 'GitHub Copilot account action failed',
    copilotSignInDisabledHint: 'GitHub sign-in is not enabled on this install. Import a compatible credential instead, or ask an operator to enable it.',
    importCredential: 'Import compatible credentials',
    loadingAccount: 'Loading account status…', authorizing: 'Complete sign-in in the browser window.', refreshing: 'Refreshing access token…', refreshTokenFailed: 'Token refresh failed. Sign in again.',
    cardAria: (intent: 'add' | 'import' | 'manage', name: string, status: string | undefined, description: string) => `${intent === 'add' ? 'Add' : intent === 'import' ? 'Import' : 'Manage'} account connection: ${name}${status ? `; status: ${status}` : ''}; ${description.replace(/[。.!！？?]+$/u, '')}`,
    connectTitle: (name: string) => `Connect ${name}`, addAccountTitle: (name: string) => `Add ${name} account`, login: (name: string) => `Sign in to ${name}`, loginAndAdd: 'Sign in and add', signedOut: (name: string) => `${name} is signed out.`,
    storageFailed: (name: string) => `Could not read local credentials for ${name}. Sign in again.`, providerUnavailable: (name: string) => `${name} is signed in, but the provider status is currently unavailable.`,
  },
};

const koOverrides = {
    detail: {
      delete: "삭제",
      cancel: "취소",
      deleteUnused: "사용하지 않는 연결 삭제",
      deleteFailed: "모델 연결을 삭제하지 못했습니다.",
      credentialReadFailed: "모델 자격 증명 상태를 읽지 못했습니다.",
      refreshFailed: "모델 연결을 새로 고치지 못했습니다.",
      saveFailed: "모델 연결을 저장하지 못했습니다.",
      saveModelsFailed: "활성화된 모델을 저장하지 못했습니다.",
      modelKey: "모델 키",
      pasteModelKey: "모델 키 붙여넣기",
      getModelKey: "모델 키 가져오기",
      saving: "절약…",
      advancedRequest: "고급 요청 설정",
      advancedRequestHelp: "이 연결에 대해 HTTP 헤더와 추가 JSON 요청 본문 필드를 추가하세요. 헤더 값은 로컬 자격 증명 저장소에 유지됩니다.",
      requestHeaders: "사용자 정의 요청 헤더",
      headerName: "헤더 이름",
      headerValue: "헤더 값",
      retainedHeaderValue: "저장된 값 유지",
      addHeader: "헤더 추가",
      removeHeader: "제거하다",
      noRequestHeaders: "사용자 정의 요청 헤더가 없습니다.",
      extraRequestBody: "추가 요청 본문(JSON)",
      extraRequestBodyHelp: "최상위 필드만 추가합니다. Maka 생성 필드와의 충돌은 명시적으로 실패합니다.",
      requestCustomizationInvalid: "잘못된 요청 설정",
      requestHeadersInvalidDetail: "요청 헤더 이름과 값을 확인하세요.",
      requestBodyInvalidDetail: "요구 사항을 충족하는 유효한 JSON 개체를 입력하세요.",
      saveAdvancedRequest: "고급 요청 설정 저장",
      configuredHeaders: (count: number) => `${count}개 헤더`,
      noAdvancedRequest: "구성되지 않음",
      oauthLoggedIn: "OAuth에 로그인됨",
      oauthLoading: "OAuth 상태 읽기",
      oauthUnknown: "OAuth 상태를 사용할 수 없습니다.",
      oauthWaiting: "OAuth 로그인을 기다리는 중",
      oauthLoggedInDetail: "이 모델 연결은 기본 프로세스에 저장된 OAuth 액세스 토큰을 사용합니다. 요청에서 다시 로그인하라는 메시지가 표시되면 계정 연결에서 다시 인증하세요.",
      oauthLoadingDetail: "로컬 OAuth 상태를 읽습니다. 알 수 없는 상태는 로그아웃된 것으로 표시되지 않습니다.",
      oauthUnknownDetail: "로컬 OAuth 상태를 일시적으로 사용할 수 없습니다. 페이지를 새로 고치거나 설정을 다시 엽니다.",
      oauthWaitingDetail: "계정 연결에서 로그인을 완료하세요. 나중에 모델 연결이 자동으로 나타납니다.",
      oauthRetired: "이 로그인 경로는 더 이상 사용되지 않습니다.",
      oauthRetiredDetail: "이 연결에서 사용하는 로그인이 Maka에서 삭제되었습니다. 더 이상 로그인하거나 대화에서 사용할 수 없습니다. Claude 모델을 계속 사용하려면 Anthropic API 키 연결을 추가하세요. 이 연결을 삭제하면 이 컴퓨터에 저장된 로그인 자격 증명도 지워집니다.",
      credentialLoadingDetail: "모델 자격 증명 상태를 읽는 중입니다. 연결 테스트 및 모델 새로 고침은 완료될 때까지 일시 중지됩니다.",
      credentialUnknownDetail: "모델 자격 증명 상태를 새로 고칠 수 없으므로 연결이 로그아웃되었거나 구성되지 않은 것으로 잘못 표시되지 않습니다.",
      testConnection: "테스트 연결",
      updateModels: "모델 카탈로그 업데이트",
      endpoint: "서비스 URL",
      connectionName: "이름",
      connectionNamePlaceholder: "이 연결의 이름을 지정하세요.",
      addModel: "모델 추가",
      addModelConfirm: "추가하다",
      addModelIdField: "모델 ID",
      addModelIdFieldHelp: "대소문자를 포함하여 공급자와 정확히 일치해야 합니다.",
      addModelIdPlaceholder: 'deepseek-v4-pro-beta',
      addModelIdRequired: "모델 ID를 입력하세요.",
      addModelIdDuplicate: "이 모델은 이미 목록에 있습니다.",
      addModelContextWindow: "컨텍스트 창",
      addModelContextWindowHelp: "공급자 모델 페이지의 최대 토큰 수입니다. 그것이 없으면 Maka는 32k만 가정할 수 있으며 긴 대화는 일찍 잘립니다.",
      addModelContextWindowRequired: "컨텍스트 창을 입력합니다.",
      credentials: "연결",
      dangerZone: "연결 삭제",
      deleteRowHelp: "이 작업은 취소할 수 없습니다.",
      credentialsHelp: "열쇠는 이 기계에 남아있습니다.",
      credentialsHelpAccount: "로그인 토큰은 이 컴퓨터에 유지됩니다.",
      modelManagementHelp: "이러한 모델은 채팅 모델 선택기에 표시됩니다.",
      capabilities: "기능",
      thinkingEffort: "사고 수준(reasoning_effort)",
      thinkingEffortHelp: "이 모델이 지원하는 사고 수준을 선택하세요. 체크 표시가 없으면 선언되지 않았음을 의미합니다.",
      thinkingUndeclared: "선언되지 않음",
      thinkingSelectedCount: (count: number) => `${count} 선택됨`,
      thinkingBulk: "모든 모델의 사고 수준 설정",
      thinkingBulkHelp: "선택하면 아래의 활성화된 모든 모델에 레벨이 추가됩니다. 선택을 취소하면 모든 항목에서 해당 항목이 제거됩니다. 다른 레벨은 그대로 둡니다.",
      thinkingBulkTrigger: "모든 모델에 적용",
      thinkingBulkCoverage: (declared: number, total: number) => declared === 0 ? "모델 없음" : `${declared} 모델의 ${total}에서`,
      visionInput: "비전 입력",
      visionInputHelp: "자동은 내장된 메타데이터를 따릅니다. 활성화/비활성화는 이를 명시적으로 재정의합니다.",
      visionAuto: "자동",
      visionEnabledOption: "활성화됨",
      visionDisabledOption: "장애가 있는",
      contextWindow: "컨텍스트 창(토큰)",
      contextWindowHelp: "설정되면 압축 및 예산이 이 값을 사용합니다. 비어 있으면 내장된 메타데이터가 결정합니다.",
      contextWindowHint: (tokens: number) => `이 모델은 ${tokens}-토큰 창을 선언합니다`,
      contextWindowApplyHint: "사용",
      saveCapabilities: "기능 선언 저장",
      fastMode: "빠른 모드",
      fastModeHelp: "OpenAI의 빠른 서비스 계층을 사용하세요. 비어 있음은 공급자 기본값을 따릅니다.",
      fastAuto: "자동",
      fastEnabled: "빠른",
      capabilitiesHelp: "활성화된 모델별로 사고 수준, 비전 및 컨텍스트 창을 선언합니다. 저장 시 적용됩니다.",
      change: "변화",
      set: "세트",
      edit: "편집하다",
      save: "구하다",
      endpointManaged: "계정 로그인 또는 공급자가 관리함",
      endpointMissing: "서비스 URL이 구성되지 않았습니다.",
      endpointModelOverridesNote: "일부 모델은 다른 엔드포인트를 통해 요청을 보냅니다.",
      endpointCredentialsMasked: "저장된 URL은 자격 증명을 포함하고 편집하는 동안 마스크된 상태로 유지됩니다.",
      modelManagement: "모델",
      disconnectAndDelete: "로그아웃 및 삭제",
      copilotImportFailed: "GitHub Copilot 로그인을 가져오지 못했습니다.",
      copilotLoggedIn: "GitHub Copilot에 로그인됨",
      copilotWaiting: "호환되는 GitHub 자격 증명을 기다리는 중",
      copilotLoggedInDetail: "계정 또는 조직 정책이 변경되면 호환되는 자격 증명을 다시 가져옵니다.",
      copilotWaitingDetail: "Copilot 요청 권한으로 자격 증명을 구성한 다음 이 장치에서 안전하게 가져옵니다.",
      reimport: "다시 가져오기",
      importCredential: "호환되는 자격 증명 가져오기",
      login: "로그인",
      loggingIn: "로그인 중…",
      relogin: "다시 로그인",
      oauthReloginDetail: "다시 로그인하라는 요청이 있으면 여기에서 승인을 다시 시작하세요.",
      oauthStartDetail: "아래 브라우저를 열어 로그인하세요. 이 상태는 승인 후 자동으로 새로고침됩니다.",
      enabledModels: "활성화된 모델",
      searchModels: "모델 검색",
      selectAllModels: "모두 활성화",
      noModels: "사용할 수 있는 모델이 없습니다. 먼저 모델 카탈로그를 업데이트하세요.",
      keySet: "세트",
      statusLoading: "읽기 상태",
      credentialUnknown: "자격 증명 상태를 알 수 없음",
      keyMissing: "키가 설정되지 않았습니다.",
      keyTroubleshooting: "모델 키, 서비스 URL 및 프록시 설정",
      endpointTroubleshooting: "로컬 서비스, 서비스 URL 및 프록시 설정",
      oauthTroubleshooting: "OAuth 로그인 및 프록시 설정",
      unknownDescription: (provider: string) => `이 연결에 사용된 공급자 "${provider}"은 현재 버전에 등록되어 있지 않습니다. 해당 구성 및 자격 증명은 지원되는 버전에 대해 보존됩니다.`,
      deleteProviderTitle: (name: string) => `공급자 ${name}을 삭제하시겠습니까?`,
      deleteConnectionTitle: (name: string) => `모델 연결 ${name}을 삭제하시겠습니까?`,
      deleteUnknownDescription: "삭제 후에는 이 공급자를 지원하는 다른 버전에서 연결이나 해당 자격 증명을 복원할 수 없습니다.",
      deleteDescription: (isDefault: boolean, disconnectsAccount: boolean) => [disconnectsAccount ? "그러면 로컬 계정이 로그아웃되고 OAuth 자격 증명 및 모델 연결이 삭제됩니다. 새로 고침 시 다시 생성되지 않습니다." : "그러면 모델 연결과 해당 로컬 자격 증명이 삭제됩니다. 나중에 다시 사용하려면 다시 추가하세요.", isDefault ? "현재는 기본 연결입니다. 기본 모델이 설정 해제되고 기존 채팅에 다른 모델을 선택해야 할 수도 있습니다." : ''].filter(Boolean).join(' '),
      connectionSuccess: (name: string) => `연결됨 · ${name}`,
      connectionFailed: (name: string) => `연결 실패 · ${name}`,
      connectionFallbackTitle: (name: string) => `연결이 작동합니다 · ${name}`,
      connectionFallbackDetail: (selected: readonly string[], tested: string) => `선택한 ${selected.join(', ')}이 응답하지 않았습니다. 대신 ${tested}과의 연결을 확인했습니다. 선택한 모델을 사용하는 작업이 실패할 수 있습니다.`,
      connectionTestError: (name: string) => `연결 테스트 오류 · ${name}`,
      modelsFetched: (count: number, name: string) => `${count}개 모델 가져옴 · ${name}`,
      modelsFetchFailed: (name: string) => `모델을 가져오지 못했습니다. · ${name}`,
      modelsFetchFailedDetail: (message: string, troubleshooting: string) => `${message} · 정적 목록은 계속 표시됩니다. ${troubleshooting}을 확인하고 다시 시도하세요.`,
      authTroubleshooting: (value: string) => `인증에 실패했습니다. ${value}을(를) 확인한 후 다시 시도하세요.`,
      recheckTroubleshooting: (value: string) => `${value}을(를) 확인한 후 다시 시도하세요.`,
      modelKeyAria: (name: string) => `${name} 모델 키`
    },
    shared: {
      actionFallback: '모델 연결 서비스를 일시적으로 사용할 수 없습니다. 나중에 다시 시도하세요.',
      rateLimit: '이 계정 또는 모델 서비스가 속도 제한에 도달했습니다. 나중에 다시 시도하세요.',
      timeout: '요청 시간이 초과되었습니다. 네트워크 또는 프록시를 확인한 후 다시 시도하세요.',
      unavailable: '모델 서비스를 일시적으로 사용할 수 없습니다. 나중에 다시 시도하세요.',
      network: '네트워크 오류입니다. 서비스 URL 또는 프록시 설정을 확인한 후 다시 시도하세요.',
      statusUnavailable: '연결 테스트 상태를 일시적으로 사용할 수 없습니다. 다시 테스트하세요.',
      categories: {
        oauth: 'OAuth', domestic: '중국', overseas: '글로벌', local: '로컬', custom: '사용자 지정'
      },
      connectionStatuses: {
        retired: '사용 중지됨 · 삭제하세요', reauth: '다시 로그인해야 함',
        disabledFailed: '사용 불가 · 최근 연결 실패', disabled: '사용 불가', failed: '최근 연결 실패'
      },
      lastTest: {
        '连接已验证': '연결 확인됨',
        '鉴权失败': '인증 실패',
        '请求超时': '요청 시간 초과',
        '网络错误': "네트워크 오류",
        '模型服务返回错误': '모델 서비스에서 오류를 반환함',
        '连接测试失败': '연결 테스트 실패',
        'connection verified': '연결 확인됨',
        'authentication failed': '인증 실패',
        'request timed out': '요청 시간 초과',
        'network error': "네트워크 오류",
        'provider returned an error': '모델 서비스에서 오류를 반환함',
        'connection test failed': '연결 테스트 실패',
        'claude oauth 未登录。': 'Claude OAuth가 로그아웃되었습니다.',
        'claude oauth 本地凭据读取失败。': '로컬 Claude OAuth 자격 증명을 읽지 못했습니다.',
        'claude oauth 需要重新登录。': 'Claude OAuth에 다시 로그인해야 합니다.',
        'claude oauth 已登录。': 'Claude OAuth에 로그인되어 있습니다.',
        'claude oauth 已退出登录。': 'Claude OAuth에서 로그아웃되었습니다.',
        'codex oauth 未登录。': 'Codex OAuth가 로그아웃되었습니다.',
        'codex oauth 本地凭据读取失败。': '로컬 Codex OAuth 자격 증명을 읽지 못했습니다.',
        'codex oauth 需要重新登录。': 'Codex OAuth에 다시 로그인해야 합니다.',
        'codex oauth 已登录。': 'Codex OAuth에 로그인되어 있습니다.',
        'codex oauth 已退出登录。': 'Codex OAuth에서 로그아웃되었습니다.',
        '当前账号无可用 codex 模型。': '이 계정에서 사용할 수 있는 Codex 모델이 없습니다.',
        'codex 模型列表获取失败。': 'Codex 모델 목록을 가져오지 못했습니다.',
        'github copilot 需要重新导入 github cli 登录。': 'GitHub CLI 로그인을 다시 가져와야 합니다.',
        'github copilot 无法读取当前账号可用模型，请重新验证登录。': '현재 계정에서 사용 가능한 모델을 읽지 못했습니다. 다시 로그인하세요.',
        'github copilot 登录已导入。': 'GitHub Copilot 로그인을 가져왔습니다.',
        'github copilot 连接未能保存，请重新导入登录。': 'GitHub Copilot 연결을 저장하지 못했습니다. 로그인을 다시 가져오세요.',
        'github copilot 已移除本地登录。': '로컬 GitHub Copilot 로그인이 제거되었습니다.'
      }
    },
    panel: {
      tabs: {
        all: "모두",
        recommended: '추천',
        accounts: '계정',
        plans: '모델 플랜',
        api: 'API',
        aggregators: '애그리게이터',
        local: '로컬'
      },
      loadFailed: '모델 연결을 로드하지 못했습니다',
      loadingAria: '모델 공급자 로드 중',
      connections: '연결',
      retry: '선택하여 다시 시도하세요.',
      empty: '아직 모델 연결이 없습니다',
      connectionRemoved: '원래 연결이 삭제되거나 제거되었습니다. 연결 목록으로 돌아갑니다.',
      connectedLoading: '연결이 추가되었습니다. 세부 정보 로드 중…',
      connectedLoadFailed: '연결은 추가되었지만 연결 목록을 아직 새로 고칠 수 없습니다.',
      connectionIdentityChanged: '새 연결 정보가 로그인 결과와 일치하지 않습니다. 연결 목록으로 돌아가 다시 시도하세요.',
      emptyHelp: '아래에서 연결 방법을 선택하여 시작하세요.',
      default: "기본",
      setDefault: "기본값으로 설정",
      setDefaultTitle: '새 채팅에서 이 연결을 사용합니다',
      setDefaultPending: '설정 중…',
      setDefaultFailed: '기본값으로 설정하지 못했습니다',
      addHelp: '계정 로그인, 모델 플랜, API, 애그리게이터 또는 로컬 런타임을 선택하세요.',
      categoriesAria: '모델 공급자 카테고리',
      searchPlaceholder: '공급자 검색',
      searchAria: '모델 공급자 검색',
      noMatch: '일치하는 공급자가 없습니다',
      clearSearch: "검색 지우기",
      createSubtitle: '필수 설정을 완료하면 모델 페이지 위에 연결이 표시됩니다.',
      connection: "모델 연결",
      count: (value: number) => `· ${value}`,
      connectTitle: (name: string) => `${name} 연결`,
      chipAria: (name: string, provider: string, isDefault: boolean, status?: string) => `모델 연결: ${name}; 공급자: ${provider}${isDefault ? '; 기본 연결' : ''}${status ? `; ${status}` : ''}`,
      addConnection: '연결 추가',
      category: '카테고리',
      backToList: '모델 연결로 돌아가기',
      backToCatalog: '공급자 목록으로 돌아가기'
    },
    catalog: {
      unavailable: '사용 불가',
      cardAria: (name: string, description: string) => `모델 공급자 추가: ${name}; ${description}`
    },
    add: {
      invalidSlug: '연결 식별자 형식이 잘못되었습니다',
      duplicateSlug: '연결 식별자가 이미 존재합니다',
      cloudflareAccount: 'Cloudflare 계정 ID를 입력하세요',
      endpointRequired: '이 공급자에는 서비스 URL이 필요합니다',
      accountLogin: '계정 연결에서 로그인을 완료하세요. 이후 모델 연결이 자동으로 생성됩니다.',
      apiKeyPlaceholder: 'API 키를 입력하거나 붙여넣으세요',
      cancel: "취소",
      accountTitle: '계정 연결로 로그인',
      advancedRequest: "고급 요청 설정",
      expandAdvancedRequest: '고급 요청 설정 표시',
      collapseAdvancedRequest: '고급 요청 설정 숨기기',
      requestHeaders: "사용자 정의 요청 헤더",
      headerName: "헤더 이름",
      headerValue: "헤더 값",
      retainedHeaderValue: "저장된 값 유지",
      addHeader: "헤더 추가",
      removeHeader: "제거하다",
      noRequestHeaders: "사용자 정의 요청 헤더가 없습니다.",
      extraRequestBody: "추가 요청 본문(JSON)",
      extraRequestBodyHelp: '최상위 필드만 추가합니다. Maka 생성 필드와 충돌하면 명시적으로 실패합니다. 헤더 값은 로컬 자격 증명 저장소에 보관됩니다.',
      requestCustomizationInvalid: '고급 요청 설정을 확인하세요.',
      accountDetail: '여기에서 이 공급자를 수동으로 추가하지 마세요. 계정 연결로 돌아가 로그인하면 Maka가 모델 연결을 자동으로 생성하고 새로 고칩니다.',
      slug: '연결 식별자',
      name: "표시 이름",
      accountIdPlaceholder: '계정 ID 입력',
      saving: "절약…",
      save: '공급자 저장',
      keyRequired: (name: string) => `${name} API 키를 입력하세요`,
      apiKeyLabel: 'API 키',
      accountIdLabel: 'Cloudflare 계정 ID',
      endpointLabel: "서비스 URL",
      defaultModel: '기본 모델',
      defaultModelPlaceholder: '비워 두면 저장 후 가져옵니다',
      defaultModelHelp: '저장 후 Maka가 이 엔드포인트에서 모델 카탈로그를 가져옵니다. 엔드포인트에 카탈로그가 없을 때만 여기에 모델 ID를 입력하세요.',
      onboardingVerifyAndChoose: '모델 확인 및 선택',
      onboardingVerifying: '키 확인 및 모델 로드 중…',
      onboardingChooseModels: '이 연결에 사용할 모델 선택',
      onboardingChooseModelsHelp: '나중에 연결 세부 정보에서 더 많은 모델을 활성화할 수 있습니다.',
      onboardingEnabledModels: "활성화된 모델",
      onboardingSearchModels: "모델 검색",
      onboardingAddConnection: '연결 추가',
      onboardingBack: '편집으로 돌아가기',
      onboardingAuthFailed: '키를 확인하지 못했습니다. 확인 후 다시 시도하세요.',
      onboardingTimeout: '확인 시간이 초과되었습니다. 네트워크 또는 프록시를 확인한 후 다시 시도하세요.',
      onboardingNetwork: '모델 공급자에 연결할 수 없습니다. 네트워크, 프록시 또는 서비스 URL을 확인하세요.',
      onboardingUnavailable: '모델 연결 서비스를 사용할 수 없습니다. 나중에 다시 시도하세요.',
      onboardingInvalidResponse: '모델 공급자가 인식할 수 없는 응답을 반환했습니다. 나중에 다시 시도하세요.',
      onboardingCatalogFull: '연결 한도에 도달했습니다. 먼저 사용하지 않는 연결을 삭제하세요.',
      onboardingModelsChanged: '사용 가능한 모델이 변경되었습니다. 다시 확인하고 새로 선택하세요.',
      onboardingNoModels: '사용할 수 있는 모델을 찾지 못했습니다. 연결을 만들지 않았습니다.',
      onboardingSelectModel: '모델을 하나 이상 활성화하세요.',
      onboardingOutcomeUnknown: '저장 결과를 확인할 수 없습니다',
      onboardingOutcomeUnknownDetail: '중복 연결이 생성될 수 있으므로 아직 다시 추가하지 마세요. 연결 목록을 새로 고쳐 이 연결이 표시되는지 확인하고, 결과가 여전히 불분명하면 Runtime Host를 다시 연결하세요.',
      onboardingReloadConnections: '연결 목록 새로 고침',
      onboardingRestart: '그래도 다른 연결 추가',
      capabilities: "기능",
      thinkingEffort: "사고 수준(reasoning_effort)",
      thinkingEffortHelp: "이 모델이 지원하는 사고 수준을 선택하세요. 체크 표시가 없으면 선언되지 않았음을 의미합니다.",
      thinkingUndeclared: "선언되지 않음",
      thinkingSelectedCount: (count: number) => `${count} 선택됨`,
      thinkingBulk: "모든 모델의 사고 수준 설정",
      thinkingBulkHelp: "선택하면 아래의 활성화된 모든 모델에 레벨이 추가됩니다. 선택을 취소하면 모든 항목에서 해당 항목이 제거됩니다. 다른 레벨은 그대로 둡니다.",
      thinkingBulkTrigger: "모든 모델에 적용",
      thinkingBulkCoverage: (declared: number, total: number) => declared === 0 ? "모델 없음" : `${declared} 모델의 ${total}에서`,
      visionInput: "비전 입력",
      visionInputHelp: "자동은 내장된 메타데이터를 따릅니다. 활성화/비활성화는 이를 명시적으로 재정의합니다.",
      visionAuto: "자동",
      visionEnabledOption: "활성화됨",
      visionDisabledOption: "장애가 있는",
      contextWindow: "컨텍스트 창(토큰)",
      contextWindowHelp: "설정되면 압축 및 예산이 이 값을 사용합니다. 비어 있으면 내장된 메타데이터가 결정합니다.",
      contextWindowHint: (tokens: number) => `이 모델은 ${tokens}-토큰 창을 선언합니다`,
      contextWindowApplyHint: "사용",
      saveCapabilities: "기능 선언 저장",
      fastMode: "빠른 모드",
      fastModeHelp: "OpenAI의 빠른 서비스 계층을 사용하세요. 비어 있음은 공급자 기본값을 따릅니다.",
      fastAuto: "자동",
      fastEnabled: "빠른"
    },
    oauthFlow: {
      refreshFailed: '로그인 상태를 새로 고치지 못했습니다',
      accountActionFailed: (name: string) => `${name} 계정 작업 실패`,
      loginFailedRetry: '로그인에 실패했습니다. 나중에 다시 시도하세요.',
      retry: "나중에 다시 시도하세요.",
      startFailed: '로그인을 시작하지 못했습니다',
      startFailedRetry: '로그인을 시작하지 못했습니다. 나중에 다시 시도하세요.',
      openFailed: '브라우저를 열지 못했습니다',
      openFailedRetry: '브라우저를 열지 못했습니다. 다시 시도하세요.',
      loginSuccess: '로그인됨',
      bound: (name: string) => `${name}이(가) 이 장치에 연결되었습니다.`,
      incomplete: '로그인 미완료',
      incompleteRetry: '로그인이 완료되지 않았습니다. 브라우저 인증을 다시 열고 시도하세요.',
      loginFailed: '로그인 실패',
      logoutDescription: '로컬에 저장된 구독 자격 증명을 제거합니다. 이 OAuth 모델을 사용하려면 다시 로그인해야 합니다.',
      logout: '로그아웃',
      cancel: "취소",
      loggedOut: '로그아웃됨',
      credentialsCleared: '로컬 자격 증명이 삭제되었습니다.',
      logoutFailed: '로그아웃 실패',
      logoutFailedRetry: '로그아웃에 실패했습니다. 나중에 다시 시도하세요.',
      reverifyFailedRetry: '확인에 실패했습니다. 나중에 다시 시도하세요.',
      serviceUnavailable: '로그인 서비스를 일시적으로 사용할 수 없습니다. 네트워크를 확인한 후 다시 시도하세요.',
      logoutTitle: (name: string) => `${name}에서 로그아웃하시겠습니까?`
    },
    oauthSection: {
      signedIn: '로그인됨',
      codexDescription: 'ChatGPT Plus / Pro 계정을 사용하여 연결을 추가하세요.',
      xaiDescription: 'SuperGrok 또는 X Premium 계정을 사용하여 연결을 추가하세요.',
      configuredConnections: (count: number) => `${count}개 연결 구성됨 · 다른 계정 추가`,
      copilotDescription: 'GitHub에 로그인하여 Copilot 구독을 연결하거나 호환되는 자격 증명을 가져오세요.',
      serviceUnavailable: '로그인 서비스를 일시적으로 사용할 수 없습니다. 네트워크를 확인한 후 다시 시도하세요.',
      aria: 'OAuth 로그인',
      staleState: 'OAuth 로그인 상태를 새로 고치지 못했습니다. 마지막으로 알려진 상태를 유지합니다. ',
      codexDetail: '아래 장치 페이지를 열고 여기에 표시된 로그인 코드를 입력하세요.',
      xaiDetail: '아래 브라우저를 열어 로그인하세요. 인증 결과가 자동으로 반영됩니다.',
      deviceCode: '로그인 코드:',
      openingBrowser: '브라우저 여는 중…',
      waitingAuthorization: '브라우저 인증 대기 중…',
      logout: '로그아웃',
      loggingOut: '로그아웃 중…',
      copilotSubtitle: 'GitHub에 로그인하거나 호환되는 자격 증명을 가져옵니다. 토큰은 렌더러에 노출되지 않습니다.',
      copilotImported: 'GitHub Copilot 구독 계정을 가져왔습니다.',
      copilotSetup: 'GitHub에 로그인하여 Copilot을 연결하거나 기존 gh 자격 증명을 가져오세요.',
      importing: "가져오는 중…",
      copilotSignIn: 'GitHub로 로그인',
      copilotActionFailed: 'GitHub Copilot 계정 작업 실패',
      copilotSignInDisabledHint: '이 설치에서는 GitHub 로그인이 활성화되어 있지 않습니다. 대신 호환되는 자격 증명을 가져오거나 관리자에게 활성화를 요청하세요.',
      reimport: "다시 가져오기",
      importCredential: "호환되는 자격 증명 가져오기",
      verifying: '확인 중…',
      reverify: '다시 확인',
      removing: '제거 중…',
      removeLocal: '로컬 로그인 제거',
      loadingAccount: '계정 상태 로드 중…',
      authorizing: '브라우저 창에서 로그인을 완료하세요.',
      refreshing: '액세스 토큰 새로 고침 중…',
      refreshTokenFailed: '토큰을 새로 고치지 못했습니다. 다시 로그인하세요.',
      cardAria: (intent: 'add' | 'import' | 'manage', name: string, status: string | undefined, description: string) => `${intent === 'add' ? '계정 추가' : intent === 'import' ? '계정 가져오기' : '계정 관리'}: ${name}${status ? `; 상태: ${status}` : ''}; ${description.replace(/[。.!！？?]+$/u, '')}`,
      connectTitle: (name: string) => `${name} 연결`,
      addAccountTitle: (name: string) => `${name} 계정 추가`,
      login: (name: string) => `${name}에 로그인`,
      loginAndAdd: '로그인 후 추가',
      signedOut: (name: string) => `${name}에서 로그아웃되었습니다.`,
      storageFailed: (name: string) => `${name}의 로컬 자격 증명을 읽지 못했습니다. 다시 로그인하세요.`,
      providerUnavailable: (name: string) => `${name}에 로그인되어 있지만 공급자 상태를 현재 사용할 수 없습니다.`
    }
  };

const koCopy: ProviderSettingsCopy = {
  ...enCopy,
  detail: { ...enCopy.detail, ...koOverrides.detail },
  shared: { ...enCopy.shared, ...koOverrides.shared },
  panel: { ...enCopy.panel, ...koOverrides.panel },
  catalog: { ...enCopy.catalog, ...koOverrides.catalog },
  add: { ...enCopy.add, ...koOverrides.add },
  oauthFlow: { ...enCopy.oauthFlow, ...koOverrides.oauthFlow },
  oauthSection: { ...enCopy.oauthSection, ...koOverrides.oauthSection },
};

const PROVIDER_SETTINGS_COPY = {
  'zh-CN': zhCopy,
  'zh-TW': zhTwCopy,
  en: enCopy,
  ko: koCopy,
} satisfies UiCatalog<ProviderSettingsCopy>;

export function getProviderSettingsCopy(locale: UiLocale): ProviderSettingsCopy {
  return PROVIDER_SETTINGS_COPY[locale];
}
