// Generated from https://models.dev/api.json; refresh with scripts/sync-bedrock-model-metadata.mjs.
import type { PricingConfig } from '@maka/core/usage-stats/types';

export const BEDROCK_MODEL_PRICING: readonly PricingConfig[] = [
  {
    modelKey: 'amazon-bedrock:us.anthropic.claude-fable-5',
    inputUsdPer1M: 10,
    outputUsdPer1M: 50,
    cacheReadUsdPer1M: 1,
    cacheWriteUsdPer1M: 12.5,
  },
  {
    modelKey: 'amazon-bedrock:qwen.qwen3-coder-480b-a35b-v1:0',
    inputUsdPer1M: 0.22,
    outputUsdPer1M: 1.8,
  },
  {
    modelKey: 'amazon-bedrock:jp.anthropic.claude-sonnet-5',
    inputUsdPer1M: 2,
    outputUsdPer1M: 10,
    cacheReadUsdPer1M: 0.2,
    cacheWriteUsdPer1M: 2.5,
  },
  {
    modelKey: 'amazon-bedrock:jp.anthropic.claude-opus-4-7',
    inputUsdPer1M: 5,
    outputUsdPer1M: 25,
    cacheReadUsdPer1M: 0.5,
    cacheWriteUsdPer1M: 6.25,
  },
  {
    modelKey: 'amazon-bedrock:mistral.pixtral-large-2502-v1:0',
    inputUsdPer1M: 2,
    outputUsdPer1M: 6,
  },
  {
    modelKey: 'amazon-bedrock:jp.anthropic.claude-sonnet-4-5-20250929-v1:0',
    inputUsdPer1M: 3,
    outputUsdPer1M: 15,
    cacheReadUsdPer1M: 0.3,
    cacheWriteUsdPer1M: 3.75,
  },
  {
    modelKey: 'amazon-bedrock:au.anthropic.claude-sonnet-5',
    inputUsdPer1M: 2,
    outputUsdPer1M: 10,
    cacheReadUsdPer1M: 0.2,
    cacheWriteUsdPer1M: 2.5,
  },
  {
    modelKey: 'amazon-bedrock:global.anthropic.claude-sonnet-4-6',
    inputUsdPer1M: 3,
    outputUsdPer1M: 15,
    cacheReadUsdPer1M: 0.3,
    cacheWriteUsdPer1M: 3.75,
  },
  {
    modelKey: 'amazon-bedrock:qwen.qwen3-235b-a22b-2507-v1:0',
    inputUsdPer1M: 0.22,
    outputUsdPer1M: 0.88,
  },
  {
    modelKey: 'amazon-bedrock:au.anthropic.claude-sonnet-4-6',
    inputUsdPer1M: 3.3,
    outputUsdPer1M: 16.5,
    cacheReadUsdPer1M: 0.33,
    cacheWriteUsdPer1M: 4.125,
  },
  {
    modelKey: 'amazon-bedrock:jp.anthropic.claude-sonnet-4-6',
    inputUsdPer1M: 3,
    outputUsdPer1M: 15,
    cacheReadUsdPer1M: 0.3,
    cacheWriteUsdPer1M: 3.75,
  },
  {
    modelKey: 'amazon-bedrock:deepseek.v3.2',
    inputUsdPer1M: 0.62,
    outputUsdPer1M: 1.85,
  },
  {
    modelKey: 'amazon-bedrock:anthropic.claude-sonnet-4-5-20250929-v1:0',
    inputUsdPer1M: 3,
    outputUsdPer1M: 15,
    cacheReadUsdPer1M: 0.3,
    cacheWriteUsdPer1M: 3.75,
  },
  {
    modelKey: 'amazon-bedrock:mistral.ministral-3-3b-instruct',
    inputUsdPer1M: 0.1,
    outputUsdPer1M: 0.1,
  },
  {
    modelKey: 'amazon-bedrock:anthropic.claude-haiku-4-5-20251001-v1:0',
    inputUsdPer1M: 1,
    outputUsdPer1M: 5,
    cacheReadUsdPer1M: 0.1,
    cacheWriteUsdPer1M: 1.25,
  },
  {
    modelKey: 'amazon-bedrock:global.anthropic.claude-sonnet-5',
    inputUsdPer1M: 2,
    outputUsdPer1M: 10,
    cacheReadUsdPer1M: 0.2,
    cacheWriteUsdPer1M: 2.5,
  },
  {
    modelKey: 'amazon-bedrock:eu.anthropic.claude-opus-5',
    inputUsdPer1M: 5.5,
    outputUsdPer1M: 27.5,
    cacheReadUsdPer1M: 0.55,
    cacheWriteUsdPer1M: 6.875,
  },
  {
    modelKey: 'amazon-bedrock:mistral.mistral-large-3-675b-instruct',
    inputUsdPer1M: 0.5,
    outputUsdPer1M: 1.5,
  },
  {
    modelKey: 'amazon-bedrock:minimax.minimax-m2',
    inputUsdPer1M: 0.3,
    outputUsdPer1M: 1.2,
  },
  {
    modelKey: 'amazon-bedrock:us.deepseek.r1-v1:0',
    inputUsdPer1M: 1.35,
    outputUsdPer1M: 5.4,
  },
  {
    modelKey: 'amazon-bedrock:mistral.voxtral-small-24b-2507',
    inputUsdPer1M: 0.15,
    outputUsdPer1M: 0.35,
  },
  {
    modelKey: 'amazon-bedrock:qwen.qwen3-coder-next',
    inputUsdPer1M: 0.22,
    outputUsdPer1M: 1.8,
  },
  {
    modelKey: 'amazon-bedrock:openai.gpt-oss-safeguard-120b',
    inputUsdPer1M: 0.15,
    outputUsdPer1M: 0.6,
  },
  {
    modelKey: 'amazon-bedrock:us.anthropic.claude-opus-4-1-20250805-v1:0',
    inputUsdPer1M: 15,
    outputUsdPer1M: 75,
    cacheReadUsdPer1M: 1.5,
    cacheWriteUsdPer1M: 18.75,
  },
  {
    modelKey: 'amazon-bedrock:us.meta.llama4-maverick-17b-instruct-v1:0',
    inputUsdPer1M: 0.24,
    outputUsdPer1M: 0.97,
  },
  {
    modelKey: 'amazon-bedrock:eu.anthropic.claude-fable-5',
    inputUsdPer1M: 11,
    outputUsdPer1M: 55,
    cacheReadUsdPer1M: 1.1,
    cacheWriteUsdPer1M: 13.75,
  },
  {
    modelKey: 'amazon-bedrock:jp.anthropic.claude-haiku-4-5-20251001-v1:0',
    inputUsdPer1M: 1,
    outputUsdPer1M: 5,
    cacheReadUsdPer1M: 0.1,
    cacheWriteUsdPer1M: 1.25,
  },
  {
    modelKey: 'amazon-bedrock:au.anthropic.claude-opus-4-8',
    inputUsdPer1M: 5,
    outputUsdPer1M: 25,
    cacheReadUsdPer1M: 0.5,
    cacheWriteUsdPer1M: 6.25,
  },
  {
    modelKey: 'amazon-bedrock:global.anthropic.claude-sonnet-4-5-20250929-v1:0',
    inputUsdPer1M: 3,
    outputUsdPer1M: 15,
    cacheReadUsdPer1M: 0.3,
    cacheWriteUsdPer1M: 3.75,
  },
  {
    modelKey: 'amazon-bedrock:eu.anthropic.claude-haiku-4-5-20251001-v1:0',
    inputUsdPer1M: 1.1,
    outputUsdPer1M: 5.5,
    cacheReadUsdPer1M: 0.11,
    cacheWriteUsdPer1M: 1.375,
  },
  {
    modelKey: 'amazon-bedrock:moonshot.kimi-k2-thinking',
    inputUsdPer1M: 0.6,
    outputUsdPer1M: 2.5,
  },
  {
    modelKey: 'amazon-bedrock:au.anthropic.claude-sonnet-4-5-20250929-v1:0',
    inputUsdPer1M: 3,
    outputUsdPer1M: 15,
    cacheReadUsdPer1M: 0.3,
    cacheWriteUsdPer1M: 3.75,
  },
  {
    modelKey: 'amazon-bedrock:meta.llama4-maverick-17b-instruct-v1:0',
    inputUsdPer1M: 0.24,
    outputUsdPer1M: 0.97,
  },
  {
    modelKey: 'amazon-bedrock:us.anthropic.claude-opus-5',
    inputUsdPer1M: 5,
    outputUsdPer1M: 25,
    cacheReadUsdPer1M: 0.5,
    cacheWriteUsdPer1M: 6.25,
  },
  {
    modelKey: 'amazon-bedrock:amazon.nova-pro-v1:0',
    inputUsdPer1M: 0.8,
    outputUsdPer1M: 3.2,
    cacheReadUsdPer1M: 0.2,
  },
  {
    modelKey: 'amazon-bedrock:qwen.qwen3-vl-235b-a22b',
    inputUsdPer1M: 0.3,
    outputUsdPer1M: 1.5,
  },
  {
    modelKey: 'amazon-bedrock:openai.gpt-oss-120b',
    inputUsdPer1M: 0.15,
    outputUsdPer1M: 0.6,
  },
  {
    modelKey: 'amazon-bedrock:openai.gpt-5.5',
    inputUsdPer1M: 5.5,
    outputUsdPer1M: 33,
    cacheReadUsdPer1M: 0.55,
  },
  {
    modelKey: 'amazon-bedrock:minimax.minimax-m2.5',
    inputUsdPer1M: 0.3,
    outputUsdPer1M: 1.2,
  },
  {
    modelKey: 'amazon-bedrock:anthropic.claude-opus-4-6-v1',
    inputUsdPer1M: 5,
    outputUsdPer1M: 25,
    cacheReadUsdPer1M: 0.5,
    cacheWriteUsdPer1M: 6.25,
  },
  {
    modelKey: 'amazon-bedrock:us.meta.llama4-scout-17b-instruct-v1:0',
    inputUsdPer1M: 0.17,
    outputUsdPer1M: 0.66,
  },
  {
    modelKey: 'amazon-bedrock:writer.palmyra-x5-v1:0',
    inputUsdPer1M: 0.6,
    outputUsdPer1M: 6,
  },
  {
    modelKey: 'amazon-bedrock:writer.palmyra-x4-v1:0',
    inputUsdPer1M: 2.5,
    outputUsdPer1M: 10,
  },
  {
    modelKey: 'amazon-bedrock:anthropic.claude-fable-5',
    inputUsdPer1M: 10,
    outputUsdPer1M: 50,
    cacheReadUsdPer1M: 1,
    cacheWriteUsdPer1M: 12.5,
  },
  {
    modelKey: 'amazon-bedrock:deepseek.v3-v1:0',
    inputUsdPer1M: 0.58,
    outputUsdPer1M: 1.68,
  },
  {
    modelKey: 'amazon-bedrock:nvidia.nemotron-super-3-120b',
    inputUsdPer1M: 0.15,
    outputUsdPer1M: 0.65,
  },
  {
    modelKey: 'amazon-bedrock:us.anthropic.claude-opus-4-8',
    inputUsdPer1M: 5,
    outputUsdPer1M: 25,
    cacheReadUsdPer1M: 0.5,
    cacheWriteUsdPer1M: 6.25,
  },
  {
    modelKey: 'amazon-bedrock:xai.grok-4.6',
    inputUsdPer1M: 2.2,
    outputUsdPer1M: 6.6,
    cacheReadUsdPer1M: 0.55,
  },
  {
    modelKey: 'amazon-bedrock:anthropic.claude-sonnet-4-6',
    inputUsdPer1M: 3,
    outputUsdPer1M: 15,
    cacheReadUsdPer1M: 0.3,
    cacheWriteUsdPer1M: 3.75,
  },
  {
    modelKey: 'amazon-bedrock:anthropic.claude-sonnet-5',
    inputUsdPer1M: 2,
    outputUsdPer1M: 10,
    cacheReadUsdPer1M: 0.2,
    cacheWriteUsdPer1M: 2.5,
  },
  {
    modelKey: 'amazon-bedrock:global.anthropic.claude-fable-5',
    inputUsdPer1M: 10,
    outputUsdPer1M: 50,
    cacheReadUsdPer1M: 1,
    cacheWriteUsdPer1M: 12.5,
  },
  {
    modelKey: 'amazon-bedrock:global.anthropic.claude-opus-4-8',
    inputUsdPer1M: 5,
    outputUsdPer1M: 25,
    cacheReadUsdPer1M: 0.5,
    cacheWriteUsdPer1M: 6.25,
  },
  {
    modelKey: 'amazon-bedrock:eu.anthropic.claude-opus-4-5-20251101-v1:0',
    inputUsdPer1M: 5.5,
    outputUsdPer1M: 27.5,
    cacheReadUsdPer1M: 0.55,
    cacheWriteUsdPer1M: 6.875,
  },
  {
    modelKey: 'amazon-bedrock:google.gemma-3-27b-it',
    inputUsdPer1M: 0.12,
    outputUsdPer1M: 0.2,
  },
  {
    modelKey: 'amazon-bedrock:jp.anthropic.claude-opus-4-8',
    inputUsdPer1M: 5,
    outputUsdPer1M: 25,
    cacheReadUsdPer1M: 0.5,
    cacheWriteUsdPer1M: 6.25,
  },
  {
    modelKey: 'amazon-bedrock:mistral.magistral-small-2509',
    inputUsdPer1M: 0.5,
    outputUsdPer1M: 1.5,
  },
  {
    modelKey: 'amazon-bedrock:global.anthropic.claude-opus-4-7',
    inputUsdPer1M: 5,
    outputUsdPer1M: 25,
    cacheReadUsdPer1M: 0.5,
    cacheWriteUsdPer1M: 6.25,
  },
  {
    modelKey: 'amazon-bedrock:jp.anthropic.claude-opus-5',
    inputUsdPer1M: 5,
    outputUsdPer1M: 25,
    cacheReadUsdPer1M: 0.5,
    cacheWriteUsdPer1M: 6.25,
  },
  {
    modelKey: 'amazon-bedrock:global.anthropic.claude-haiku-4-5-20251001-v1:0',
    inputUsdPer1M: 1,
    outputUsdPer1M: 5,
    cacheReadUsdPer1M: 0.1,
    cacheWriteUsdPer1M: 1.25,
  },
  {
    modelKey: 'amazon-bedrock:au.anthropic.claude-opus-4-6-v1',
    inputUsdPer1M: 16.5,
    outputUsdPer1M: 82.5,
    cacheReadUsdPer1M: 1.65,
    cacheWriteUsdPer1M: 20.625,
  },
  {
    modelKey: 'amazon-bedrock:mistral.ministral-3-8b-instruct',
    inputUsdPer1M: 0.15,
    outputUsdPer1M: 0.15,
  },
  {
    modelKey: 'amazon-bedrock:us.anthropic.claude-haiku-4-5-20251001-v1:0',
    inputUsdPer1M: 1,
    outputUsdPer1M: 5,
    cacheReadUsdPer1M: 0.1,
    cacheWriteUsdPer1M: 1.25,
  },
  {
    modelKey: 'amazon-bedrock:amazon.nova-lite-v1:0',
    inputUsdPer1M: 0.06,
    outputUsdPer1M: 0.24,
    cacheReadUsdPer1M: 0.015,
  },
  {
    modelKey: 'amazon-bedrock:nvidia.nemotron-nano-12b-v2',
    inputUsdPer1M: 0.2,
    outputUsdPer1M: 0.6,
  },
  {
    modelKey: 'amazon-bedrock:deepseek.r1-v1:0',
    inputUsdPer1M: 1.35,
    outputUsdPer1M: 5.4,
  },
  {
    modelKey: 'amazon-bedrock:eu.anthropic.claude-sonnet-4-6',
    inputUsdPer1M: 3.3,
    outputUsdPer1M: 16.5,
    cacheReadUsdPer1M: 0.33,
    cacheWriteUsdPer1M: 4.125,
  },
  {
    modelKey: 'amazon-bedrock:minimax.minimax-m2.1',
    inputUsdPer1M: 0.3,
    outputUsdPer1M: 1.2,
  },
  {
    modelKey: 'amazon-bedrock:global.anthropic.claude-opus-4-5-20251101-v1:0',
    inputUsdPer1M: 5,
    outputUsdPer1M: 25,
    cacheReadUsdPer1M: 0.5,
    cacheWriteUsdPer1M: 6.25,
  },
  {
    modelKey: 'amazon-bedrock:mistral.devstral-2-123b',
    inputUsdPer1M: 0.4,
    outputUsdPer1M: 2,
  },
  {
    modelKey: 'amazon-bedrock:eu.anthropic.claude-sonnet-5',
    inputUsdPer1M: 2.2,
    outputUsdPer1M: 11,
    cacheReadUsdPer1M: 0.22,
    cacheWriteUsdPer1M: 2.75,
  },
  {
    modelKey: 'amazon-bedrock:us.anthropic.claude-sonnet-5',
    inputUsdPer1M: 2,
    outputUsdPer1M: 10,
    cacheReadUsdPer1M: 0.2,
    cacheWriteUsdPer1M: 2.5,
  },
  {
    modelKey: 'amazon-bedrock:openai.gpt-oss-safeguard-20b',
    inputUsdPer1M: 0.07,
    outputUsdPer1M: 0.2,
  },
  {
    modelKey: 'amazon-bedrock:anthropic.claude-opus-5',
    inputUsdPer1M: 5,
    outputUsdPer1M: 25,
    cacheReadUsdPer1M: 0.5,
    cacheWriteUsdPer1M: 6.25,
  },
  {
    modelKey: 'amazon-bedrock:qwen.qwen3-32b-v1:0',
    inputUsdPer1M: 0.15,
    outputUsdPer1M: 0.6,
  },
  {
    modelKey: 'amazon-bedrock:qwen.qwen3-coder-30b-a3b-v1:0',
    inputUsdPer1M: 0.15,
    outputUsdPer1M: 0.6,
  },
  {
    modelKey: 'amazon-bedrock:au.anthropic.claude-haiku-4-5-20251001-v1:0',
    inputUsdPer1M: 1,
    outputUsdPer1M: 5,
    cacheReadUsdPer1M: 0.1,
    cacheWriteUsdPer1M: 1.25,
  },
  {
    modelKey: 'amazon-bedrock:xai.grok-4.3',
    inputUsdPer1M: 1.25,
    outputUsdPer1M: 2.5,
    cacheReadUsdPer1M: 0.2,
  },
  {
    modelKey: 'amazon-bedrock:zai.glm-4.7',
    inputUsdPer1M: 0.6,
    outputUsdPer1M: 2.2,
  },
  {
    modelKey: 'amazon-bedrock:us.anthropic.claude-opus-4-7',
    inputUsdPer1M: 5,
    outputUsdPer1M: 25,
    cacheReadUsdPer1M: 0.5,
    cacheWriteUsdPer1M: 6.25,
  },
  {
    modelKey: 'amazon-bedrock:us.anthropic.claude-sonnet-4-6',
    inputUsdPer1M: 3,
    outputUsdPer1M: 15,
    cacheReadUsdPer1M: 0.3,
    cacheWriteUsdPer1M: 3.75,
  },
  {
    modelKey: 'amazon-bedrock:anthropic.claude-opus-4-7',
    inputUsdPer1M: 5,
    outputUsdPer1M: 25,
    cacheReadUsdPer1M: 0.5,
    cacheWriteUsdPer1M: 6.25,
  },
  {
    modelKey: 'amazon-bedrock:zai.glm-5',
    inputUsdPer1M: 1,
    outputUsdPer1M: 3.2,
  },
  {
    modelKey: 'amazon-bedrock:meta.llama3-3-70b-instruct-v1:0',
    inputUsdPer1M: 0.72,
    outputUsdPer1M: 0.72,
  },
  {
    modelKey: 'amazon-bedrock:mistral.voxtral-mini-3b-2507',
    inputUsdPer1M: 0.04,
    outputUsdPer1M: 0.04,
  },
  {
    modelKey: 'amazon-bedrock:google.gemma-3-4b-it',
    inputUsdPer1M: 0.04,
    outputUsdPer1M: 0.08,
  },
  {
    modelKey: 'amazon-bedrock:amazon.nova-2-lite-v1:0',
    inputUsdPer1M: 0.33,
    outputUsdPer1M: 2.75,
  },
  {
    modelKey: 'amazon-bedrock:google.gemma-3-12b-it',
    inputUsdPer1M: 0.049999999999999996,
    outputUsdPer1M: 0.09999999999999999,
  },
  {
    modelKey: 'amazon-bedrock:anthropic.claude-opus-4-1-20250805-v1:0',
    inputUsdPer1M: 15,
    outputUsdPer1M: 75,
    cacheReadUsdPer1M: 1.5,
    cacheWriteUsdPer1M: 18.75,
  },
  {
    modelKey: 'amazon-bedrock:amazon.nova-micro-v1:0',
    inputUsdPer1M: 0.035,
    outputUsdPer1M: 0.14,
    cacheReadUsdPer1M: 0.00875,
  },
  {
    modelKey: 'amazon-bedrock:openai.gpt-5.4',
    inputUsdPer1M: 2.75,
    outputUsdPer1M: 16.5,
    cacheReadUsdPer1M: 0.275,
  },
  {
    modelKey: 'amazon-bedrock:moonshotai.kimi-k2.5',
    inputUsdPer1M: 0.6,
    outputUsdPer1M: 3,
  },
  {
    modelKey: 'amazon-bedrock:anthropic.claude-opus-4-5-20251101-v1:0',
    inputUsdPer1M: 5,
    outputUsdPer1M: 25,
    cacheReadUsdPer1M: 0.5,
    cacheWriteUsdPer1M: 6.25,
  },
  {
    modelKey: 'amazon-bedrock:qwen.qwen3-next-80b-a3b',
    inputUsdPer1M: 0.14,
    outputUsdPer1M: 1.4,
  },
  {
    modelKey: 'amazon-bedrock:au.anthropic.claude-opus-5',
    inputUsdPer1M: 5,
    outputUsdPer1M: 25,
    cacheReadUsdPer1M: 0.5,
    cacheWriteUsdPer1M: 6.25,
  },
  {
    modelKey: 'amazon-bedrock:us.anthropic.claude-sonnet-4-5-20250929-v1:0',
    inputUsdPer1M: 3,
    outputUsdPer1M: 15,
    cacheReadUsdPer1M: 0.3,
    cacheWriteUsdPer1M: 3.75,
  },
  {
    modelKey: 'amazon-bedrock:openai.gpt-oss-20b-1:0',
    inputUsdPer1M: 0.07,
    outputUsdPer1M: 0.3,
  },
  {
    modelKey: 'amazon-bedrock:openai.gpt-oss-20b',
    inputUsdPer1M: 0.07,
    outputUsdPer1M: 0.3,
  },
  {
    modelKey: 'amazon-bedrock:global.anthropic.claude-opus-5',
    inputUsdPer1M: 5,
    outputUsdPer1M: 25,
    cacheReadUsdPer1M: 0.5,
    cacheWriteUsdPer1M: 6.25,
  },
  {
    modelKey: 'amazon-bedrock:meta.llama4-scout-17b-instruct-v1:0',
    inputUsdPer1M: 0.17,
    outputUsdPer1M: 0.66,
  },
  {
    modelKey: 'amazon-bedrock:zai.glm-4.7-flash',
    inputUsdPer1M: 0.07,
    outputUsdPer1M: 0.4,
  },
  {
    modelKey: 'amazon-bedrock:us.anthropic.claude-opus-4-5-20251101-v1:0',
    inputUsdPer1M: 5,
    outputUsdPer1M: 25,
    cacheReadUsdPer1M: 0.5,
    cacheWriteUsdPer1M: 6.25,
  },
  {
    modelKey: 'amazon-bedrock:us.anthropic.claude-opus-4-6-v1',
    inputUsdPer1M: 5,
    outputUsdPer1M: 25,
    cacheReadUsdPer1M: 0.5,
    cacheWriteUsdPer1M: 6.25,
  },
  {
    modelKey: 'amazon-bedrock:eu.anthropic.claude-opus-4-8',
    inputUsdPer1M: 5.5,
    outputUsdPer1M: 27.5,
    cacheReadUsdPer1M: 0.55,
    cacheWriteUsdPer1M: 6.875,
  },
  {
    modelKey: 'amazon-bedrock:nvidia.nemotron-nano-9b-v2',
    inputUsdPer1M: 0.06,
    outputUsdPer1M: 0.23,
  },
  {
    modelKey: 'amazon-bedrock:meta.llama3-1-8b-instruct-v1:0',
    inputUsdPer1M: 0.22,
    outputUsdPer1M: 0.22,
  },
  {
    modelKey: 'amazon-bedrock:nvidia.nemotron-nano-3-30b',
    inputUsdPer1M: 0.06,
    outputUsdPer1M: 0.24,
  },
  {
    modelKey: 'amazon-bedrock:eu.anthropic.claude-opus-4-7',
    inputUsdPer1M: 5.5,
    outputUsdPer1M: 27.5,
    cacheReadUsdPer1M: 0.55,
    cacheWriteUsdPer1M: 6.875,
  },
  {
    modelKey: 'amazon-bedrock:openai.gpt-oss-120b-1:0',
    inputUsdPer1M: 0.15,
    outputUsdPer1M: 0.6,
  },
  {
    modelKey: 'amazon-bedrock:eu.anthropic.claude-opus-4-6-v1',
    inputUsdPer1M: 5.5,
    outputUsdPer1M: 27.5,
    cacheReadUsdPer1M: 0.55,
    cacheWriteUsdPer1M: 6.875,
  },
  {
    modelKey: 'amazon-bedrock:meta.llama3-1-70b-instruct-v1:0',
    inputUsdPer1M: 0.72,
    outputUsdPer1M: 0.72,
  },
  {
    modelKey: 'amazon-bedrock:eu.anthropic.claude-sonnet-4-5-20250929-v1:0',
    inputUsdPer1M: 3.3,
    outputUsdPer1M: 16.5,
    cacheReadUsdPer1M: 0.33,
    cacheWriteUsdPer1M: 4.125,
  },
  {
    modelKey: 'amazon-bedrock:global.anthropic.claude-opus-4-6-v1',
    inputUsdPer1M: 5,
    outputUsdPer1M: 25,
    cacheReadUsdPer1M: 0.5,
    cacheWriteUsdPer1M: 6.25,
  },
  {
    modelKey: 'amazon-bedrock:anthropic.claude-opus-4-8',
    inputUsdPer1M: 5,
    outputUsdPer1M: 25,
    cacheReadUsdPer1M: 0.5,
    cacheWriteUsdPer1M: 6.25,
  },
  {
    modelKey: 'amazon-bedrock:mistral.ministral-3-14b-instruct',
    inputUsdPer1M: 0.2,
    outputUsdPer1M: 0.2,
  },
];
