// Generated from https://models.dev/api.json; refresh with scripts/sync-bedrock-model-metadata.mjs.
import type { ModelMetadata } from './model-metadata.js';

export const BEDROCK_MODEL_METADATA: Readonly<Record<string, ModelMetadata>> = {
  'us.anthropic.claude-fable-5': {
    displayName: 'Claude Fable 5 (US)',
    description: 'Claude model for creative writing, analysis, and controlled agent workflows',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    knowledgeCutoff: '2026-01-31',
    lastUpdated: '2026-06-09',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['low', 'medium', 'high', 'xhigh', 'max'],
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'qwen.qwen3-coder-480b-a35b-v1:0': {
    displayName: 'Qwen3 Coder 480B A35B Instruct',
    description: 'Qwen coding model for software agents, repository edits, and code reasoning',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 131072,
    maxOutputTokens: 65536,
    knowledgeCutoff: '2024-04',
    structuredOutput: true,
    lastUpdated: '2025-09-18',
    capabilities: {
      vision: false,
      reasoning: false,
      functionCalling: true,
    },
    modalities: {
      input: ['text'],
      output: ['text'],
    },
  },
  'jp.anthropic.claude-sonnet-5': {
    displayName: 'Claude Sonnet 5 (JP)',
    description: 'Everyday Claude agent model for coding, planning, browsing, and general work',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    knowledgeCutoff: '2026-01-31',
    structuredOutput: true,
    lastUpdated: '2026-06-30',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['low', 'medium', 'high', 'xhigh', 'max'],
      toggle: true,
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'jp.anthropic.claude-opus-4-7': {
    displayName: 'Claude Opus 4.7 (JP)',
    description: 'Stronger Opus tier for advanced software work and high-stakes reasoning',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    knowledgeCutoff: '2026-01-31',
    lastUpdated: '2026-04-16',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['low', 'medium', 'high', 'xhigh', 'max'],
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'mistral.pixtral-large-2502-v1:0': {
    displayName: 'Pixtral Large (25.02)',
    description: 'Mistral vision-language model for image understanding and multimodal chat',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 128000,
    maxOutputTokens: 8192,
    lastUpdated: '2025-04-08',
    capabilities: {
      vision: true,
      reasoning: false,
      functionCalling: true,
    },
    modalities: {
      input: ['text', 'image'],
      output: ['text'],
    },
  },
  'jp.anthropic.claude-sonnet-4-5-20250929-v1:0': {
    displayName: 'Claude Sonnet 4.5 (JP)',
    description: 'Balanced Claude model for coding, analysis, agent workflows, and cost control',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 200000,
    maxOutputTokens: 64000,
    knowledgeCutoff: '2025-07-31',
    structuredOutput: true,
    lastUpdated: '2025-09-29',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'au.anthropic.claude-sonnet-5': {
    displayName: 'Claude Sonnet 5 (AU)',
    description: 'Everyday Claude agent model for coding, planning, browsing, and general work',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    knowledgeCutoff: '2026-01-31',
    structuredOutput: true,
    lastUpdated: '2026-06-30',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['low', 'medium', 'high', 'xhigh', 'max'],
      toggle: true,
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'global.anthropic.claude-sonnet-4-6': {
    displayName: 'Claude Sonnet 4.6 (Global)',
    description:
      'Claude workhorse for coding agents, careful analysis, and production cost control',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 1000000,
    maxOutputTokens: 64000,
    knowledgeCutoff: '2025-08-31',
    structuredOutput: true,
    lastUpdated: '2026-03-13',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['low', 'medium', 'high', 'max'],
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'qwen.qwen3-235b-a22b-2507-v1:0': {
    displayName: 'Qwen3 235B A22B 2507',
    description: 'Qwen instruction model for multilingual chat, reasoning, and tool use',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 262144,
    maxOutputTokens: 131072,
    knowledgeCutoff: '2024-04',
    structuredOutput: true,
    lastUpdated: '2025-09-18',
    capabilities: {
      vision: false,
      reasoning: false,
      functionCalling: true,
    },
    modalities: {
      input: ['text'],
      output: ['text'],
    },
  },
  'au.anthropic.claude-sonnet-4-6': {
    displayName: 'AU Anthropic Claude Sonnet 4.6',
    description: 'Balanced Claude model for coding, analysis, agent workflows, and cost control',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    knowledgeCutoff: '2025-08',
    structuredOutput: true,
    lastUpdated: '2026-02-17',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['low', 'medium', 'high', 'max'],
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'global.openai.gpt-5.6-sol': {
    displayName: 'GPT-5.6 Sol (Global)',
    description:
      'Frontier GPT-5.6 model for complex professional work, coding, and agentic workflows',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 1050000,
    inputLimit: 922000,
    maxOutputTokens: 128000,
    knowledgeCutoff: '2026-02-16',
    structuredOutput: true,
    lastUpdated: '2026-07-09',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'jp.anthropic.claude-sonnet-4-6': {
    displayName: 'Claude Sonnet 4.6 (JP)',
    description:
      'Claude workhorse for coding agents, careful analysis, and production cost control',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 1000000,
    maxOutputTokens: 64000,
    knowledgeCutoff: '2025-08-31',
    structuredOutput: true,
    lastUpdated: '2026-03-13',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['low', 'medium', 'high', 'max'],
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'deepseek.v3.2': {
    displayName: 'DeepSeek-V3.2',
    description: 'DeepSeek chat model for instruction following, coding, and analysis',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 163840,
    maxOutputTokens: 81920,
    knowledgeCutoff: '2024-07',
    structuredOutput: true,
    lastUpdated: '2026-02-06',
    capabilities: {
      vision: false,
      reasoning: true,
      functionCalling: true,
    },
    modalities: {
      input: ['text'],
      output: ['text'],
    },
  },
  'anthropic.claude-sonnet-4-5-20250929-v1:0': {
    displayName: 'Claude Sonnet 4.5',
    description: 'Balanced Claude model for coding, analysis, agent workflows, and cost control',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 200000,
    maxOutputTokens: 64000,
    knowledgeCutoff: '2025-07-31',
    structuredOutput: true,
    lastUpdated: '2025-09-29',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'mistral.ministral-3-3b-instruct': {
    displayName: 'Ministral 3 3B',
    description: 'Compact Mistral model for edge, latency-sensitive, and cost-efficient workloads',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 256000,
    maxOutputTokens: 8192,
    structuredOutput: true,
    lastUpdated: '2025-12-02',
    capabilities: {
      vision: true,
      reasoning: false,
      functionCalling: true,
    },
    modalities: {
      input: ['text', 'image'],
      output: ['text'],
    },
  },
  'anthropic.claude-haiku-4-5-20251001-v1:0': {
    displayName: 'Claude Haiku 4.5',
    description:
      'Fast Claude model for responsive assistance, classification, and lightweight agents',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 200000,
    maxOutputTokens: 64000,
    knowledgeCutoff: '2025-02-28',
    structuredOutput: true,
    lastUpdated: '2025-10-15',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'global.anthropic.claude-sonnet-5': {
    displayName: 'Claude Sonnet 5 (Global)',
    description: 'Everyday Claude agent model for coding, planning, browsing, and general work',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    knowledgeCutoff: '2026-01-31',
    structuredOutput: true,
    lastUpdated: '2026-06-30',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['low', 'medium', 'high', 'xhigh', 'max'],
      toggle: true,
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'eu.anthropic.claude-opus-5': {
    displayName: 'Claude Opus 5 (EU)',
    description: 'Strongest Claude Opus model for coding, agents, and professional work',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    knowledgeCutoff: '2026-05',
    lastUpdated: '2026-07-24',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['low', 'medium', 'high', 'xhigh', 'max'],
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'mistral.mistral-large-3-675b-instruct': {
    displayName: 'Mistral Large 3',
    description: 'Flagship Mistral model for advanced reasoning, coding, and multilingual work',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 256000,
    maxOutputTokens: 8192,
    structuredOutput: true,
    lastUpdated: '2025-12-02',
    capabilities: {
      vision: true,
      reasoning: false,
      functionCalling: true,
    },
    modalities: {
      input: ['text', 'image'],
      output: ['text'],
    },
  },
  'openai.gpt-5.6-terra': {
    displayName: 'GPT-5.6 Terra',
    description: 'Balanced GPT-5.6 model for capable, cost-efficient everyday work',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 1050000,
    inputLimit: 922000,
    maxOutputTokens: 128000,
    knowledgeCutoff: '2026-02-16',
    structuredOutput: true,
    lastUpdated: '2026-07-09',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'minimax.minimax-m2': {
    displayName: 'MiniMax M2',
    description: 'MiniMax model for chat, coding, office work, and agentic tasks',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 204608,
    maxOutputTokens: 128000,
    structuredOutput: false,
    lastUpdated: '2025-10-27',
    capabilities: {
      vision: false,
      reasoning: true,
      functionCalling: true,
    },
    modalities: {
      input: ['text'],
      output: ['text'],
    },
  },
  'us.deepseek.r1-v1:0': {
    displayName: 'DeepSeek-R1 (US)',
    description:
      'Classic open reasoning model for transparent math, coding, and deliberate problem solving',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 128000,
    maxOutputTokens: 32768,
    knowledgeCutoff: '2024-07',
    lastUpdated: '2025-05-29',
    capabilities: {
      vision: false,
      reasoning: true,
      functionCalling: true,
    },
    modalities: {
      input: ['text'],
      output: ['text'],
    },
  },
  'mistral.voxtral-small-24b-2507': {
    displayName: 'Voxtral Small 24B 2507',
    description: 'Efficient Mistral model for fast chat, extraction, and production assistants',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 32000,
    maxOutputTokens: 8192,
    structuredOutput: true,
    lastUpdated: '2025-07-01',
    capabilities: {
      vision: false,
      reasoning: false,
      functionCalling: true,
    },
    modalities: {
      input: ['text', 'audio'],
      output: ['text'],
    },
  },
  'qwen.qwen3-coder-next': {
    displayName: 'Qwen3 Coder Next',
    description: 'Qwen coding model for software agents, repository edits, and code reasoning',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 131072,
    maxOutputTokens: 65536,
    structuredOutput: true,
    lastUpdated: '2026-02-06',
    capabilities: {
      vision: false,
      reasoning: true,
      functionCalling: true,
    },
    modalities: {
      input: ['text'],
      output: ['text'],
    },
  },
  'openai.gpt-oss-safeguard-120b': {
    displayName: 'GPT OSS Safeguard 120B',
    description: 'Safety model for policy screening, moderation, and risk-aware routing workflows',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 128000,
    maxOutputTokens: 16384,
    structuredOutput: true,
    lastUpdated: '2025-10-29',
    capabilities: {
      vision: false,
      reasoning: false,
      functionCalling: true,
    },
    modalities: {
      input: ['text'],
      output: ['text'],
    },
  },
  'us.anthropic.claude-opus-4-1-20250805-v1:0': {
    displayName: 'Claude Opus 4.1 (US)',
    description: 'Flagship Claude model for deep reasoning, coding, and long-horizon agents',
    lifecycle: 'deprecated',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 200000,
    maxOutputTokens: 32000,
    knowledgeCutoff: '2025-03-31',
    lastUpdated: '2025-08-05',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'us.meta.llama4-maverick-17b-instruct-v1:0': {
    displayName: 'Llama 4 Maverick 17B Instruct (US)',
    description: 'Open multimodal Llama for strong reasoning with efficient everyday serving',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    knowledgeCutoff: '2024-08',
    lastUpdated: '2025-04-05',
    capabilities: {
      vision: true,
      reasoning: false,
      functionCalling: true,
    },
    modalities: {
      input: ['text', 'image'],
      output: ['text'],
    },
  },
  'eu.anthropic.claude-fable-5': {
    displayName: 'Claude Fable 5 (EU)',
    description: 'Claude model for creative writing, analysis, and controlled agent workflows',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    knowledgeCutoff: '2026-01-31',
    lastUpdated: '2026-06-09',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['low', 'medium', 'high', 'xhigh', 'max'],
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'jp.anthropic.claude-haiku-4-5-20251001-v1:0': {
    displayName: 'Claude Haiku 4.5 (JP)',
    description:
      'Fast Claude model for responsive assistance, classification, and lightweight agents',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 200000,
    maxOutputTokens: 64000,
    knowledgeCutoff: '2025-02-28',
    structuredOutput: true,
    lastUpdated: '2025-10-15',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'au.anthropic.claude-opus-4-8': {
    displayName: 'Claude Opus 4.8 (AU)',
    description: 'Top Claude Opus tier for the hardest reasoning, coding, and long-horizon agents',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    knowledgeCutoff: '2026-01',
    lastUpdated: '2026-05-28',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['low', 'medium', 'high', 'xhigh', 'max'],
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'global.anthropic.claude-sonnet-4-5-20250929-v1:0': {
    displayName: 'Claude Sonnet 4.5 (Global)',
    description: 'Balanced Claude model for coding, analysis, agent workflows, and cost control',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 200000,
    maxOutputTokens: 64000,
    knowledgeCutoff: '2025-07-31',
    structuredOutput: true,
    lastUpdated: '2025-09-29',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'eu.anthropic.claude-haiku-4-5-20251001-v1:0': {
    displayName: 'Claude Haiku 4.5 (EU)',
    description:
      'Fast Claude model for responsive assistance, classification, and lightweight agents',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 200000,
    maxOutputTokens: 64000,
    knowledgeCutoff: '2025-02-28',
    structuredOutput: true,
    lastUpdated: '2025-10-15',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'moonshot.kimi-k2-thinking': {
    displayName: 'Kimi K2 Thinking',
    description: 'Kimi reasoning model for long-horizon research, planning, and tool use',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 262143,
    maxOutputTokens: 16000,
    structuredOutput: true,
    lastUpdated: '2025-12-02',
    capabilities: {
      vision: false,
      reasoning: true,
      functionCalling: true,
    },
    modalities: {
      input: ['text'],
      output: ['text'],
    },
  },
  'au.anthropic.claude-sonnet-4-5-20250929-v1:0': {
    displayName: 'Claude Sonnet 4.5 (AU)',
    description: 'Balanced Claude model for coding, analysis, agent workflows, and cost control',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 200000,
    maxOutputTokens: 64000,
    knowledgeCutoff: '2025-07-31',
    structuredOutput: true,
    lastUpdated: '2025-09-29',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'meta.llama4-maverick-17b-instruct-v1:0': {
    displayName: 'Llama 4 Maverick 17B Instruct',
    description: 'Open multimodal Llama model for strong reasoning and fast responses',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 1000000,
    maxOutputTokens: 16384,
    knowledgeCutoff: '2024-08',
    lastUpdated: '2025-04-05',
    capabilities: {
      vision: true,
      reasoning: false,
      functionCalling: true,
    },
    modalities: {
      input: ['text', 'image'],
      output: ['text'],
    },
  },
  'us.anthropic.claude-opus-5': {
    displayName: 'Claude Opus 5 (US)',
    description: 'Strongest Claude Opus model for coding, agents, and professional work',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    knowledgeCutoff: '2026-05',
    lastUpdated: '2026-07-24',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['low', 'medium', 'high', 'xhigh', 'max'],
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'amazon.nova-pro-v1:0': {
    displayName: 'Nova Pro',
    description: 'Flagship model for demanding analysis, coding, and production agent workflows',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 300000,
    maxOutputTokens: 8192,
    knowledgeCutoff: '2024-10',
    lastUpdated: '2024-12-03',
    capabilities: {
      vision: true,
      reasoning: false,
      functionCalling: true,
    },
    modalities: {
      input: ['text', 'image'],
      output: ['text'],
    },
  },
  'qwen.qwen3-vl-235b-a22b': {
    displayName: 'Qwen/Qwen3-VL-235B-A22B-Instruct',
    description: 'Qwen vision-language model for visual reasoning, documents, and agent tasks',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 262000,
    maxOutputTokens: 262000,
    structuredOutput: true,
    lastUpdated: '2025-11-25',
    capabilities: {
      vision: true,
      reasoning: false,
      functionCalling: true,
    },
    modalities: {
      input: ['text', 'image'],
      output: ['text'],
    },
  },
  'openai.gpt-oss-120b': {
    displayName: 'gpt-oss-120b',
    description:
      'Open-weight GPT model for self-hosted reasoning and instruction-following workloads',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 128000,
    maxOutputTokens: 16384,
    structuredOutput: true,
    lastUpdated: '2025-08-05',
    capabilities: {
      vision: false,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['low', 'medium', 'high'],
    },
    modalities: {
      input: ['text'],
      output: ['text'],
    },
  },
  'openai.gpt-5.5': {
    displayName: 'GPT-5.5',
    description: 'Default frontier GPT for coding, computer use, research, and knowledge work',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 272000,
    maxOutputTokens: 128000,
    knowledgeCutoff: '2025-12-01',
    structuredOutput: true,
    lastUpdated: '2026-06-01',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['none', 'low', 'medium', 'high', 'xhigh'],
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'minimax.minimax-m2.5': {
    displayName: 'MiniMax M2.5',
    description: 'MiniMax model for chat, coding, office work, and agentic tasks',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 196608,
    maxOutputTokens: 98304,
    structuredOutput: false,
    lastUpdated: '2026-03-18',
    capabilities: {
      vision: false,
      reasoning: true,
      functionCalling: true,
    },
    modalities: {
      input: ['text'],
      output: ['text'],
    },
  },
  'anthropic.claude-opus-4-6-v1': {
    displayName: 'Claude Opus 4.6',
    description: 'High-end Claude for difficult coding, planning, and slower expert reasoning',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    knowledgeCutoff: '2025-05-31',
    structuredOutput: true,
    lastUpdated: '2026-03-13',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['low', 'medium', 'high', 'max'],
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'us.meta.llama4-scout-17b-instruct-v1:0': {
    displayName: 'Llama 4 Scout 17B Instruct (US)',
    description: 'Open Llama with long-context vision for efficient multimodal agents',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 3500000,
    maxOutputTokens: 16384,
    knowledgeCutoff: '2024-08',
    lastUpdated: '2025-04-05',
    capabilities: {
      vision: true,
      reasoning: false,
      functionCalling: true,
    },
    modalities: {
      input: ['text', 'image'],
      output: ['text'],
    },
  },
  'writer.palmyra-x5-v1:0': {
    displayName: 'Palmyra X5',
    description:
      'Reasoning model for deliberate analysis, multi-step problem solving, and tool use',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 1040000,
    maxOutputTokens: 8192,
    lastUpdated: '2025-04-28',
    capabilities: {
      vision: false,
      reasoning: true,
      functionCalling: true,
    },
    modalities: {
      input: ['text'],
      output: ['text'],
    },
  },
  'writer.palmyra-x4-v1:0': {
    displayName: 'Palmyra X4',
    description:
      'Reasoning model for deliberate analysis, multi-step problem solving, and tool use',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 122880,
    maxOutputTokens: 8192,
    lastUpdated: '2025-04-28',
    capabilities: {
      vision: false,
      reasoning: true,
      functionCalling: true,
    },
    modalities: {
      input: ['text'],
      output: ['text'],
    },
  },
  'anthropic.claude-fable-5': {
    displayName: 'Claude Fable 5',
    description: 'Claude model for creative writing, analysis, and controlled agent workflows',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    knowledgeCutoff: '2026-01-31',
    lastUpdated: '2026-06-09',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['low', 'medium', 'high', 'xhigh', 'max'],
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'deepseek.v3-v1:0': {
    displayName: 'DeepSeek-V3.1',
    description: 'DeepSeek chat model for instruction following, coding, and analysis',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 163840,
    maxOutputTokens: 81920,
    knowledgeCutoff: '2024-07',
    structuredOutput: true,
    lastUpdated: '2025-09-18',
    capabilities: {
      vision: false,
      reasoning: true,
      functionCalling: true,
    },
    modalities: {
      input: ['text'],
      output: ['text'],
    },
  },
  'nvidia.nemotron-super-3-120b': {
    displayName: 'NVIDIA Nemotron 3 Super 120B A12B',
    description:
      'Nemotron middle tier for collaborative agents and high-volume reasoning workloads',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 262144,
    maxOutputTokens: 131072,
    structuredOutput: true,
    lastUpdated: '2026-03-11',
    capabilities: {
      vision: false,
      reasoning: true,
      functionCalling: true,
    },
    modalities: {
      input: ['text'],
      output: ['text'],
    },
  },
  'us.anthropic.claude-opus-4-8': {
    displayName: 'Claude Opus 4.8 (US)',
    description: 'Top Claude Opus tier for the hardest reasoning, coding, and long-horizon agents',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    knowledgeCutoff: '2026-01',
    lastUpdated: '2026-05-28',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['low', 'medium', 'high', 'xhigh', 'max'],
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'xai.grok-4.6': {
    displayName: 'Grok 4.6',
    description:
      "xAI's frontier model for long-running agents, coding, knowledge work, and visual projects",
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 500000,
    maxOutputTokens: 500000,
    knowledgeCutoff: '2026-02-01',
    structuredOutput: true,
    lastUpdated: '2026-08-18',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['low', 'medium', 'high', 'xhigh'],
    },
    modalities: {
      input: ['text', 'image'],
      output: ['text'],
    },
  },
  'anthropic.claude-sonnet-4-6': {
    displayName: 'Claude Sonnet 4.6',
    description:
      'Claude workhorse for coding agents, careful analysis, and production cost control',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 1000000,
    maxOutputTokens: 64000,
    knowledgeCutoff: '2025-08-31',
    structuredOutput: true,
    lastUpdated: '2026-03-13',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['low', 'medium', 'high', 'max'],
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'anthropic.claude-sonnet-5': {
    displayName: 'Claude Sonnet 5',
    description: 'Everyday Claude agent model for coding, planning, browsing, and general work',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    knowledgeCutoff: '2026-01-31',
    structuredOutput: true,
    lastUpdated: '2026-06-30',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['low', 'medium', 'high', 'xhigh', 'max'],
      toggle: true,
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'global.anthropic.claude-fable-5': {
    displayName: 'Claude Fable 5 (Global)',
    description: 'Claude model for creative writing, analysis, and controlled agent workflows',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    knowledgeCutoff: '2026-01-31',
    lastUpdated: '2026-06-09',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['low', 'medium', 'high', 'xhigh', 'max'],
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'global.anthropic.claude-opus-4-8': {
    displayName: 'Claude Opus 4.8 (Global)',
    description: 'Top Claude Opus tier for the hardest reasoning, coding, and long-horizon agents',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    knowledgeCutoff: '2026-01',
    lastUpdated: '2026-05-28',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['low', 'medium', 'high', 'xhigh', 'max'],
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'eu.anthropic.claude-opus-4-5-20251101-v1:0': {
    displayName: 'Claude Opus 4.5 (EU)',
    description: 'Flagship Claude model for deep reasoning, coding, and long-horizon agents',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 200000,
    maxOutputTokens: 64000,
    knowledgeCutoff: '2025-03-31',
    structuredOutput: true,
    lastUpdated: '2025-08-01',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['low', 'medium', 'high'],
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'google.gemma-3-27b-it': {
    displayName: 'Google Gemma 3 27B Instruct',
    description: 'Open Gemma instruction model for efficient chat and self-hosted deployments',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 202752,
    maxOutputTokens: 8192,
    knowledgeCutoff: '2025-07',
    structuredOutput: true,
    lastUpdated: '2025-07-27',
    capabilities: {
      vision: true,
      reasoning: false,
      functionCalling: true,
    },
    modalities: {
      input: ['text', 'image'],
      output: ['text'],
    },
  },
  'jp.anthropic.claude-opus-4-8': {
    displayName: 'Claude Opus 4.8 (JP)',
    description: 'Top Claude Opus tier for the hardest reasoning, coding, and long-horizon agents',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    knowledgeCutoff: '2026-01',
    lastUpdated: '2026-05-28',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['low', 'medium', 'high', 'xhigh', 'max'],
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'mistral.magistral-small-2509': {
    displayName: 'Magistral Small 1.2',
    description: 'Mistral reasoning model for transparent analysis, math, and complex decisions',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 128000,
    maxOutputTokens: 40000,
    structuredOutput: true,
    lastUpdated: '2025-12-02',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    modalities: {
      input: ['text', 'image'],
      output: ['text'],
    },
  },
  'global.anthropic.claude-opus-4-7': {
    displayName: 'Claude Opus 4.7 (Global)',
    description: 'Flagship Claude model for deep reasoning, coding, and long-horizon agents',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    knowledgeCutoff: '2026-01-31',
    lastUpdated: '2026-04-16',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['low', 'medium', 'high', 'xhigh', 'max'],
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'jp.anthropic.claude-opus-5': {
    displayName: 'Claude Opus 5 (JP)',
    description: 'Strongest Claude Opus model for coding, agents, and professional work',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    knowledgeCutoff: '2026-05',
    lastUpdated: '2026-07-24',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['low', 'medium', 'high', 'xhigh', 'max'],
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'global.anthropic.claude-haiku-4-5-20251001-v1:0': {
    displayName: 'Claude Haiku 4.5 (Global)',
    description:
      'Fast Claude model for responsive assistance, classification, and lightweight agents',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 200000,
    maxOutputTokens: 64000,
    knowledgeCutoff: '2025-02-28',
    structuredOutput: true,
    lastUpdated: '2025-10-15',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'au.anthropic.claude-opus-4-6-v1': {
    displayName: 'AU Anthropic Claude Opus 4.6',
    description: 'Flagship Claude model for deep reasoning, coding, and long-horizon agents',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    knowledgeCutoff: '2025-05',
    structuredOutput: true,
    lastUpdated: '2026-02-05',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['low', 'medium', 'high', 'max'],
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'mistral.ministral-3-8b-instruct': {
    displayName: 'Ministral 3 8B',
    description: 'Compact Mistral model for edge, latency-sensitive, and cost-efficient workloads',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 128000,
    maxOutputTokens: 4096,
    structuredOutput: true,
    lastUpdated: '2024-12-01',
    capabilities: {
      vision: false,
      reasoning: false,
      functionCalling: true,
    },
    modalities: {
      input: ['text'],
      output: ['text'],
    },
  },
  'us.anthropic.claude-haiku-4-5-20251001-v1:0': {
    displayName: 'Claude Haiku 4.5 (US)',
    description:
      'Fast Claude model for responsive assistance, classification, and lightweight agents',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 200000,
    maxOutputTokens: 64000,
    knowledgeCutoff: '2025-02-28',
    structuredOutput: true,
    lastUpdated: '2025-10-15',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'amazon.nova-lite-v1:0': {
    displayName: 'Nova Lite',
    description: 'Efficient model for low-latency assistance, extraction, and routine automation',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 300000,
    maxOutputTokens: 8192,
    knowledgeCutoff: '2024-10',
    lastUpdated: '2024-12-03',
    capabilities: {
      vision: true,
      reasoning: false,
      functionCalling: true,
    },
    modalities: {
      input: ['text', 'image'],
      output: ['text'],
    },
  },
  'openai.gpt-5.6-luna': {
    displayName: 'GPT-5.6 Luna',
    description: 'Cost-efficient GPT-5.6 model for fast, high-volume workloads',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 1050000,
    inputLimit: 922000,
    maxOutputTokens: 128000,
    knowledgeCutoff: '2026-02-16',
    structuredOutput: true,
    lastUpdated: '2026-07-09',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'nvidia.nemotron-nano-12b-v2': {
    displayName: 'NVIDIA Nemotron Nano 12B v2 VL BF16',
    description: 'Nemotron multimodal model for visual reasoning and agentic AI workflows',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 128000,
    maxOutputTokens: 4096,
    structuredOutput: true,
    lastUpdated: '2024-12-01',
    capabilities: {
      vision: true,
      reasoning: false,
      functionCalling: true,
    },
    modalities: {
      input: ['text', 'image'],
      output: ['text'],
    },
  },
  'deepseek.r1-v1:0': {
    displayName: 'DeepSeek-R1',
    description: 'DeepSeek reasoning model for multi-step analysis, math, coding, and tools',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 128000,
    maxOutputTokens: 32768,
    knowledgeCutoff: '2024-07',
    lastUpdated: '2025-05-29',
    capabilities: {
      vision: false,
      reasoning: true,
      functionCalling: true,
    },
    modalities: {
      input: ['text'],
      output: ['text'],
    },
  },
  'eu.anthropic.claude-sonnet-4-6': {
    displayName: 'Claude Sonnet 4.6 (EU)',
    description:
      'Claude workhorse for coding agents, careful analysis, and production cost control',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 1000000,
    maxOutputTokens: 64000,
    knowledgeCutoff: '2025-08-31',
    structuredOutput: true,
    lastUpdated: '2026-03-13',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['low', 'medium', 'high', 'max'],
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'minimax.minimax-m2.1': {
    displayName: 'MiniMax M2.1',
    description: 'MiniMax model for chat, coding, office work, and agentic tasks',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 204800,
    maxOutputTokens: 131072,
    structuredOutput: false,
    lastUpdated: '2025-12-23',
    capabilities: {
      vision: false,
      reasoning: true,
      functionCalling: true,
    },
    modalities: {
      input: ['text'],
      output: ['text'],
    },
  },
  'global.anthropic.claude-opus-4-5-20251101-v1:0': {
    displayName: 'Claude Opus 4.5 (Global)',
    description: 'Flagship Claude model for deep reasoning, coding, and long-horizon agents',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 200000,
    maxOutputTokens: 64000,
    knowledgeCutoff: '2025-03-31',
    structuredOutput: true,
    lastUpdated: '2025-08-01',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['low', 'medium', 'high'],
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'mistral.devstral-2-123b': {
    displayName: 'Devstral 2 123B',
    description:
      'Mistral coding agent model for repository tasks and software engineering workflows',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 256000,
    maxOutputTokens: 8192,
    structuredOutput: true,
    lastUpdated: '2026-02-17',
    capabilities: {
      vision: false,
      reasoning: false,
      functionCalling: true,
    },
    modalities: {
      input: ['text'],
      output: ['text'],
    },
  },
  'eu.anthropic.claude-sonnet-5': {
    displayName: 'Claude Sonnet 5 (EU)',
    description: 'Everyday Claude agent model for coding, planning, browsing, and general work',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    knowledgeCutoff: '2026-01-31',
    structuredOutput: true,
    lastUpdated: '2026-06-30',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['low', 'medium', 'high', 'xhigh', 'max'],
      toggle: true,
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'us.anthropic.claude-sonnet-5': {
    displayName: 'Claude Sonnet 5 (US)',
    description: 'Everyday Claude agent model for coding, planning, browsing, and general work',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    knowledgeCutoff: '2026-01-31',
    structuredOutput: true,
    lastUpdated: '2026-06-30',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['low', 'medium', 'high', 'xhigh', 'max'],
      toggle: true,
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'openai.gpt-oss-safeguard-20b': {
    displayName: 'GPT OSS Safeguard 20B',
    description: 'Safety model for policy screening, moderation, and risk-aware routing workflows',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 128000,
    maxOutputTokens: 16384,
    structuredOutput: true,
    lastUpdated: '2025-10-29',
    capabilities: {
      vision: false,
      reasoning: false,
      functionCalling: true,
    },
    modalities: {
      input: ['text'],
      output: ['text'],
    },
  },
  'anthropic.claude-opus-5': {
    displayName: 'Claude Opus 5',
    description: 'Strongest Claude Opus model for coding, agents, and professional work',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    knowledgeCutoff: '2026-05',
    lastUpdated: '2026-07-24',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['low', 'medium', 'high', 'xhigh', 'max'],
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'qwen.qwen3-32b-v1:0': {
    displayName: 'Qwen3 32B (dense)',
    description: 'Qwen instruction model for multilingual chat, reasoning, and tool use',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 16384,
    maxOutputTokens: 16384,
    knowledgeCutoff: '2024-04',
    structuredOutput: true,
    lastUpdated: '2025-09-18',
    capabilities: {
      vision: false,
      reasoning: true,
      functionCalling: true,
    },
    modalities: {
      input: ['text'],
      output: ['text'],
    },
  },
  'qwen.qwen3-coder-30b-a3b-v1:0': {
    displayName: 'Qwen3 Coder 30B A3B Instruct',
    description: 'Qwen coding model for software agents, repository edits, and code reasoning',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 262144,
    maxOutputTokens: 131072,
    knowledgeCutoff: '2024-04',
    structuredOutput: true,
    lastUpdated: '2025-09-18',
    capabilities: {
      vision: false,
      reasoning: false,
      functionCalling: true,
    },
    modalities: {
      input: ['text'],
      output: ['text'],
    },
  },
  'au.anthropic.claude-haiku-4-5-20251001-v1:0': {
    displayName: 'Claude Haiku 4.5 (AU)',
    description:
      'Fast Claude model for responsive assistance, classification, and lightweight agents',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 200000,
    maxOutputTokens: 64000,
    knowledgeCutoff: '2025-02-28',
    structuredOutput: true,
    lastUpdated: '2025-10-15',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'xai.grok-4.3': {
    displayName: 'Grok 4.3',
    description: "xAI's default Grok for chat, coding, agentic tools, and lower hallucination risk",
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 1000000,
    maxOutputTokens: 131072,
    structuredOutput: true,
    lastUpdated: '2026-06-28',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['none', 'low', 'medium', 'high'],
    },
    modalities: {
      input: ['text', 'image'],
      output: ['text'],
    },
  },
  'global.openai.gpt-5.6-luna': {
    displayName: 'GPT-5.6 Luna (Global)',
    description: 'Cost-efficient GPT-5.6 model for fast, high-volume workloads',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 1050000,
    inputLimit: 922000,
    maxOutputTokens: 128000,
    knowledgeCutoff: '2026-02-16',
    structuredOutput: true,
    lastUpdated: '2026-07-09',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'zai.glm-4.7': {
    displayName: 'GLM-4.7',
    description: 'Flagship GLM model for hybrid reasoning, coding, and agentic engineering',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 204800,
    maxOutputTokens: 131072,
    knowledgeCutoff: '2025-04',
    structuredOutput: true,
    lastUpdated: '2025-12-22',
    capabilities: {
      vision: false,
      reasoning: true,
      functionCalling: true,
    },
    modalities: {
      input: ['text'],
      output: ['text'],
    },
  },
  'us.anthropic.claude-opus-4-7': {
    displayName: 'Claude Opus 4.7 (US)',
    description: 'Flagship Claude model for deep reasoning, coding, and long-horizon agents',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    knowledgeCutoff: '2026-01-31',
    lastUpdated: '2026-04-16',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['low', 'medium', 'high', 'xhigh', 'max'],
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'us.anthropic.claude-sonnet-4-6': {
    displayName: 'Claude Sonnet 4.6 (US)',
    description:
      'Claude workhorse for coding agents, careful analysis, and production cost control',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 1000000,
    maxOutputTokens: 64000,
    knowledgeCutoff: '2025-08-31',
    structuredOutput: true,
    lastUpdated: '2026-03-13',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['low', 'medium', 'high', 'max'],
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'anthropic.claude-opus-4-7': {
    displayName: 'Claude Opus 4.7',
    description: 'Flagship Claude model for deep reasoning, coding, and long-horizon agents',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    knowledgeCutoff: '2026-01-31',
    lastUpdated: '2026-04-16',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['low', 'medium', 'high', 'xhigh', 'max'],
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'zai.glm-5': {
    displayName: 'GLM-5',
    description: 'Flagship GLM model for hybrid reasoning, coding, and agentic engineering',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 202752,
    maxOutputTokens: 101376,
    structuredOutput: true,
    lastUpdated: '2026-03-18',
    capabilities: {
      vision: false,
      reasoning: true,
      functionCalling: true,
    },
    modalities: {
      input: ['text'],
      output: ['text'],
    },
  },
  'meta.llama3-3-70b-instruct-v1:0': {
    displayName: 'Llama 3.3 70B Instruct',
    description: 'Open Llama instruction model for multilingual chat, reasoning, and coding',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 128000,
    maxOutputTokens: 4096,
    knowledgeCutoff: '2023-12',
    lastUpdated: '2024-12-06',
    capabilities: {
      vision: false,
      reasoning: false,
      functionCalling: true,
    },
    modalities: {
      input: ['text'],
      output: ['text'],
    },
  },
  'mistral.voxtral-mini-3b-2507': {
    displayName: 'Voxtral Mini 3B 2507',
    description: 'Efficient Mistral model for fast chat, extraction, and production assistants',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 128000,
    maxOutputTokens: 4096,
    structuredOutput: true,
    lastUpdated: '2024-12-01',
    capabilities: {
      vision: false,
      reasoning: false,
      functionCalling: true,
    },
    modalities: {
      input: ['audio', 'text'],
      output: ['text'],
    },
  },
  'google.gemma-3-4b-it': {
    displayName: 'Gemma 3 4B IT',
    description: 'Open Gemma instruction model for efficient chat and self-hosted deployments',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 128000,
    maxOutputTokens: 4096,
    lastUpdated: '2024-12-01',
    capabilities: {
      vision: true,
      reasoning: false,
      functionCalling: true,
    },
    modalities: {
      input: ['text', 'image'],
      output: ['text'],
    },
  },
  'amazon.nova-2-lite-v1:0': {
    displayName: 'Nova 2 Lite',
    description: 'Multimodal reasoning model for visual analysis, planning, and tool use',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 128000,
    maxOutputTokens: 4096,
    lastUpdated: '2024-12-01',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['low', 'medium', 'high'],
      toggle: true,
    },
    modalities: {
      input: ['text', 'image'],
      output: ['text'],
    },
  },
  'google.gemma-3-12b-it': {
    displayName: 'Google Gemma 3 12B',
    description: 'Open Gemma instruction model for efficient chat and self-hosted deployments',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 131072,
    maxOutputTokens: 8192,
    knowledgeCutoff: '2024-12',
    structuredOutput: true,
    lastUpdated: '2024-12-01',
    capabilities: {
      vision: true,
      reasoning: false,
      functionCalling: false,
    },
    modalities: {
      input: ['text', 'image'],
      output: ['text'],
    },
  },
  'anthropic.claude-opus-4-1-20250805-v1:0': {
    displayName: 'Claude Opus 4.1',
    description: 'Flagship Claude model for deep reasoning, coding, and long-horizon agents',
    lifecycle: 'deprecated',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 200000,
    maxOutputTokens: 32000,
    knowledgeCutoff: '2025-03-31',
    lastUpdated: '2025-08-05',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'amazon.nova-micro-v1:0': {
    displayName: 'Nova Micro',
    description: 'Efficient model for low-latency assistance, extraction, and routine automation',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 128000,
    maxOutputTokens: 8192,
    knowledgeCutoff: '2024-10',
    lastUpdated: '2024-12-03',
    capabilities: {
      vision: false,
      reasoning: false,
      functionCalling: true,
    },
    modalities: {
      input: ['text'],
      output: ['text'],
    },
  },
  'openai.gpt-5.4': {
    displayName: 'GPT-5.4',
    description: 'Agent-ready GPT for coding and computer-use workflows at a lower cost',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 272000,
    maxOutputTokens: 128000,
    knowledgeCutoff: '2025-08-31',
    structuredOutput: true,
    lastUpdated: '2026-06-01',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['none', 'low', 'medium', 'high', 'xhigh'],
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'moonshotai.kimi-k2.5': {
    displayName: 'Kimi K2.5',
    description: 'Kimi multimodal agent model for visual understanding, coding, and planning',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 262143,
    maxOutputTokens: 16000,
    structuredOutput: true,
    lastUpdated: '2026-02-06',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    modalities: {
      input: ['text', 'image'],
      output: ['text'],
    },
  },
  'anthropic.claude-opus-4-5-20251101-v1:0': {
    displayName: 'Claude Opus 4.5',
    description: 'Flagship Claude model for deep reasoning, coding, and long-horizon agents',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 200000,
    maxOutputTokens: 64000,
    knowledgeCutoff: '2025-03-31',
    structuredOutput: true,
    lastUpdated: '2025-08-01',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['low', 'medium', 'high'],
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'qwen.qwen3-next-80b-a3b': {
    displayName: 'Qwen/Qwen3-Next-80B-A3B-Instruct',
    description: 'Qwen instruction model for multilingual chat, reasoning, and tool use',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 262000,
    maxOutputTokens: 262000,
    structuredOutput: true,
    lastUpdated: '2025-11-25',
    capabilities: {
      vision: false,
      reasoning: false,
      functionCalling: true,
    },
    modalities: {
      input: ['text'],
      output: ['text'],
    },
  },
  'au.anthropic.claude-opus-5': {
    displayName: 'Claude Opus 5 (AU)',
    description: 'Strongest Claude Opus model for coding, agents, and professional work',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    knowledgeCutoff: '2026-05',
    lastUpdated: '2026-07-24',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['low', 'medium', 'high', 'xhigh', 'max'],
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'us.anthropic.claude-sonnet-4-5-20250929-v1:0': {
    displayName: 'Claude Sonnet 4.5 (US)',
    description: 'Balanced Claude model for coding, analysis, agent workflows, and cost control',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 200000,
    maxOutputTokens: 64000,
    knowledgeCutoff: '2025-07-31',
    structuredOutput: true,
    lastUpdated: '2025-09-29',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'global.openai.gpt-5.6-terra': {
    displayName: 'GPT-5.6 Terra (Global)',
    description: 'Balanced GPT-5.6 model for capable, cost-efficient everyday work',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 1050000,
    inputLimit: 922000,
    maxOutputTokens: 128000,
    knowledgeCutoff: '2026-02-16',
    structuredOutput: true,
    lastUpdated: '2026-07-09',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'openai.gpt-oss-20b-1:0': {
    displayName: 'gpt-oss-20b',
    description:
      'Open-weight GPT model for self-hosted reasoning and instruction-following workloads',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 128000,
    maxOutputTokens: 16384,
    structuredOutput: true,
    lastUpdated: '2025-08-05',
    capabilities: {
      vision: false,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['low', 'medium', 'high'],
    },
    modalities: {
      input: ['text'],
      output: ['text'],
    },
  },
  'openai.gpt-oss-20b': {
    displayName: 'gpt-oss-20b',
    description:
      'Open-weight GPT model for self-hosted reasoning and instruction-following workloads',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 128000,
    maxOutputTokens: 16384,
    structuredOutput: true,
    lastUpdated: '2025-08-05',
    capabilities: {
      vision: false,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['low', 'medium', 'high'],
    },
    modalities: {
      input: ['text'],
      output: ['text'],
    },
  },
  'global.anthropic.claude-opus-5': {
    displayName: 'Claude Opus 5 (Global)',
    description: 'Strongest Claude Opus model for coding, agents, and professional work',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    knowledgeCutoff: '2026-05',
    lastUpdated: '2026-07-24',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['low', 'medium', 'high', 'xhigh', 'max'],
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'meta.llama4-scout-17b-instruct-v1:0': {
    displayName: 'Llama 4 Scout 17B Instruct',
    description: 'Open multimodal Llama model for long-context analysis and efficient agents',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 3500000,
    maxOutputTokens: 16384,
    knowledgeCutoff: '2024-08',
    lastUpdated: '2025-04-05',
    capabilities: {
      vision: true,
      reasoning: false,
      functionCalling: true,
    },
    modalities: {
      input: ['text', 'image'],
      output: ['text'],
    },
  },
  'zai.glm-4.7-flash': {
    displayName: 'GLM-4.7-Flash',
    description: 'Efficient GLM model for fast reasoning, coding, and agent workflows',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 200000,
    maxOutputTokens: 131072,
    knowledgeCutoff: '2025-04',
    structuredOutput: true,
    lastUpdated: '2026-01-19',
    capabilities: {
      vision: false,
      reasoning: true,
      functionCalling: true,
    },
    modalities: {
      input: ['text'],
      output: ['text'],
    },
  },
  'us.anthropic.claude-opus-4-5-20251101-v1:0': {
    displayName: 'Claude Opus 4.5 (US)',
    description: 'Flagship Claude model for deep reasoning, coding, and long-horizon agents',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 200000,
    maxOutputTokens: 64000,
    knowledgeCutoff: '2025-03-31',
    structuredOutput: true,
    lastUpdated: '2025-08-01',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['low', 'medium', 'high'],
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'us.anthropic.claude-opus-4-6-v1': {
    displayName: 'Claude Opus 4.6 (US)',
    description: 'High-end Claude for difficult coding, planning, and slower expert reasoning',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    knowledgeCutoff: '2025-05-31',
    structuredOutput: true,
    lastUpdated: '2026-03-13',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['low', 'medium', 'high', 'max'],
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'eu.anthropic.claude-opus-4-8': {
    displayName: 'Claude Opus 4.8 (EU)',
    description: 'Top Claude Opus tier for the hardest reasoning, coding, and long-horizon agents',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    knowledgeCutoff: '2026-01',
    lastUpdated: '2026-05-28',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['low', 'medium', 'high', 'xhigh', 'max'],
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'nvidia.nemotron-nano-9b-v2': {
    displayName: 'NVIDIA Nemotron Nano 9B v2',
    description: 'Compact Nemotron model for efficient reasoning and deployable AI agents',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 128000,
    maxOutputTokens: 4096,
    structuredOutput: true,
    lastUpdated: '2024-12-01',
    capabilities: {
      vision: false,
      reasoning: false,
      functionCalling: true,
    },
    modalities: {
      input: ['text'],
      output: ['text'],
    },
  },
  'meta.llama3-1-8b-instruct-v1:0': {
    displayName: 'Llama 3.1 8B Instruct',
    description: 'Open Llama instruction model for multilingual chat, reasoning, and coding',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 128000,
    maxOutputTokens: 4096,
    knowledgeCutoff: '2023-12',
    lastUpdated: '2024-07-23',
    capabilities: {
      vision: false,
      reasoning: false,
      functionCalling: true,
    },
    modalities: {
      input: ['text'],
      output: ['text'],
    },
  },
  'nvidia.nemotron-nano-3-30b': {
    displayName: 'NVIDIA Nemotron Nano 3 30B',
    description: 'Small Nemotron 3 MoE for efficient coding, math, and long-context agents',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 128000,
    maxOutputTokens: 4096,
    structuredOutput: true,
    lastUpdated: '2025-12-23',
    capabilities: {
      vision: false,
      reasoning: true,
      functionCalling: true,
    },
    modalities: {
      input: ['text'],
      output: ['text'],
    },
  },
  'openai.gpt-5.6-sol': {
    displayName: 'GPT-5.6 Sol',
    description:
      'Frontier GPT-5.6 model for complex professional work, coding, and agentic workflows',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 1050000,
    inputLimit: 922000,
    maxOutputTokens: 128000,
    knowledgeCutoff: '2026-02-16',
    structuredOutput: true,
    lastUpdated: '2026-07-09',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'eu.anthropic.claude-opus-4-7': {
    displayName: 'Claude Opus 4.7 (EU)',
    description: 'Flagship Claude model for deep reasoning, coding, and long-horizon agents',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    knowledgeCutoff: '2026-01-31',
    lastUpdated: '2026-04-16',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['low', 'medium', 'high', 'xhigh', 'max'],
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'openai.gpt-oss-120b-1:0': {
    displayName: 'gpt-oss-120b',
    description:
      'Open-weight GPT model for self-hosted reasoning and instruction-following workloads',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 128000,
    maxOutputTokens: 16384,
    structuredOutput: true,
    lastUpdated: '2025-08-05',
    capabilities: {
      vision: false,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['low', 'medium', 'high'],
    },
    modalities: {
      input: ['text'],
      output: ['text'],
    },
  },
  'eu.anthropic.claude-opus-4-6-v1': {
    displayName: 'Claude Opus 4.6 (EU)',
    description: 'High-end Claude for difficult coding, planning, and slower expert reasoning',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    knowledgeCutoff: '2025-05-31',
    structuredOutput: true,
    lastUpdated: '2026-03-13',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['low', 'medium', 'high', 'max'],
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'meta.llama3-1-70b-instruct-v1:0': {
    displayName: 'Llama 3.1 70B Instruct',
    description: 'Open Llama instruction model for multilingual chat, reasoning, and coding',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 128000,
    maxOutputTokens: 4096,
    knowledgeCutoff: '2023-12',
    lastUpdated: '2024-07-23',
    capabilities: {
      vision: false,
      reasoning: false,
      functionCalling: true,
    },
    modalities: {
      input: ['text'],
      output: ['text'],
    },
  },
  'eu.anthropic.claude-sonnet-4-5-20250929-v1:0': {
    displayName: 'Claude Sonnet 4.5 (EU)',
    description: 'Balanced Claude model for coding, analysis, agent workflows, and cost control',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 200000,
    maxOutputTokens: 64000,
    knowledgeCutoff: '2025-07-31',
    structuredOutput: true,
    lastUpdated: '2025-09-29',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'global.anthropic.claude-opus-4-6-v1': {
    displayName: 'Claude Opus 4.6 (Global)',
    description: 'High-end Claude for difficult coding, planning, and slower expert reasoning',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    knowledgeCutoff: '2025-05-31',
    structuredOutput: true,
    lastUpdated: '2026-03-13',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['low', 'medium', 'high', 'max'],
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'anthropic.claude-opus-4-8': {
    displayName: 'Claude Opus 4.8',
    description: 'Top Claude Opus tier for the hardest reasoning, coding, and long-horizon agents',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 1000000,
    maxOutputTokens: 128000,
    knowledgeCutoff: '2026-01',
    lastUpdated: '2026-05-28',
    capabilities: {
      vision: true,
      reasoning: true,
      functionCalling: true,
    },
    thinkingOptions: {
      efforts: ['low', 'medium', 'high', 'xhigh', 'max'],
    },
    modalities: {
      input: ['text', 'image', 'pdf'],
      output: ['text'],
    },
  },
  'mistral.ministral-3-14b-instruct': {
    displayName: 'Ministral 14B 3.0',
    description: 'Compact Mistral model for edge, latency-sensitive, and cost-efficient workloads',
    lifecycle: 'active',
    docsUrl: 'https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
    contextWindow: 128000,
    maxOutputTokens: 4096,
    structuredOutput: true,
    lastUpdated: '2024-12-01',
    capabilities: {
      vision: false,
      reasoning: false,
      functionCalling: true,
    },
    modalities: {
      input: ['text'],
      output: ['text'],
    },
  },
};
