/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// TODO #3975: ko dictionaries staged off the enabled UiLocale union (['zh','en']).
// They are intentionally added as `as const` entries without widening UiCatalog/UiLocale.
// Will be wired when UI_LOCALES adds 'ko' via #3975 (atomic enable, see #3974).
export const TUI_COPY_RESOURCES = {
  'mcp-status': {
    en: {
      title: 'MCP SERVERS',
      footer: {
        back: 'Esc back',
        readOnly: '↑/↓ scroll · q/Esc close',
        manage:
          'a Add · Enter Edit · Space Enable/disable · t Test · r Reconnect · d Remove · Esc Close',
      },
      unavailableTitle: 'This TUI is not connected to a local MCP control plane.',
      unavailableDetail:
        'Client MCP tool association for remote Runtime Hosts is planned for a later release.',
      loading: 'Loading mcp.json and discovering tools…',
      loadError:
        'MCP configuration could not be loaded; no tools were published to the Runtime Host.',
      noServers: 'No MCP servers are configured. Press a to add one.',
      publication: {
        waiting: 'waiting to publish',
        host_unavailable: 'Runtime Host reconnecting',
        publishing: 'publishing',
        published: 'published',
        not_published: 'not published',
        error: 'publication failed',
      },
      serverState: {
        disabled: 'disabled',
        disconnected: 'disconnected',
        connecting: 'connecting',
        connected: 'connected',
        'needs-auth': 'needs-auth',
        error: 'error',
      },
      configuredOnly: 'configured only',
      configPending: 'config pending',
      toolCount: '{count, plural, one {# tool} other {# tools}}',
    },
    zh: {
      title: 'MCP 服务器',
      footer: {
        back: 'Esc 返回',
        readOnly: '↑/↓ 滚动 · q/Esc 关闭',
        manage: 'a 添加 · Enter 编辑 · Space 启用/停用 · t 测试 · r 重连 · d 删除 · Esc 关闭',
      },
      unavailableTitle: '当前 TUI 未连接本地 MCP 控制面。',
      unavailableDetail: '远程 Runtime Host 的客户端 MCP 工具关联将在后续版本提供。',
      loading: '正在读取 mcp.json 并发现工具…',
      loadError: '无法读取或应用 MCP 配置；没有向 Runtime Host 发布工具。',
      noServers: '尚未配置 MCP 服务器。按 a 添加。',
      publication: {
        waiting: '等待发布',
        host_unavailable: 'Runtime Host 重连中',
        publishing: '正在发布',
        published: '已发布',
        not_published: '未发布',
        error: '发布失败',
      },
      serverState: {
        disabled: '已停用',
        disconnected: '未连接',
        connecting: '连接中',
        connected: '已连接',
        'needs-auth': '需要登录',
        error: '错误',
      },
      configuredOnly: '仅已配置',
      configPending: '配置待同步',
      toolCount: '{count} 个工具',
    },
    ko: {
      title: 'MCP 서버',
      footer: {
        back: 'Esc 뒤로',
        readOnly: '↑/↓ 스크롤 · q/Esc 닫기',
        manage: 'a 추가 · Enter 편집 · Space 활성화/비활성화 · t 테스트 · r 재연결 · d 삭제 · Esc 닫기',
      },
      unavailableTitle: '이 TUI는 로컬 MCP 제어 평면에 연결되어 있지 않습니다.',
      unavailableDetail: '원격 Runtime Host의 클라이언트 MCP 도구 연결은 향후 릴리스에서 제공될 예정입니다.',
      loading: 'mcp.json을 읽고 도구를 탐색하는 중…',
      loadError: 'MCP 구성을 불러올 수 없어 Runtime Host에 도구를 게시하지 못했습니다.',
      noServers: '구성된 MCP 서버가 없습니다. a를 눌러 추가하세요.',
      publication: {
        waiting: '게시 대기 중',
        host_unavailable: 'Runtime Host 재연결 중',
        publishing: '게시 중',
        published: '게시됨',
        not_published: '미게시',
        error: '게시 실패',
      },
      serverState: {
        disabled: '비활성화됨',
        disconnected: '연결 끊김',
        connecting: '연결 중',
        connected: '연결됨',
        'needs-auth': '인증 필요',
        error: '오류',
      },
      configuredOnly: '구성만',
      configPending: '구성 대기 중',
      toolCount: '{count}개 도구',
    },
  },
  pickers: {
    en: {
      modelPickerTitle: 'Select Model',
      modelSwitchCacheWarning:
        '⚠ Switching models may rebuild the prompt cache; the next request may be slower or cost more.',
      modelSearchHint:
        'Search models / providers / connections · ↑↓ select · Enter confirm · Esc cancel',
      searchLabel: 'Search',
      noMatchingModels: 'No matching models',
      selectPickerHint: '↑↓ select · Enter confirm · Esc close',
      providerConfigured: 'configured',
      addAccount: 'add account',
      thinkingLevels: {
        off: 'Off',
        minimal: 'Minimal',
        low: 'Low',
        medium: 'Medium',
        high: 'High',
        xhigh: 'Extra high',
        max: 'Maximum',
      },
      defaultThinkingLevel: 'Default',
      thinkingPickerTitle: 'Select Thinking Level',
      currentMarker: 'current',
      defaultMarker: 'default',
      setupTitle: 'Set Up Provider',
      baseUrlLabel: 'Base URL',
      apiKeyLabel: 'API key',
      onboardingUnavailable:
        'Onboarding is unavailable: this environment does not provide a setup surface.',
      onboardingRequestFailed: 'Could not reach the Runtime Host. Try again.',
      onboardingRejections: {
        provider_unsupported: 'This provider does not support API-key onboarding.',
        connection_not_found: 'This connection no longer exists. Reopen /setup and try again.',
        credential_not_configured: 'An API key is required.',
        base_url_not_configured: 'A Base URL is required for this provider.',
        catalog_full: 'The connection catalog is full.',
        model_unavailable: 'A selected model is no longer available. Verify and select again.',
        superseded: 'This connection changed. Reopen /setup and try again.',
      },
      onboardingFailures: {
        auth: 'Provider authentication failed. Check the API key and try again.',
        timeout: 'Provider verification timed out. Try again.',
        provider_unavailable: 'The provider is unavailable. Try again later.',
        network: 'A network error interrupted provider verification. Try again.',
        invalid_response: 'The provider returned an invalid response. Try again.',
        unknown: 'Provider verification failed. Try again.',
      },
      accountSavedRefreshFailed:
        'Account saved, but the model list has not refreshed. Restart Maka to reload it.',
      listProvidersFailed: 'Could not read configured connections.',
      noConfigurableProviders: 'No configurable API key providers are available.',
      baseUrlRequired: 'Enter a Base URL',
      baseUrlInvalid: 'Base URL is not a valid URL',
      baseUrlProtocol: 'Base URL must use http or https',
      baseUrlCredentials: 'Base URL cannot include credentials',
      baseUrlQuery: 'Base URL cannot include a query or fragment',
      baseUrlTooLong: 'Base URL cannot exceed 2048 bytes',
      selectModelBeforeSaving: 'Select at least one model before saving',
      reuseBaseUrlHint:
        'Leave blank to reuse the saved Base URL, or enter a replacement · Esc returns to provider selection',
      enterBaseUrlHint: 'Enter the relay Base URL (http/https) · Esc returns to provider selection',
      continueAction: 'Enter to continue',
      providerSearchHint: 'Search providers · ↑↓ select · Enter confirm · Esc cancel',
      noMatchingProviders: 'No matching providers',
      keyHints: {
        reuse: {
          baseUrl:
            'Leave blank to reuse the saved key, or enter a new key to rotate it · Esc returns to Base URL',
          provider:
            'Leave blank to reuse the saved key, or enter a new key to rotate it · Esc returns to provider selection',
        },
        enter: {
          baseUrl: 'Enter an API key · stored only on this machine · Esc returns to Base URL',
          provider:
            'Enter an API key · stored only on this machine · Esc returns to provider selection',
        },
      },
      submitAction: 'Enter to submit',
      verifyingKey: 'Verifying key…',
      modelSelectionHint: 'Search models · ↑↓ select · Space toggle · Enter save · Esc back',
      selectedModels: '{count} selected',
      selectedModelsAndSave: '{count} selected · Enter to save',
      saving: 'Saving…',
      complete: 'Complete',
      enabledModels: 'Models enabled: {count}',
      closeAction: 'Enter to close',
      thinkingUnsupported: 'This model does not support changing the thinking level.',
    },
    zh: {
      modelPickerTitle: '选择模型',
      modelSwitchCacheWarning: '⚠ 切换模型可能需要重建提示缓存；下一次请求可能更慢或成本更高。',
      modelSearchHint: '搜索模型 / 服务商 / 连接 · ↑↓ 选择 · Enter 确认 · Esc 取消',
      searchLabel: '搜索',
      noMatchingModels: '没有匹配的模型',
      selectPickerHint: '↑↓ 选择 · Enter 确认 · Esc 关闭',
      providerConfigured: '已设置',
      addAccount: '添加账号',
      thinkingLevels: {
        off: '关',
        minimal: '最小',
        low: '低',
        medium: '中',
        high: '高',
        xhigh: '超高',
        max: '最高',
      },
      defaultThinkingLevel: '默认',
      thinkingPickerTitle: '选择思考级别',
      currentMarker: '当前',
      defaultMarker: '默认',
      setupTitle: '配置模型提供商',
      baseUrlLabel: 'Base URL',
      apiKeyLabel: 'API key',
      onboardingUnavailable: 'Onboarding 不可用：当前运行环境未提供配置入口。',
      onboardingRequestFailed: '无法连接 Runtime Host，请重试。',
      onboardingRejections: {
        provider_unsupported: '该服务商不支持 API key 配置。',
        connection_not_found: '该连接已不存在，请重新打开 /setup 后重试。',
        credential_not_configured: '需要填写 API key。',
        base_url_not_configured: '该服务商需要填写 Base URL。',
        catalog_full: '连接目录已满。',
        model_unavailable: '所选模型已不可用，请重新验证并选择。',
        superseded: '该连接已发生变化，请重新打开 /setup 后重试。',
      },
      onboardingFailures: {
        auth: '服务商身份验证失败，请检查 API key 后重试。',
        timeout: '服务商验证超时，请重试。',
        provider_unavailable: '服务商当前不可用，请稍后重试。',
        network: '网络错误中断了服务商验证，请重试。',
        invalid_response: '服务商返回了无效响应，请重试。',
        unknown: '服务商验证失败，请重试。',
      },
      accountSavedRefreshFailed: '账号已保存，但模型列表暂未刷新。重启 Maka 后会重新载入。',
      listProvidersFailed: '无法读取已配置的连接。',
      noConfigurableProviders: '没有可配置的 API key 类供应商。',
      baseUrlRequired: '需要填写 Base URL',
      baseUrlInvalid: 'Base URL 不是有效的 URL',
      baseUrlProtocol: 'Base URL 必须使用 http 或 https',
      baseUrlCredentials: 'Base URL 不能包含账号密码',
      baseUrlQuery: 'Base URL 不能包含查询串或片段',
      baseUrlTooLong: 'Base URL 不能超过 2048 字节',
      selectModelBeforeSaving: '至少选择一个模型再保存',
      reuseBaseUrlHint: '留空复用已保存的 Base URL，或输入新地址替换 · Esc 返回选择服务商',
      enterBaseUrlHint: '输入中转站的 Base URL（http/https）· Esc 返回选择服务商',
      continueAction: 'Enter 继续',
      providerSearchHint: '搜索服务商，↑↓ 选择 · Enter 确认 · Esc 取消',
      noMatchingProviders: '没有匹配的服务商',
      keyHints: {
        reuse: {
          baseUrl: '留空复用已保存的 key，或输入新 key 轮换 · Esc 返回 Base URL',
          provider: '留空复用已保存的 key，或输入新 key 轮换 · Esc 返回选择服务商',
        },
        enter: {
          baseUrl: '输入 API key · 仅本机存储 · Esc 返回 Base URL',
          provider: '输入 API key · 仅本机存储 · Esc 返回选择服务商',
        },
      },
      submitAction: 'Enter 提交',
      verifyingKey: '正在验证 key…',
      modelSelectionHint: '搜索模型，↑↓ 选择 · Space 切换 · Enter 保存 · Esc 返回',
      selectedModels: '已选 {count}',
      selectedModelsAndSave: '已选 {count} · Enter 保存',
      saving: '正在保存…',
      complete: '完成',
      enabledModels: '已启用模型：{count}',
      closeAction: 'Enter 关闭',
      thinkingUnsupported: '当前模型不支持思考级别切换。',
    },
    ko: {
      modelPickerTitle: '모델 선택',
      modelSwitchCacheWarning: '⚠ 모델을 전환하면 프롬프트 캐시가 재구축될 수 있어 다음 요청이 더 느리거나 비용이 더 들 수 있습니다.',
      modelSearchHint: '모델 / 프로바이더 / 연결 검색 · ↑↓ 선택 · Enter 확인 · Esc 취소',
      searchLabel: '검색',
      noMatchingModels: '일치하는 모델이 없습니다',
      selectPickerHint: '↑↓ 선택 · Enter 확인 · Esc 닫기',
      providerConfigured: '구성됨',
      addAccount: '계정 추가',
      thinkingLevels: {
        off: '끔',
        minimal: '최소',
        low: '낮음',
        medium: '중간',
        high: '높음',
        xhigh: '매우 높음',
        max: '최대',
      },
      defaultThinkingLevel: '기본값',
      thinkingPickerTitle: '사고 수준 선택',
      currentMarker: '현재',
      defaultMarker: '기본값',
      setupTitle: '프로바이더 설정',
      baseUrlLabel: 'Base URL',
      apiKeyLabel: 'API 키',
      onboardingUnavailable: '온보딩을 사용할 수 없습니다. 이 환경에서는 설정 화면을 제공하지 않습니다.',
      onboardingRequestFailed: 'Runtime Host에 연결할 수 없습니다. 다시 시도하세요.',
      onboardingRejections: {
        provider_unsupported: '이 프로바이더는 API 키 온보딩을 지원하지 않습니다.',
        connection_not_found: '이 연결을 더 이상 찾을 수 없습니다. /setup을 다시 열어 시도하세요.',
        credential_not_configured: 'API 키가 필요합니다.',
        base_url_not_configured: '이 프로바이더는 Base URL이 필요합니다.',
        catalog_full: '연결 카탈로그가 가득 찼습니다.',
        model_unavailable: '선택한 모델을 더 이상 사용할 수 없습니다. 확인 후 다시 선택하세요.',
        superseded: '이 연결이 변경되었습니다. /setup을 다시 열어 시도하세요.',
      },
      onboardingFailures: {
        auth: '프로바이더 인증에 실패했습니다. API 키를 확인하고 다시 시도하세요.',
        timeout: '프로바이더 확인 시간이 초과되었습니다. 다시 시도하세요.',
        provider_unavailable: '프로바이더를 사용할 수 없습니다. 나중에 다시 시도하세요.',
        network: '네트워크 오류로 프로바이더 확인이 중단되었습니다. 다시 시도하세요.',
        invalid_response: '프로바이더가 잘못된 응답을 반환했습니다. 다시 시도하세요.',
        unknown: '프로바이더 확인에 실패했습니다. 다시 시도하세요.',
      },
      accountSavedRefreshFailed: '계정은 저장되었지만 모델 목록이 새로고침되지 않았습니다. Maka를 다시 시작하면 다시 불러옵니다.',
      listProvidersFailed: '구성된 연결을 읽을 수 없습니다.',
      noConfigurableProviders: '구성 가능한 API 키 프로바이더가 없습니다.',
      baseUrlRequired: 'Base URL을 입력하세요',
      baseUrlInvalid: 'Base URL이 올바른 URL이 아닙니다',
      baseUrlProtocol: 'Base URL은 http 또는 https를 사용해야 합니다',
      baseUrlCredentials: 'Base URL에 인증 정보를 포함할 수 없습니다',
      baseUrlQuery: 'Base URL에 쿼리나 프래그먼트를 포함할 수 없습니다',
      baseUrlTooLong: 'Base URL은 2048바이트를 초과할 수 없습니다',
      selectModelBeforeSaving: '저장하기 전에 최소 하나의 모델을 선택하세요',
      reuseBaseUrlHint: '비워두면 저장된 Base URL을 재사용하거나, 새 주소를 입력해 교체하세요 · Esc로 프로바이더 선택으로 돌아가기',
      enterBaseUrlHint: '릴레이 Base URL 입력 (http/https) · Esc로 프로바이더 선택으로 돌아가기',
      continueAction: 'Enter로 계속',
      providerSearchHint: '프로바이더 검색 · ↑↓ 선택 · Enter 확인 · Esc 취소',
      noMatchingProviders: '일치하는 프로바이더가 없습니다',
      keyHints: {
        reuse: {
          baseUrl: '비워두면 저장된 키를 재사용하거나, 새 키를 입력해 교체하세요 · Esc로 Base URL로 돌아가기',
          provider: '비워두면 저장된 키를 재사용하거나, 새 키를 입력해 교체하세요 · Esc로 프로바이더 선택으로 돌아가기',
        },
        enter: {
          baseUrl: 'API 키 입력 · 이 기기에만 저장됨 · Esc로 Base URL로 돌아가기',
          provider: 'API 키 입력 · 이 기기에만 저장됨 · Esc로 프로바이더 선택으로 돌아가기',
        },
      },
      submitAction: 'Enter로 제출',
      verifyingKey: '키 확인 중…',
      modelSelectionHint: '모델 검색 · ↑↓ 선택 · Space 토글 · Enter 저장 · Esc 뒤로',
      selectedModels: '{count}개 선택됨',
      selectedModelsAndSave: '{count}개 선택됨 · Enter로 저장',
      saving: '저장 중…',
      complete: '완료',
      enabledModels: '활성화된 모델: {count}개',
      closeAction: 'Enter로 닫기',
      thinkingUnsupported: '이 모델은 사고 수준 변경을 지원하지 않습니다.',
    },
  },
  'primary-guidance': {
    en: {
      welcome: {
        tagline: 'Get things done together',
        start: 'Type a message to start',
        session: 'Switch or resume a session',
        model: 'Switch models',
        setup: 'Set up a model provider',
      },
      commands: {
        compact: 'Compact session context',
        context: 'Show latest request context usage',
        exit: 'Exit Maka',
        goal: 'Show autonomous goal status',
        graph: 'Show, enable, disable, or run one Graph turn',
        help: 'Show commands and keybindings',
        mcp: 'Manage client-owned MCP servers and tool publication status',
        model: 'Select model',
        move: 'Move current session to another directory',
        new: 'Start a new session',
        permissions: 'Set session permissions',
        recap: 'One-sentence recap of the session so far',
        rename: 'Rename current session',
        resume: 'Resume latest interrupted run at a safe boundary',
        rewind: 'Rewind to an earlier turn',
        session: 'Resume session',
        setup: 'Set up a model provider (API key)',
        side: 'Open a temporary side conversation',
        skill: 'Invoke a skill (or type /skill:<name> inline)',
        swarm: 'Show, enable, disable, or run one Swarm turn',
        thinking: 'Set thinking level',
        transcript: 'Browse the full transcript inside Maka',
      },
      help: {
        commandsHeading: 'Commands',
        userCommand: '  !<command> — run one shell command visible only to you',
        keybindingsHeading: 'Keybindings',
        keybindings: [
          '  Ctrl+O — expand or collapse all tool output',
          '  Ctrl+T — expand or collapse all thinking in view',
          '  Scroll the transcript with your terminal or trackpad',
          '  Enter (during a turn) — steer: inject a message into the running turn',
          '  Alt+Enter (during a turn) — queue a message for the next turn',
          '  Alt+↑ — take queued messages back into the editor to re-edit',
          '  Esc Esc (during a turn) — interrupt the turn',
          '  Esc Esc (when idle) — rewind to an earlier turn',
          '  Ctrl+C — stop the turn, clear input, or press twice to exit',
          '  Ctrl+D — exit when input is empty',
        ],
      },
    },
    zh: {
      welcome: {
        tagline: '陪你把事做完',
        start: '输入消息开始对话',
        session: '切换或恢复会话',
        model: '切换模型',
        setup: '配置模型提供商',
      },
      commands: {
        compact: '压缩会话上下文',
        context: '查看最近一次请求的上下文用量',
        exit: '退出 Maka',
        goal: '查看自主目标状态',
        graph: '查看、启用、停用 Graph 模式，或执行一次 Graph 任务',
        help: '查看命令和快捷键',
        mcp: '管理客户端 MCP 服务器和工具发布状态',
        model: '选择模型',
        move: '将当前会话移到其他目录',
        new: '新建会话',
        permissions: '设置会话权限',
        recap: '用一句话总结当前会话',
        rename: '重命名当前会话',
        resume: '从安全边界恢复最近一次中断的执行',
        rewind: '回退到较早的对话轮次',
        session: '切换或恢复会话',
        setup: '配置模型提供商（API Key）',
        side: '打开临时 Side Conversation',
        skill: '调用 Skill（也可直接输入 /skill:<name>）',
        swarm: '查看、启用、停用 Swarm 模式，或执行一次 Swarm 任务',
        thinking: '设置思考级别',
        transcript: '在 Maka 内浏览完整对话记录',
      },
      help: {
        commandsHeading: '命令',
        userCommand: '  !<command> — 执行一次仅用户可见的 shell 命令',
        keybindingsHeading: '快捷键',
        keybindings: [
          '  Ctrl+O — 展开或折叠所有工具输出',
          '  Ctrl+T — 展开或折叠视图中的所有思考块',
          '  使用终端或触控板滚动对话记录',
          '  Enter（任务运行中）— 将消息注入当前任务',
          '  Alt+Enter（任务运行中）— 将消息排入下一轮',
          '  Alt+↑ — 将已排队消息取回编辑器重新编辑',
          '  Esc Esc（任务运行中）— 中断当前任务',
          '  Esc Esc（空闲时）— 回退到较早的轮次',
          '  Ctrl+C — 停止任务、清空输入，或连续按两次退出',
          '  Ctrl+D — 输入为空时退出',
        ],
      },
    },
    ko: {
      welcome: {
        tagline: '함께 일을 완수하세요',
        start: '메시지를 입력해 시작하세요',
        session: '세션을 전환하거나 재개하세요',
        model: '모델 전환',
        setup: '모델 프로바이더 설정',
      },
      commands: {
        compact: '세션 컨텍스트 압축',
        context: '최근 요청의 컨텍스트 사용량 보기',
        exit: 'Maka 종료',
        goal: '자율 목표 상태 보기',
        graph: 'Graph 모드 보기, 활성화/비활성화 또는 Graph 작업 실행',
        help: '명령어와 단축키 보기',
        mcp: '클라이언트 MCP 서버 및 도구 게시 상태 관리',
        model: '모델 선택',
        move: '현재 세션을 다른 디렉터리로 이동',
        new: '새 세션 시작',
        permissions: '세션 권한 설정',
        recap: '지금까지의 세션을 한 문장으로 요약',
        rename: '현재 세션 이름 바꾸기',
        resume: '안전한 경계에서 최근 중단된 실행 재개',
        rewind: '이전 턴으로 되돌리기',
        session: '세션 전환 또는 재개',
        setup: '모델 프로바이더 설정 (API 키)',
        side: '임시 Side Conversation 열기',
        skill: '스킬 호출 (또는 /skill:<name> 직접 입력)',
        swarm: 'Swarm 모드 보기, 활성화/비활성화 또는 Swarm 작업 실행',
        thinking: '사고 수준 설정',
        transcript: 'Maka에서 전체 대화 기록 보기',
      },
      help: {
        commandsHeading: '명령어',
        userCommand: '  !<command> — 사용자만 볼 수 있는 셸 명령어 한 번 실행',
        keybindingsHeading: '단축키',
        keybindings: [
          '  Ctrl+O — 모든 도구 출력 펼치기/접기',
          '  Ctrl+T — 보기의 모든 사고 블록 펼치기/접기',
          '  터미널이나 트랙패드로 대화 기록 스크롤',
          '  Enter (턴 실행 중) — 실행 중인 턴에 메시지 주입',
          '  Alt+Enter (턴 실행 중) — 다음 턴을 위해 메시지 대기열에 추가',
          '  Alt+↑ — 대기열에 있는 메시지를 편집기로 가져와 다시 편집',
          '  Esc Esc (턴 실행 중) — 턴 중단',
          '  Esc Esc (대기 중) — 이전 턴으로 되돌리기',
          '  Ctrl+C — 턴 중지, 입력 지우기 또는 두 번 눌러 종료',
          '  Ctrl+D — 입력이 비어 있을 때 종료',
        ],
      },
    },
  },
  'session-status': {
    en: {
      running: 'running',
      waitingForUser: 'waiting for you',
      permissionRequired: 'needs permission',
      connectionRequired: 'needs connection',
      signInRequired: 'needs sign-in',
      stopped: 'stopped',
    },
    zh: {
      running: '进行中',
      waitingForUser: '等你确认',
      permissionRequired: '需要权限',
      connectionRequired: '需要连接',
      signInRequired: '需要重新登录',
      stopped: '已中止',
    },
    ko: {
      running: '실행 중',
      waitingForUser: '사용자 대기 중',
      permissionRequired: '권한 필요',
      connectionRequired: '연결 필요',
      signInRequired: '로그인 필요',
      stopped: '중지됨',
    },
  },
} as const;
