/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { dirname, join, relative } from 'node:path';
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';

export function generateCargoNotices(input) {
  const cargo = process.env.CARGO ?? 'cargo';
  const metadata = JSON.parse(
    execFileSync(
      cargo,
      ['metadata', '--manifest-path', input.manifestPath, '--locked', '--format-version', '1'],
      { cwd: input.repoRoot, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 },
    ),
  );
  const includedPackages = input.dependencyEdges
    ? cargoTreePackages(cargo, input, metadata)
    : metadata.packages;
  const packages = includedPackages
    .filter((pkg) => !input.excludedPackages.has(pkg.name))
    .sort((left, right) =>
      Buffer.compare(
        Buffer.from(`${left.name}@${left.version}`, 'utf8'),
        Buffer.from(`${right.name}@${right.version}`, 'utf8'),
      ),
    );
  const licenseTexts = new Map();
  const sections = packages.map((pkg) => {
    if (!pkg.license) throw new Error(`${pkg.name}@${pkg.version}: missing SPDX license metadata`);
    const directory = dirname(pkg.manifest_path);
    const licenseFiles = readdirSync(directory, { withFileTypes: true })
      .filter(
        (entry) => entry.isFile() && /^(licen[cs]e|copying|notice)(?:[._-].*)?$/iu.test(entry.name),
      )
      .map((entry) => entry.name)
      .sort();
    const fallback = licenseFiles.length === 0 ? input.resolveMissingLicenseText?.(pkg) : undefined;
    if (licenseFiles.length === 0 && !fallback && input.requireLicenseFiles !== false) {
      throw new Error(`${pkg.name}@${pkg.version}: packaged crate has no license or notice text`);
    }
    const source = pkg.repository ?? pkg.homepage ?? pkg.source ?? 'unknown';
    const heading = `${pkg.name} ${pkg.version}`;
    const renderedLicenses = [
      ...licenseFiles.map((name) => ({
        name,
        content: readFileSync(join(directory, name), 'utf8'),
      })),
      ...(fallback ? [fallback] : []),
    ].flatMap(({ name, content: rawContent }) => {
      const content = rawContent
        .replace(/\r\n?/gu, '\n')
        .replace(/[ \t]+$/gmu, '')
        .trimEnd();
      if (!input.deduplicateLicenseTexts) return ['', `--- ${name} ---`, content];
      const digest = createHash('sha256').update(content).digest('hex');
      licenseTexts.set(digest, content);
      return [`License text: sha256:${digest} (${name})`];
    });
    return [
      heading,
      '-'.repeat(heading.length),
      `SPDX license: ${pkg.license}`,
      `Source: ${source}`,
      ...(fallback?.selectedLicense ? [`Selected license: ${fallback.selectedLicense}`] : []),
      ...(fallback?.note ? [fallback.note] : []),
      ...renderedLicenses,
    ].join('\n');
  });
  const deduplicatedLicenses = [...licenseTexts.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([digest, content]) => `sha256:${digest}\n${'-'.repeat(71)}\n${content}`);
  const lockDigest = createHash('sha256').update(readFileSync(input.lockPath)).digest('hex');
  const output = `${input.title}
${'='.repeat(input.titleUnderlineLength ?? input.title.length)}

Generated by ${relative(input.repoRoot, input.generatorPath).replaceAll('\\', '/')} from the exact
${input.dependencyEdges ? 'active Cargo.lock dependency closure' : 'Cargo.lock dependency graph'}. Do not edit this file by hand.

Manifest: ${relative(input.repoRoot, input.manifestPath).replaceAll('\\', '/')}
Cargo.lock SHA-256: ${lockDigest}

${sections.join('\n\n')}${
  deduplicatedLicenses.length > 0
    ? `\n\nDeduplicated license and notice texts\n=====================================\n\n${deduplicatedLicenses.join('\n\n')}`
    : ''
}
`;
  if (input.check) {
    if (readFileSync(input.outputPath, 'utf8') !== output) throw new Error(input.staleMessage);
  } else {
    writeFileSync(input.outputPath, output);
  }
}

function cargoTreePackages(cargo, input, metadata) {
  const output = execFileSync(
    cargo,
    [
      'tree',
      '--manifest-path',
      input.manifestPath,
      '--locked',
      '--target',
      'all',
      '--edges',
      input.dependencyEdges.join(','),
      '--prefix',
      'none',
      '--format',
      '{p}',
    ],
    { cwd: input.repoRoot, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 },
  );
  const packageKeys = new Set(
    output
      .split(/\r?\n/u)
      .map((line) => /^(\S+) v(\S+)/u.exec(line))
      .filter(Boolean)
      .map((match) => `${match[1]}@${match[2]}`),
  );
  return metadata.packages.filter((pkg) => packageKeys.has(`${pkg.name}@${pkg.version}`));
}
