/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

import assert from 'node:assert/strict';
import { test } from 'node:test';
import { comparePathArtifact, inventoryDrift } from './astryx-surface-inventory-contract.mjs';

const rendered = {
  files: ['packages/ui/src/first.tsx', 'packages/ui/src/second.tsx'],
  paths: 'packages/ui/src/first.tsx\npackages/ui/src/second.tsx\n',
  markdown: '# Surface inventory\n| first |\n| second |\n',
};

test('accepts both artifacts only when they match the generated bytes', () => {
  assert.deepEqual(inventoryDrift(rendered, rendered), []);
  assert.deepEqual(inventoryDrift(rendered, { ...rendered, paths: rendered.paths.trimEnd() }), [
    '.paths does not match generator output',
  ]);
});

test('rejects a stale Markdown table even when the path list is current', () => {
  assert.deepEqual(
    inventoryDrift(rendered, { ...rendered, markdown: '# Surface inventory\n| first |\n' }),
    ['docs/astryx-surface-file-inventory.md does not match generator output'],
  );
});

test('diagnoses missing and extra paths independently of Markdown drift', () => {
  assert.deepEqual(
    inventoryDrift(rendered, {
      paths: 'packages/ui/src/first.tsx\npackages/ui/src/old.tsx\n',
      markdown: rendered.markdown,
    }),
    [
      '.paths does not match generator output',
      'on disk but not in .paths (1):\n  packages/ui/src/second.tsx',
      'in .paths but not on disk (1):\n  packages/ui/src/old.tsx',
    ],
  );
});

test('reports path-only drift without parsing Markdown', () => {
  assert.deepEqual(
    comparePathArtifact(rendered, 'packages/ui/src/first.tsx\npackages/ui/src/old.tsx\n'),
    [
      '.paths does not match generator output',
      'on disk but not in .paths (1):\n  packages/ui/src/second.tsx',
      'in .paths but not on disk (1):\n  packages/ui/src/old.tsx',
    ],
  );
});
