import type { AppSettings, UpdateAppSettingsInput } from '@maka/core/settings';
import type { CredentialRoutingStrategy } from '@maka/core/runtime-policy';
import {
  PROVIDER_DEFAULTS,
  reconcileConnectionAfterEnabledModelsChange,
  type LlmConnection,
} from '@maka/core/llm-connections';
import {
  CONFIG_TRANSFER_LEGACY_SCHEMA_VERSION,
  type ConfigBundle,
  type ConfigCategory,
  type ConfigData,
  type ConnectionConflictStrategy,
  type CredentialKind,
  buildConfigBundle,
  planConnectionMerge,
} from '@maka/storage';
import { stripSettingsSecretsForExport } from './settings-ipc-helpers.js';

/**
 * Desktop-side orchestration for config import/export. Kept store-injected and
 * Electron-free so it is unit-testable; the IPC handlers in main.ts are thin
 * wrappers that supply the real stores + file dialogs.
 *
 * The credential category (opt-in, plaintext) is gathered by walking the
 * connection list and reading each slug's connection credentials — the
 * credential store exposes no bulk-list, so enumeration is the only path.
 *
 * Schema v2 extends the bundle with Credential Profile metadata: every
 * connection payload carries `credentialProfiles` (export-local `profileRef`,
 * label, enabled, weight, primary), and credential entries reference
 * `connectionSlug + profileRef + kind` so secondary secrets survive a
 * round-trip. `profileRef 'primary'` maps to the target `connectionId`;
 * secondary profile IDs are generated by the target Catalog authority.
 */

export const EXPORT_PRIMARY_PROFILE_REF = 'primary';

export interface ExportedProfileMeta {
  readonly profileRef: string;
  readonly profileId: string;
  readonly label: string;
  readonly enabled: boolean;
  readonly weight: number;
  readonly primary: boolean;
}

export interface V2ExportedConnection extends LlmConnection {
  readonly credentialProfiles?: readonly ExportedProfileMeta[];
  readonly routingMode?: 'legacy_primary' | 'balanced';
  readonly routingStrategy?: CredentialRoutingStrategy;
}

export interface ExportedCredential {
  slug: string;
  kind: CredentialKind;
  value: string;
  /** v2: profileRef ('primary' or a secondary ref); v1 entries have none. */
  profileRef?: string;
}

export interface ProfileImportOutcome {
  readonly created: number;
  readonly updated: number;
  readonly skipped: number;
  readonly labelConflicts: readonly string[];
  readonly verificationFailed: readonly string[];
  readonly restoredEnabled: number;
  readonly balancedRestored: boolean;
  readonly balancedPending: boolean;
}

const CONNECTION_CREDENTIAL_KINDS: readonly CredentialKind[] = [
  'api_key',
  'oauth_token',
  'request_headers',
];
const VALID_CREDENTIAL_KINDS: ReadonlySet<string> = new Set<CredentialKind>([
  'api_key',
  'oauth_token',
  'request_headers',
  'bot_token',
  'app_secret',
  'proxy_password',
  'tavily_api_key',
]);

export interface ConfigTransferDeps {
  connectionStore: { list(): Promise<LlmConnection[]>; save(c: LlmConnection): Promise<LlmConnection> };
  settingsStore: { get(): Promise<AppSettings>; update(patch: UpdateAppSettingsInput): Promise<AppSettings> };
  credentialStore: {
    getSecret(slug: string, kind: CredentialKind): Promise<string | null>;
    setSecret(slug: string, kind: CredentialKind, value: string): Promise<void>;
  };
  readMemory(): Promise<string | null>;
  writeMemory(content: string): Promise<void>;
  appVersion: string;
  /** v2-only: Profile-aware operations against the Runtime Host. */
  profiles?: {
    list(slug: string): Promise<{
      readonly connectionRevision: number;
      readonly routingMode: 'legacy_primary' | 'balanced';
      readonly readyCandidateCount: number;
      readonly profiles: ReadonlyArray<{
        readonly profileId: string;
        readonly revision: number;
        readonly label: string;
        readonly enabled: boolean;
        readonly weight: number;
        readonly primary: boolean;
        readonly credentialConfigured: boolean;
        readonly supportedModels: readonly string[];
      }>;
    }>;
    create(slug: string, input: { label: string; weight: number }): Promise<void>;
    update(
      slug: string,
      input: { profileId: string; profileRevision: number; label?: string; weight?: number },
    ): Promise<void>;
    setEnabled(
      slug: string,
      input: { profileId: string; profileRevision: number; enabled: boolean },
    ): Promise<void>;
    setRoutingMode(
      slug: string,
      input: {
        mode: 'legacy_primary' | 'balanced';
        strategy?: CredentialRoutingStrategy;
        orderedProfileIds?: readonly string[];
      },
    ): Promise<void>;
    setCredential(
      slug: string,
      input: { profileId: string; secret: string; kind: 'api_key' | 'oauth_token' },
    ): Promise<void>;
    test(slug: string, input: { profileId: string }): Promise<{ ok: boolean }>;
    /** Materialize the implicit primary into an explicit routing declaration. */
    materializePrimary(slug: string): Promise<void>;
  };
}

export async function gatherConfigExport(
  categories: readonly ConfigCategory[],
  deps: ConfigTransferDeps,
): Promise<ConfigBundle> {
  const selected = new Set(categories);
  const data: ConfigData = {};

  const connections = selected.has('connections') || selected.has('credentials')
    ? await deps.connectionStore.list()
    : [];

  if (selected.has('connections')) {
    data.connections = connections;
  }

  if (selected.has('settings')) {
    const settings = await deps.settingsStore.get();
    // When credentials are included, settings keeps its embedded secrets
    // (proxy password, bot tokens, Tavily key); otherwise strip.
    data.settings = selected.has('credentials') ? settings : stripSettingsSecretsForExport(settings);
  }

  if (selected.has('credentials')) {
    const creds: ExportedCredential[] = [];
    for (const connection of connections) {
      for (const kind of CONNECTION_CREDENTIAL_KINDS) {
        const value = await deps.credentialStore.getSecret(connection.slug, kind);
        if (value) creds.push({ slug: connection.slug, kind, value });
      }
    }
    data.credentials = creds;
  }

  if (selected.has('memory')) {
    const memory = await deps.readMemory();
    if (memory !== null) data.memory = memory;
  }

  return buildConfigBundle({ appVersion: deps.appVersion, data });
}

export interface ConfigImportResult {
  connections?: { created: number; overwritten: number; skipped: number };
  settings?: { applied: boolean };
  credentials?: { applied: number; skipped: number };
  memory?: { applied: boolean };
  profiles?: ProfileImportOutcome;
}

export async function applyConfigImport(
  bundle: ConfigBundle,
  strategy: ConnectionConflictStrategy,
  deps: ConfigTransferDeps,
): Promise<ConfigImportResult> {
  if (bundle.schemaVersion !== CONFIG_TRANSFER_LEGACY_SCHEMA_VERSION && deps.profiles) {
    return applyV2ConfigImport(bundle, strategy, deps);
  }
  return applyLegacyConfigImport(bundle, strategy, deps);
}

/**
 * Schema v1 / legacy single-credential path — unchanged behavior. Secondary
 * Profile secrets are not part of v1 bundles, so nothing here invents them.
 */
async function applyLegacyConfigImport(
  bundle: ConfigBundle,
  strategy: ConnectionConflictStrategy,
  deps: ConfigTransferDeps,
): Promise<ConfigImportResult> {
  const result: ConfigImportResult = {};
  // Credentials are only applied for connections actually written this import
  // (created or overwritten). A slug the user chose to skip must not have its
  // stored secret silently overwritten.
  const appliedConnectionSlugs = new Set<string>();

  if (Array.isArray(bundle.data.connections)) {
    const incoming = bundle.data.connections as LlmConnection[];
    const existing = await deps.connectionStore.list();
    const plan = planConnectionMerge(existing, incoming, strategy);
    for (const connection of [...plan.create, ...plan.overwrite]) {
      // A backup states its selection, so restoring it restores that selection.
      // `save()` is a snapshot boundary and cannot tell a stated selection from
      // an echoed one, so the caller that knows applies the rule — otherwise
      // the read-time shim merged the default back in and the import quietly
      // re-enabled a model the backup had disabled.
      const selection = connection.enabledModelIds
        ? reconcileConnectionAfterEnabledModelsChange(connection, connection.enabledModelIds)
        : null;
      await deps.connectionStore.save(selection ? { ...connection, ...selection } : connection);
      appliedConnectionSlugs.add(connection.slug);
    }
    result.connections = {
      created: plan.create.length,
      overwritten: plan.overwrite.length,
      skipped: plan.skipped.length,
    };
  }

  if (bundle.data.settings && typeof bundle.data.settings === 'object') {
    await deps.settingsStore.update(bundle.data.settings as unknown as UpdateAppSettingsInput);
    result.settings = { applied: true };
  }

  if (Array.isArray(bundle.data.credentials)) {
    let applied = 0;
    let skipped = 0;
    for (const entry of bundle.data.credentials as ExportedCredential[]) {
      const valid =
        entry &&
        typeof entry.slug === 'string' &&
        typeof entry.value === 'string' &&
        entry.value.length > 0 &&
        VALID_CREDENTIAL_KINDS.has(entry.kind);
      if (!valid) continue;
      // Only write a secret for a connection that was created or overwritten
      // in this import. Skipped (or not-imported) slugs keep their existing
      // stored secret untouched.
      if (!appliedConnectionSlugs.has(entry.slug)) {
        skipped += 1;
        continue;
      }
      await deps.credentialStore.setSecret(entry.slug, entry.kind, entry.value);
      applied += 1;
    }
    result.credentials = { applied, skipped };
  }

  if (typeof bundle.data.memory === 'string') {
    await deps.writeMemory(bundle.data.memory);
    result.memory = { applied: true };
  }

  return result;
}

/**
 * Schema v2 profile-aware import (RFC 13.4). Ordered so a partial failure
 * never fabricates readiness:
 *
 * 1. import/create Connections
 * 2. create all Profiles (enabled=false, routing stays legacy_primary)
 * 3. write per-locator credentials
 * 4. validate structure/credential kinds (each write path validates)
 * 5. re-run profile test for Profiles that were enabled in the bundle
 * 6. restore enabled only for Profiles that verified
 * 7. restore balanced mode only when its activation gates still hold
 *
 * Locator mapping: (source slug, source profileRef) -> (target connectionId,
 * target profileId). The primary profileRef maps to the target connection
 * identity; secondary profile IDs are generated by the target Catalog
 * authority. Overwrite updates a profile in place only when the profile ID
 * matches exactly; a label conflict with a different ID is reported and the
 * secret is never written to it. Profiles absent from the bundle are kept.
 */
async function applyV2ConfigImport(
  bundle: ConfigBundle,
  strategy: ConnectionConflictStrategy,
  deps: ConfigTransferDeps,
): Promise<ConfigImportResult> {
  const profiles = deps.profiles!;
  const result: ConfigImportResult = {};
  const appliedConnectionSlugs = new Set<string>();
  // slug -> profileRef -> target profileId ('primary' for the connection id)
  const mappings = new Map<string, Map<string, string>>();
  const labelConflicts: string[] = [];
  const verificationFailed: string[] = [];
  let createdProfiles = 0;
  let updatedProfiles = 0;
  let skippedProfiles = 0;
  let restoredEnabled = 0;
  let balancedRestored = false;
  let balancedPending = false;
  // slug -> profileIds the quiesce disabled; the restore pass re-enables the
  // ones the bundle did not list. The primary is quiesced too: overwrite
  // credential replacement must never happen while the primary is dispatchable
  // (RFC 13.4 lifecycle applies to every profile).
  const quiescedProfiles = new Map<string, Set<string>>();
  // slug -> target profile ids the bundle claimed (mapped, regardless of
  // enabled state or verification outcome). Profile identity is scoped per
  // Connection, so the set is per slug: the quiesce restore must never
  // re-enable a profile the bundle deliberately disabled or that failed
  // re-verification, and one connection's listing must not block another
  // connection's absent-profile restore.
  const listedTargetProfileIds = new Map<string, Set<string>>();

  if (Array.isArray(bundle.data.connections)) {
    const incoming = bundle.data.connections as V2ExportedConnection[];
    const existing = await deps.connectionStore.list();
    const plan = planConnectionMerge(existing, incoming, strategy);
    const existingBySlug = new Map(existing.map((connection) => [connection.slug, connection]));
    const createSlugs = new Set(plan.create.map((connection) => connection.slug));
    const sourceFor = (connection: LlmConnection): V2ExportedConnection =>
      (incoming.find((candidate) => candidate.slug === connection.slug) ??
        connection) as V2ExportedConnection;
    const isProfileAware = (connection: LlmConnection): boolean => {
      const source = sourceFor(connection);
      return source.credentialProfiles !== undefined || source.routingMode !== undefined;
    };
    const quiesceConnection = async (slug: string): Promise<void> => {
      await profiles.materializePrimary(slug);
      const current = await profiles.list(slug);
      if (current.routingMode === 'balanced') {
        await profiles.setRoutingMode(slug, { mode: 'legacy_primary' });
      }
      const disabled = new Set<string>();
      for (const profile of current.profiles.filter((candidate) => candidate.enabled)) {
        await profiles.setEnabled(slug, {
          profileId: profile.profileId,
          profileRevision: profile.revision,
          enabled: false,
        });
        disabled.add(profile.profileId);
      }
      if (disabled.size > 0) quiescedProfiles.set(slug, disabled);
    };

    // Existing profile-capable targets are quiesced BEFORE their endpoint,
    // overlay or credential basis can change. This closes the legacy-primary
    // window in which an old key could otherwise be dispatched to the newly
    // imported endpoint.
    for (const connection of plan.overwrite) {
      if (!isProfileAware(connection)) continue;
      const target = existingBySlug.get(connection.slug);
      if (!target || PROVIDER_DEFAULTS[target.providerType].authKind === 'none') continue;
      await quiesceConnection(connection.slug);
    }

    for (const connection of [...plan.create, ...plan.overwrite]) {
      const selection = connection.enabledModelIds
        ? reconcileConnectionAfterEnabledModelsChange(connection, connection.enabledModelIds)
        : null;
      const normalized = selection ? { ...connection, ...selection } : connection;
      const target = existingBySlug.get(connection.slug);
      const replacesProvider = target?.providerType !== undefined &&
        target.providerType !== connection.providerType;
      const needsPostSaveQuiesce =
        isProfileAware(connection) && (createSlugs.has(connection.slug) || replacesProvider);
      // A new/replaced Connection must not become dispatchable between create
      // and primary materialization. Stage it disabled, quiesce its Profiles,
      // then restore the Connection-level enabled bit while Profiles remain
      // disabled pending verification.
      const staged = needsPostSaveQuiesce && normalized.enabled
        ? { ...normalized, enabled: false }
        : normalized;
      await deps.connectionStore.save(staged);
      if (needsPostSaveQuiesce) {
        await quiesceConnection(connection.slug);
        if (staged !== normalized) {
          await deps.connectionStore.save(normalized);
        }
      }
      appliedConnectionSlugs.add(connection.slug);
    }
    result.connections = {
      created: plan.create.length,
      overwritten: plan.overwrite.length,
      skipped: plan.skipped.length,
    };

    for (const connection of [...plan.create, ...plan.overwrite]) {
      const source = sourceFor(connection);
      const slugMapping = new Map<string, string>();
      slugMapping.set(EXPORT_PRIMARY_PROFILE_REF, 'primary');
      mappings.set(connection.slug, slugMapping);
      const meta = source.credentialProfiles ?? [];
      if (meta.length === 0) continue;
      const current = await profiles.list(connection.slug);
      const byId = new Map(current.profiles.map((profile) => [profile.profileId, profile]));
      const byLabel = new Map(
        current.profiles.map((profile) => [profile.label.toLowerCase(), profile]),
      );
      for (const profile of meta) {
        if (profile.primary) {
          const primary = current.profiles.find((candidate) => candidate.primary);
          if (primary) {
            let listed = listedTargetProfileIds.get(connection.slug);
            if (!listed) {
              listed = new Set<string>();
              listedTargetProfileIds.set(connection.slug, listed);
            }
            listed.add(primary.profileId);
            const labelOwner = byLabel.get(profile.label.toLowerCase());
            if (labelOwner && labelOwner.profileId !== primary.profileId) {
              labelConflicts.push(`${connection.slug}/${profile.label}`);
              skippedProfiles += 1;
              continue;
            }
            if (primary.label !== profile.label || primary.weight !== profile.weight) {
              await profiles.update(connection.slug, {
                profileId: primary.profileId,
                profileRevision: primary.revision,
                label: profile.label,
                weight: profile.weight,
              });
              byLabel.delete(primary.label.toLowerCase());
              const updatedPrimary = {
                ...primary,
                label: profile.label,
                weight: profile.weight,
                revision: primary.revision + 1,
              };
              byId.set(primary.profileId, updatedPrimary);
              byLabel.set(profile.label.toLowerCase(), updatedPrimary);
              updatedProfiles += 1;
            }
          }
          continue;
        }
        const exact = byId.get(profile.profileId);
        if (strategy === 'overwrite' && exact) {
          const labelOwner = byLabel.get(profile.label.toLowerCase());
          if (labelOwner && labelOwner.profileId !== exact.profileId) {
            labelConflicts.push(`${connection.slug}/${profile.label}`);
            skippedProfiles += 1;
            continue;
          }
          // In-place update only for an exact profile-ID match.
          await profiles.update(connection.slug, {
            profileId: exact.profileId,
            profileRevision: exact.revision,
            label: profile.label,
            weight: profile.weight,
          });
          byLabel.delete(exact.label.toLowerCase());
          const updatedExact = {
            ...exact,
            label: profile.label,
            weight: profile.weight,
            revision: exact.revision + 1,
          };
          byId.set(exact.profileId, updatedExact);
          byLabel.set(profile.label.toLowerCase(), updatedExact);
          slugMapping.set(profile.profileRef, exact.profileId);
          let listed = listedTargetProfileIds.get(connection.slug);
          if (!listed) {
            listed = new Set<string>();
            listedTargetProfileIds.set(connection.slug, listed);
          }
          listed.add(exact.profileId);
          updatedProfiles += 1;
          continue;
        }
        const labelConflict = byLabel.get(profile.label.toLowerCase());
        if (labelConflict) {
          // A different profile already owns this label: report, keep it out
          // of the mapping so no secret can be written against the wrong id.
          labelConflicts.push(`${connection.slug}/${profile.label}`);
          skippedProfiles += 1;
          continue;
        }
        await profiles.create(connection.slug, {
          label: profile.label,
          weight: profile.weight,
        });
        createdProfiles += 1;
        const fresh = await profiles.list(connection.slug);
        const createdTarget = fresh.profiles.find(
          (candidate) =>
            !candidate.primary && candidate.label.toLowerCase() === profile.label.toLowerCase(),
        );
        if (createdTarget) {
          slugMapping.set(profile.profileRef, createdTarget.profileId);
          byId.set(createdTarget.profileId, createdTarget);
          byLabel.set(createdTarget.label.toLowerCase(), createdTarget);
          let listed = listedTargetProfileIds.get(connection.slug);
          if (!listed) {
            listed = new Set<string>();
            listedTargetProfileIds.set(connection.slug, listed);
          }
          listed.add(createdTarget.profileId);
        }
      }
    }
  }

  if (bundle.data.settings && typeof bundle.data.settings === 'object') {
    await deps.settingsStore.update(bundle.data.settings as unknown as UpdateAppSettingsInput);
    result.settings = { applied: true };
  }

  if (Array.isArray(bundle.data.credentials)) {
    let applied = 0;
    let skipped = 0;
    for (const entry of bundle.data.credentials as ExportedCredential[]) {
      const valid =
        entry &&
        typeof entry.slug === 'string' &&
        typeof entry.value === 'string' &&
        entry.value.length > 0 &&
        VALID_CREDENTIAL_KINDS.has(entry.kind);
      if (!valid) continue;
      if (!appliedConnectionSlugs.has(entry.slug)) {
        skipped += 1;
        continue;
      }
      const slugMapping = mappings.get(entry.slug);
      if (!slugMapping) {
        skipped += 1;
        continue;
      }
      const profileRef = entry.profileRef ?? EXPORT_PRIMARY_PROFILE_REF;
      const targetProfileId = slugMapping.get(profileRef);
      // Unmapped refs include label conflicts — their secrets stay out.
      if (!targetProfileId) {
        skipped += 1;
        continue;
      }
      if (targetProfileId === 'primary') {
        await deps.credentialStore.setSecret(entry.slug, entry.kind, entry.value);
      } else {
        if (entry.kind !== 'api_key' && entry.kind !== 'oauth_token') {
          skipped += 1;
          continue;
        }
        await profiles.setCredential(entry.slug, {
          profileId: targetProfileId,
          secret: entry.value,
          kind: entry.kind,
        });
      }
      applied += 1;
    }
    result.credentials = { applied, skipped };
  }

  if (typeof bundle.data.memory === 'string') {
    await deps.writeMemory(bundle.data.memory);
    result.memory = { applied: true };
  }

  // Re-verify and restore enable state for Profiles the bundle had enabled —
  // the primary is re-tested too, because a clean target starts with no
  // verification evidence and the balanced gate needs two verified profiles.
  if (Array.isArray(bundle.data.connections)) {
    for (const connection of bundle.data.connections as V2ExportedConnection[]) {
      if (!appliedConnectionSlugs.has(connection.slug)) continue;
      const slugMapping = mappings.get(connection.slug);
      if (!slugMapping) continue;
      for (const profile of connection.credentialProfiles ?? []) {
        const targetProfileId = slugMapping.get(profile.profileRef);
        if (!targetProfileId) continue;
        const fresh = await profiles.list(connection.slug);
        const target =
          targetProfileId === EXPORT_PRIMARY_PROFILE_REF
            ? fresh.profiles.find((candidate) => candidate.primary)
            : fresh.profiles.find((candidate) => candidate.profileId === targetProfileId);
        if (!profile.enabled) {
          // The bundle explicitly disabled this profile: enforce it even on
          // freshly created connections, whose primary defaults to enabled.
          if (target && target.enabled) {
            await profiles.setEnabled(connection.slug, {
              profileId: target.profileId,
              profileRevision: target.revision,
              enabled: false,
            });
          }
          continue;
        }
        const tested = await profiles.test(connection.slug, {
          profileId: targetProfileId,
        });
        if (tested.ok && target) {
          await profiles.setEnabled(connection.slug, {
            profileId: target.profileId,
            profileRevision: target.revision,
            enabled: true,
          });
          restoredEnabled += 1;
        } else {
          verificationFailed.push(`${connection.slug}/${profile.label}`);
        }
      }
      // Profiles the quiesce disabled but the bundle did not list keep their
      // metadata and credentials (RFC 13.4); restore their previous enabled
      // state so the import never silently disables an account. Profiles the
      // bundle DID claim are never restored here: the ones it disabled stay
      // disabled and the ones that failed re-verification stay disabled
      // (fail-closed) — only the restore loop above re-enables them.
      const quiesced = quiescedProfiles.get(connection.slug);
      const listed = listedTargetProfileIds.get(connection.slug);
      if (quiesced) {
        const fresh = await profiles.list(connection.slug);
        for (const profile of fresh.profiles) {
          if (
            !profile.enabled &&
            quiesced.has(profile.profileId) &&
            !listed?.has(profile.profileId)
          ) {
            await profiles.setEnabled(connection.slug, {
              profileId: profile.profileId,
              profileRevision: profile.revision,
              enabled: true,
            });
            restoredEnabled += 1;
          }
        }
      }
      if (connection.routingMode === 'balanced') {
        try {
          const freshProfiles = await profiles.list(connection.slug);
          const orderedProfileIds: string[] = [];
          const orderedIds = new Set<string>();
          for (const profile of connection.credentialProfiles ?? []) {
            const mappedId = slugMapping.get(profile.profileRef);
            const targetId =
              mappedId === EXPORT_PRIMARY_PROFILE_REF
                ? freshProfiles.profiles.find((candidate) => candidate.primary)?.profileId
                : freshProfiles.profiles.find(
                    (candidate) => candidate.profileId === mappedId,
                  )?.profileId;
            if (targetId && !orderedIds.has(targetId)) {
              orderedProfileIds.push(targetId);
              orderedIds.add(targetId);
            }
          }
          for (const profile of freshProfiles.profiles) {
            if (!orderedIds.has(profile.profileId)) {
              orderedProfileIds.push(profile.profileId);
              orderedIds.add(profile.profileId);
            }
          }
          await profiles.setRoutingMode(connection.slug, {
            mode: 'balanced',
            ...(connection.routingStrategy === undefined
              ? {}
              : { strategy: connection.routingStrategy }),
            ...(orderedProfileIds.length === freshProfiles.profiles.length
              ? { orderedProfileIds }
              : {}),
          });
          balancedRestored = true;
        } catch {
          // Activation gates (2+ verified profiles on one enabled model) no
          // longer hold — stay on legacy_primary and report it.
          balancedPending = true;
        }
      }
    }
  }

  result.profiles = {
    created: createdProfiles,
    updated: updatedProfiles,
    skipped: skippedProfiles,
    labelConflicts,
    verificationFailed,
    restoredEnabled,
    balancedRestored,
    balancedPending,
  };
  return result;
}
