import type { AppSettings, UpdateAppSettingsInput } from '@maka/core/settings';
import {
  reconcileConnectionAfterEnabledModelsChange,
  type LlmConnection,
} from '@maka/core/llm-connections';
import {
  CONFIG_TRANSFER_LEGACY_SCHEMA_VERSION,
  type ConfigBundle,
  type ConfigCategory,
  type ConfigData,
  type ConnectionConflictStrategy,
  type CredentialKind,
  buildConfigBundle,
  planConnectionMerge,
} from '@maka/storage';
import { stripSettingsSecretsForExport } from './settings-ipc-helpers.js';

/**
 * Desktop-side orchestration for config import/export. Kept store-injected and
 * Electron-free so it is unit-testable; the IPC handlers in main.ts are thin
 * wrappers that supply the real stores + file dialogs.
 *
 * The credential category (opt-in, plaintext) is gathered by walking the
 * connection list and reading each slug's connection credentials — the
 * credential store exposes no bulk-list, so enumeration is the only path.
 *
 * Schema v2 extends the bundle with Credential Profile metadata: every
 * connection payload carries `credentialProfiles` (export-local `profileRef`,
 * label, enabled, weight, primary), and credential entries reference
 * `connectionSlug + profileRef + kind` so secondary secrets survive a
 * round-trip. `profileRef 'primary'` maps to the target `connectionId`;
 * secondary profile IDs are generated by the target Catalog authority.
 */

export const EXPORT_PRIMARY_PROFILE_REF = 'primary';

export interface ExportedProfileMeta {
  readonly profileRef: string;
  readonly profileId: string;
  readonly label: string;
  readonly enabled: boolean;
  readonly weight: number;
  readonly primary: boolean;
}

export interface V2ExportedConnection extends LlmConnection {
  readonly credentialProfiles?: readonly ExportedProfileMeta[];
  readonly routingMode?: 'legacy_primary' | 'balanced';
}

export interface ExportedCredential {
  slug: string;
  kind: CredentialKind;
  value: string;
  /** v2: profileRef ('primary' or a secondary ref); v1 entries have none. */
  profileRef?: string;
}

export interface ProfileImportOutcome {
  readonly created: number;
  readonly updated: number;
  readonly skipped: number;
  readonly labelConflicts: readonly string[];
  readonly verificationFailed: readonly string[];
  readonly restoredEnabled: number;
  readonly balancedRestored: boolean;
  readonly balancedPending: boolean;
}

const CONNECTION_CREDENTIAL_KINDS: readonly CredentialKind[] = [
  'api_key',
  'oauth_token',
  'request_headers',
];
const VALID_CREDENTIAL_KINDS: ReadonlySet<string> = new Set<CredentialKind>([
  'api_key',
  'oauth_token',
  'request_headers',
  'bot_token',
  'app_secret',
  'proxy_password',
  'tavily_api_key',
]);

export interface ConfigTransferDeps {
  connectionStore: { list(): Promise<LlmConnection[]>; save(c: LlmConnection): Promise<LlmConnection> };
  settingsStore: { get(): Promise<AppSettings>; update(patch: UpdateAppSettingsInput): Promise<AppSettings> };
  credentialStore: {
    getSecret(slug: string, kind: CredentialKind): Promise<string | null>;
    setSecret(slug: string, kind: CredentialKind, value: string): Promise<void>;
  };
  readMemory(): Promise<string | null>;
  writeMemory(content: string): Promise<void>;
  appVersion: string;
  /** v2-only: Profile-aware operations against the Runtime Host. */
  profiles?: {
    list(slug: string): Promise<{
      readonly connectionRevision: number;
      readonly routingMode: 'legacy_primary' | 'balanced';
      readonly readyCandidateCount: number;
      readonly profiles: ReadonlyArray<{
        readonly profileId: string;
        readonly revision: number;
        readonly label: string;
        readonly enabled: boolean;
        readonly weight: number;
        readonly primary: boolean;
        readonly credentialConfigured: boolean;
        readonly supportedModels: readonly string[];
      }>;
    }>;
    create(slug: string, input: { label: string; weight: number }): Promise<void>;
    update(
      slug: string,
      input: { profileId: string; profileRevision: number; label?: string; weight?: number },
    ): Promise<void>;
    setEnabled(
      slug: string,
      input: { profileId: string; profileRevision: number; enabled: boolean },
    ): Promise<void>;
    setRoutingMode(slug: string, input: { mode: 'legacy_primary' | 'balanced' }): Promise<void>;
    setCredential(slug: string, input: { profileId: string; secret: string }): Promise<void>;
    test(slug: string, input: { profileId: string }): Promise<{ ok: boolean }>;
  };
}

export async function gatherConfigExport(
  categories: readonly ConfigCategory[],
  deps: ConfigTransferDeps,
): Promise<ConfigBundle> {
  const selected = new Set(categories);
  const data: ConfigData = {};

  const connections = selected.has('connections') || selected.has('credentials')
    ? await deps.connectionStore.list()
    : [];

  if (selected.has('connections')) {
    data.connections = connections;
  }

  if (selected.has('settings')) {
    const settings = await deps.settingsStore.get();
    // When credentials are included, settings keeps its embedded secrets
    // (proxy password, bot tokens, Tavily key); otherwise strip.
    data.settings = selected.has('credentials') ? settings : stripSettingsSecretsForExport(settings);
  }

  if (selected.has('credentials')) {
    const creds: ExportedCredential[] = [];
    for (const connection of connections) {
      for (const kind of CONNECTION_CREDENTIAL_KINDS) {
        const value = await deps.credentialStore.getSecret(connection.slug, kind);
        if (value) creds.push({ slug: connection.slug, kind, value });
      }
    }
    data.credentials = creds;
  }

  if (selected.has('memory')) {
    const memory = await deps.readMemory();
    if (memory !== null) data.memory = memory;
  }

  return buildConfigBundle({ appVersion: deps.appVersion, data });
}

export interface ConfigImportResult {
  connections?: { created: number; overwritten: number; skipped: number };
  settings?: { applied: boolean };
  credentials?: { applied: number; skipped: number };
  memory?: { applied: boolean };
  profiles?: ProfileImportOutcome;
}

export async function applyConfigImport(
  bundle: ConfigBundle,
  strategy: ConnectionConflictStrategy,
  deps: ConfigTransferDeps,
): Promise<ConfigImportResult> {
  if (bundle.schemaVersion !== CONFIG_TRANSFER_LEGACY_SCHEMA_VERSION && deps.profiles) {
    return applyV2ConfigImport(bundle, strategy, deps);
  }
  return applyLegacyConfigImport(bundle, strategy, deps);
}

/**
 * Schema v1 / legacy single-credential path — unchanged behavior. Secondary
 * Profile secrets are not part of v1 bundles, so nothing here invents them.
 */
async function applyLegacyConfigImport(
  bundle: ConfigBundle,
  strategy: ConnectionConflictStrategy,
  deps: ConfigTransferDeps,
): Promise<ConfigImportResult> {
  const result: ConfigImportResult = {};
  // Credentials are only applied for connections actually written this import
  // (created or overwritten). A slug the user chose to skip must not have its
  // stored secret silently overwritten.
  const appliedConnectionSlugs = new Set<string>();

  if (Array.isArray(bundle.data.connections)) {
    const incoming = bundle.data.connections as LlmConnection[];
    const existing = await deps.connectionStore.list();
    const plan = planConnectionMerge(existing, incoming, strategy);
    for (const connection of [...plan.create, ...plan.overwrite]) {
      // A backup states its selection, so restoring it restores that selection.
      // `save()` is a snapshot boundary and cannot tell a stated selection from
      // an echoed one, so the caller that knows applies the rule — otherwise
      // the read-time shim merged the default back in and the import quietly
      // re-enabled a model the backup had disabled.
      const selection = connection.enabledModelIds
        ? reconcileConnectionAfterEnabledModelsChange(connection, connection.enabledModelIds)
        : null;
      await deps.connectionStore.save(selection ? { ...connection, ...selection } : connection);
      appliedConnectionSlugs.add(connection.slug);
    }
    result.connections = {
      created: plan.create.length,
      overwritten: plan.overwrite.length,
      skipped: plan.skipped.length,
    };
  }

  if (bundle.data.settings && typeof bundle.data.settings === 'object') {
    await deps.settingsStore.update(bundle.data.settings as unknown as UpdateAppSettingsInput);
    result.settings = { applied: true };
  }

  if (Array.isArray(bundle.data.credentials)) {
    let applied = 0;
    let skipped = 0;
    for (const entry of bundle.data.credentials as ExportedCredential[]) {
      const valid =
        entry &&
        typeof entry.slug === 'string' &&
        typeof entry.value === 'string' &&
        entry.value.length > 0 &&
        VALID_CREDENTIAL_KINDS.has(entry.kind);
      if (!valid) continue;
      // Only write a secret for a connection that was created or overwritten
      // in this import. Skipped (or not-imported) slugs keep their existing
      // stored secret untouched.
      if (!appliedConnectionSlugs.has(entry.slug)) {
        skipped += 1;
        continue;
      }
      await deps.credentialStore.setSecret(entry.slug, entry.kind, entry.value);
      applied += 1;
    }
    result.credentials = { applied, skipped };
  }

  if (typeof bundle.data.memory === 'string') {
    await deps.writeMemory(bundle.data.memory);
    result.memory = { applied: true };
  }

  return result;
}

/**
 * Schema v2 profile-aware import (RFC 13.4). Ordered so a partial failure
 * never fabricates readiness:
 *
 * 1. import/create Connections
 * 2. create all Profiles (enabled=false, routing stays legacy_primary)
 * 3. write per-locator credentials
 * 4. validate structure/credential kinds (each write path validates)
 * 5. re-run profile test for Profiles that were enabled in the bundle
 * 6. restore enabled only for Profiles that verified
 * 7. restore balanced mode only when its activation gates still hold
 *
 * Locator mapping: (source slug, source profileRef) -> (target connectionId,
 * target profileId). The primary profileRef maps to the target connection
 * identity; secondary profile IDs are generated by the target Catalog
 * authority. Overwrite updates a profile in place only when the profile ID
 * matches exactly; a label conflict with a different ID is reported and the
 * secret is never written to it. Profiles absent from the bundle are kept.
 */
async function applyV2ConfigImport(
  bundle: ConfigBundle,
  strategy: ConnectionConflictStrategy,
  deps: ConfigTransferDeps,
): Promise<ConfigImportResult> {
  const profiles = deps.profiles!;
  const result: ConfigImportResult = {};
  const appliedConnectionSlugs = new Set<string>();
  // slug -> profileRef -> target profileId ('primary' for the connection id)
  const mappings = new Map<string, Map<string, string>>();
  const labelConflicts: string[] = [];
  const verificationFailed: string[] = [];
  let createdProfiles = 0;
  let updatedProfiles = 0;
  let skippedProfiles = 0;
  let restoredEnabled = 0;
  let balancedRestored = false;
  let balancedPending = false;

  if (Array.isArray(bundle.data.connections)) {
    const incoming = bundle.data.connections as V2ExportedConnection[];
    const existing = await deps.connectionStore.list();
    const plan = planConnectionMerge(existing, incoming, strategy);
    for (const connection of [...plan.create, ...plan.overwrite]) {
      const selection = connection.enabledModelIds
        ? reconcileConnectionAfterEnabledModelsChange(connection, connection.enabledModelIds)
        : null;
      await deps.connectionStore.save(selection ? { ...connection, ...selection } : connection);
      appliedConnectionSlugs.add(connection.slug);
    }
    result.connections = {
      created: plan.create.length,
      overwritten: plan.overwrite.length,
      skipped: plan.skipped.length,
    };

    // Quiesce before touching any credential: an overwritten connection that
    // still declares balanced routing must drop to legacy_primary and every
    // enabled secondary must be disabled FIRST, so a partial failure can never
    // leave "balanced declared + credentials partially replaced". Newly
    // created connections have no routing declaration and skip this pass.
    for (const connection of plan.overwrite) {
      const current = await profiles.list(connection.slug);
      if (current.routingMode === 'balanced') {
        await profiles.setRoutingMode(connection.slug, { mode: 'legacy_primary' });
      }
      for (const secondary of current.profiles.filter(
        (candidate) => !candidate.primary && candidate.enabled,
      )) {
        await profiles.setEnabled(connection.slug, {
          profileId: secondary.profileId,
          profileRevision: secondary.revision,
          enabled: false,
        });
      }
    }

    for (const connection of [...plan.create, ...plan.overwrite]) {
      const source =
        (incoming.find((candidate) => candidate.slug === connection.slug) ??
          connection) as V2ExportedConnection;
      const slugMapping = new Map<string, string>();
      slugMapping.set(EXPORT_PRIMARY_PROFILE_REF, 'primary');
      mappings.set(connection.slug, slugMapping);
      const meta = source.credentialProfiles ?? [];
      if (meta.length === 0) continue;
      const current = await profiles.list(connection.slug);
      const byId = new Map(current.profiles.map((profile) => [profile.profileId, profile]));
      const byLabel = new Map(
        current.profiles
          .filter((profile) => !profile.primary)
          .map((profile) => [profile.label.toLowerCase(), profile]),
      );
      for (const profile of meta) {
        if (profile.primary) continue;
        const exact = byId.get(profile.profileId);
        if (strategy === 'overwrite' && exact) {
          // In-place update only for an exact profile-ID match.
          await profiles.update(connection.slug, {
            profileId: exact.profileId,
            profileRevision: exact.revision,
            label: profile.label,
            weight: profile.weight,
          });
          slugMapping.set(profile.profileRef, exact.profileId);
          updatedProfiles += 1;
          continue;
        }
        const labelConflict = byLabel.get(profile.label.toLowerCase());
        if (labelConflict) {
          // A different profile already owns this label: report, keep it out
          // of the mapping so no secret can be written against the wrong id.
          labelConflicts.push(`${connection.slug}/${profile.label}`);
          skippedProfiles += 1;
          continue;
        }
        await profiles.create(connection.slug, {
          label: profile.label,
          weight: profile.weight,
        });
        createdProfiles += 1;
        const fresh = await profiles.list(connection.slug);
        const createdTarget = fresh.profiles.find(
          (candidate) =>
            !candidate.primary && candidate.label.toLowerCase() === profile.label.toLowerCase(),
        );
        if (createdTarget) slugMapping.set(profile.profileRef, createdTarget.profileId);
      }
    }
  }

  if (bundle.data.settings && typeof bundle.data.settings === 'object') {
    await deps.settingsStore.update(bundle.data.settings as unknown as UpdateAppSettingsInput);
    result.settings = { applied: true };
  }

  if (Array.isArray(bundle.data.credentials)) {
    let applied = 0;
    let skipped = 0;
    for (const entry of bundle.data.credentials as ExportedCredential[]) {
      const valid =
        entry &&
        typeof entry.slug === 'string' &&
        typeof entry.value === 'string' &&
        entry.value.length > 0 &&
        VALID_CREDENTIAL_KINDS.has(entry.kind);
      if (!valid) continue;
      if (!appliedConnectionSlugs.has(entry.slug)) {
        skipped += 1;
        continue;
      }
      const slugMapping = mappings.get(entry.slug);
      if (!slugMapping) {
        skipped += 1;
        continue;
      }
      const profileRef = entry.profileRef ?? EXPORT_PRIMARY_PROFILE_REF;
      const targetProfileId = slugMapping.get(profileRef);
      // Unmapped refs include label conflicts — their secrets stay out.
      if (!targetProfileId) {
        skipped += 1;
        continue;
      }
      if (targetProfileId === 'primary') {
        await deps.credentialStore.setSecret(entry.slug, entry.kind, entry.value);
      } else {
        // PR4 scope is API-key profiles; OAuth profile material is a later PR.
        if (entry.kind !== 'api_key') {
          skipped += 1;
          continue;
        }
        await profiles.setCredential(entry.slug, {
          profileId: targetProfileId,
          secret: entry.value,
        });
      }
      applied += 1;
    }
    result.credentials = { applied, skipped };
  }

  if (typeof bundle.data.memory === 'string') {
    await deps.writeMemory(bundle.data.memory);
    result.memory = { applied: true };
  }

  // Re-verify and restore enable state for Profiles the bundle had enabled —
  // the primary is re-tested too, because a clean target starts with no
  // verification evidence and the balanced gate needs two verified profiles.
  if (Array.isArray(bundle.data.connections)) {
    for (const connection of bundle.data.connections as V2ExportedConnection[]) {
      if (!appliedConnectionSlugs.has(connection.slug)) continue;
      const slugMapping = mappings.get(connection.slug);
      if (!slugMapping) continue;
      for (const profile of connection.credentialProfiles ?? []) {
        if (!profile.enabled) continue;
        const targetProfileId = slugMapping.get(profile.profileRef);
        if (!targetProfileId) continue;
        const tested = await profiles.test(connection.slug, {
          profileId: targetProfileId,
        });
        const fresh = await profiles.list(connection.slug);
        const target =
          targetProfileId === EXPORT_PRIMARY_PROFILE_REF
            ? fresh.profiles.find((candidate) => candidate.primary)
            : fresh.profiles.find((candidate) => candidate.profileId === targetProfileId);
        if (tested.ok && target) {
          if (!target.primary) {
            await profiles.setEnabled(connection.slug, {
              profileId: target.profileId,
              profileRevision: target.revision,
              enabled: true,
            });
          }
          restoredEnabled += 1;
        } else {
          verificationFailed.push(`${connection.slug}/${profile.label}`);
        }
      }
      if (connection.routingMode === 'balanced') {
        try {
          await profiles.setRoutingMode(connection.slug, { mode: 'balanced' });
          balancedRestored = true;
        } catch {
          // Activation gates (2+ verified profiles on one enabled model) no
          // longer hold — stay on legacy_primary and report it.
          balancedPending = true;
        }
      }
    }
  }

  result.profiles = {
    created: createdProfiles,
    updated: updatedProfiles,
    skipped: skippedProfiles,
    labelConflicts,
    verificationFailed,
    restoredEnabled,
    balancedRestored,
    balancedPending,
  };
  return result;
}
